-- Bernstein Neovim integration
-- Commands: :BernsteinRun, :BernsteinStatus, :BernsteinPlan, :BernsteinStop
--
-- Generated by bernstein.core.protocols.neovim_bridge
-- Do not edit manually; regenerate with generate_plugin_lua().

local M = {}

M.config = {
  server_url = "http://127.0.0.1:8052",
  split_direction = "botright",
  split_height = 15,
  statusline = true,
  auto_refresh = true,
  refresh_interval_ms = 5000,
}

-- Internal state -------------------------------------------------------

local _buf = nil
local _win = nil
local _timer = nil

-- Helpers --------------------------------------------------------------

local function request(method, path, body)
  local url = M.config.server_url .. path
  local cmd
  if method == "GET" then
    cmd = string.format("curl -s -X GET %s", vim.fn.shellescape(url))
  else
    local json = body or "{}"
    cmd = string.format(
      "curl -s -X %s -H 'Content-Type: application/json' -d %s %s",
      method,
      vim.fn.shellescape(json),
      vim.fn.shellescape(url)
    )
  end
  local result = vim.fn.system(cmd)
  local ok, decoded = pcall(vim.fn.json_decode, result)
  if ok then
    return decoded
  end
  return { error = result }
end

local function open_split()
  if _win and vim.api.nvim_win_is_valid(_win) then
    vim.api.nvim_set_current_win(_win)
    return
  end
  vim.cmd(M.config.split_direction .. " " .. M.config.split_height .. "split")
  _buf = vim.api.nvim_create_buf(false, true)
  _win = vim.api.nvim_get_current_win()
  vim.api.nvim_win_set_buf(_win, _buf)
  vim.api.nvim_buf_set_option(_buf, "buftype", "nofile")
  vim.api.nvim_buf_set_option(_buf, "filetype", "bernstein")
  vim.api.nvim_buf_set_option(_buf, "modifiable", false)
end

local function set_buf_lines(lines)
  if not _buf or not vim.api.nvim_buf_is_valid(_buf) then
    return
  end
  vim.api.nvim_buf_set_option(_buf, "modifiable", true)
  vim.api.nvim_buf_set_lines(_buf, 0, -1, false, lines)
  vim.api.nvim_buf_set_option(_buf, "modifiable", false)
end

local function format_status(data)
  local lines = {}
  table.insert(lines, "--- Bernstein Status ---")
  table.insert(lines, "")
  if data.error then
    table.insert(lines, "Error: " .. tostring(data.error))
  else
    for k, v in pairs(data) do
      table.insert(lines, string.format("  %s: %s", k, tostring(v)))
    end
  end
  table.insert(lines, "")
  table.insert(lines, "--- End ---")
  return lines
end

-- Commands -------------------------------------------------------------

function M.run(opts)
  local plan = (opts and opts.args ~= "") and opts.args or nil
  local body = plan and vim.fn.json_encode({ plan_file = plan }) or "{}"
  local resp = request("POST", "/tasks", body)
  if resp and not resp.error then
    vim.notify("[Bernstein] Run started", vim.log.levels.INFO)
  else
    vim.notify("[Bernstein] Run failed: " .. tostring(resp and resp.error or "unknown"), vim.log.levels.ERROR)
  end
end

function M.status()
  open_split()
  local data = request("GET", "/status")
  local lines = format_status(data or {})
  set_buf_lines(lines)
end

function M.plan(opts)
  local file = (opts and opts.args ~= "") and opts.args or nil
  if not file then
    vim.notify("[Bernstein] Usage: :BernsteinPlan <file>", vim.log.levels.WARN)
    return
  end
  vim.cmd("edit " .. file)
  vim.notify("[Bernstein] Plan loaded: " .. file, vim.log.levels.INFO)
end

function M.stop()
  vim.notify("[Bernstein] Sending stop signal...", vim.log.levels.INFO)
  request("POST", "/stop")
  vim.notify("[Bernstein] Stop signal sent", vim.log.levels.INFO)
end

-- Statusline -----------------------------------------------------------

function M.statusline()
  local ok, data = pcall(request, "GET", "/status")
  if not ok or not data or data.error then
    return "[BST:offline]"
  end
  local total = data.total_tasks or 0
  local completed = data.completed_tasks or 0
  local agents = data.active_agents or 0
  local state = data.state or "unknown"
  return string.format("[BST:%s] %d/%d tasks | %d agents", state, completed, total, agents)
end

-- Auto-refresh ---------------------------------------------------------

function M.start_auto_refresh()
  if _timer then
    return
  end
  _timer = vim.loop.new_timer()
  _timer:start(0, M.config.refresh_interval_ms, vim.schedule_wrap(function()
    if _win and vim.api.nvim_win_is_valid(_win) then
      local data = request("GET", "/status")
      local lines = format_status(data or {})
      set_buf_lines(lines)
    end
  end))
end

function M.stop_auto_refresh()
  if _timer then
    _timer:stop()
    _timer:close()
    _timer = nil
  end
end

-- Setup ----------------------------------------------------------------

function M.setup(user_config)
  if user_config then
    M.config = vim.tbl_deep_extend("force", M.config, user_config)
  end

  vim.api.nvim_create_user_command("BernsteinRun", M.run, { nargs = "?" })
  vim.api.nvim_create_user_command("BernsteinStatus", M.status, { nargs = 0 })
  vim.api.nvim_create_user_command("BernsteinPlan", M.plan, { nargs = "?" })
  vim.api.nvim_create_user_command("BernsteinStop", M.stop, { nargs = 0 })
end

return M
