"""Evidence-bundle wiring in the opt-in auto-PR body (issue #2362, AC3).

The orchestrator auto-PR path (``_create_auto_pr`` -> ``_build_pr_body``) links
the sealed evidence bundle of a completed task, so a PR opened by the
orchestrator carries the same proof-of-done pointer as the canonical
``bernstein pr`` path. The wiring is fail-open: a missing or unreadable bundle
never blocks PR creation and leaves the body exactly as before.
"""

from __future__ import annotations

from types import SimpleNamespace
from typing import TYPE_CHECKING

from bernstein.core.models import Task

from bernstein.core.evidence.bundle import EvidenceProducer, run_evidence_gate
from bernstein.core.orchestration.orchestrator import Orchestrator
from bernstein.github_app.evidence_projection import EVIDENCE_BUNDLE_MARKER

if TYPE_CHECKING:
    from pathlib import Path

    import pytest

_KEY = b"k" * 32


def _seal_bundle(workdir: Path, task_id: str) -> None:
    """Seal a deterministic, verifiable evidence bundle for ``task_id``."""

    def runner(_p: EvidenceProducer) -> tuple[int, bytes]:
        return 0, b"5 passed\n"

    run_evidence_gate(
        workdir=workdir,
        task_id=task_id,
        producers=(EvidenceProducer(name="tests", kind="test", command=("run",), required=True),),
        runner=runner,
        timestamp=1,
        hmac_key=_KEY,
    )


def _task(task_id: str, title: str = "Do the thing", description: str = "") -> Task:
    return Task(id=task_id, title=title, description=description, role="backend")


def _self_with(workdir: Path) -> SimpleNamespace:
    """Stub ``self`` that drives the real ``_evidence_projection_for_tasks``.

    ``_build_pr_body`` resolves ``self._evidence_projection_for_tasks`` on the
    instance, so the real unbound method is bound to this namespace to exercise
    the live bundle-resolution + projection path.
    """
    ns = SimpleNamespace(
        _workdir=workdir,
        _get_pr_diff_stats=lambda _branch: {"files": 0, "insertions": 0, "deletions": 0},
    )
    ns._evidence_projection_for_tasks = lambda tasks: Orchestrator._evidence_projection_for_tasks(ns, tasks)
    return ns


def test_pr_body_links_bundle_when_task_sealed_one(tmp_path: Path) -> None:
    """A completed task with a sealed bundle yields an Evidence block + marker."""
    _seal_bundle(tmp_path, "T-auto-1")
    body = Orchestrator._build_pr_body(_self_with(tmp_path), [_task("T-auto-1")], "feature")
    assert EVIDENCE_BUNDLE_MARKER in body
    assert "## Evidence" in body
    assert "bernstein evidence verify T-auto-1" in body


def test_pr_body_omits_evidence_when_no_bundle(tmp_path: Path) -> None:
    """A completed task with no sealed bundle leaves the body exactly as before."""
    body = Orchestrator._build_pr_body(_self_with(tmp_path), [_task("T-none")], "feature")
    assert EVIDENCE_BUNDLE_MARKER not in body
    assert "## Evidence" not in body
    # Baseline body is untouched.
    assert "## Summary" in body
    assert body.strip().endswith("*Generated by Bernstein*")


def test_pr_body_swallows_bundle_resolution_error(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """An exception while resolving the bundle is swallowed; the body still renders."""

    def _boom(*_a: object, **_k: object) -> object:
        raise RuntimeError("bundle store exploded")

    monkeypatch.setattr("bernstein.core.evidence.bundle.read_evidence_bundle", _boom)
    body = Orchestrator._build_pr_body(_self_with(tmp_path), [_task("T-boom")], "feature")
    # Fail-open: body still produced, no marker, no partial Evidence section.
    assert EVIDENCE_BUNDLE_MARKER not in body
    assert "## Evidence" not in body
    assert "## Summary" in body
