"""Property tests for the per-artifact health verdict (issue #2559).

The verdict has to be recomputable offline by a third party, and the CLI and the
dashboard must never be able to disagree about it. Both claims reduce to one
property -- the verdict is a *pure function* of the collected state and the
evaluation instant -- which is exactly the shape a property test can hold to
account over generated spine fixtures rather than over a handful of hand-built
ones.

Properties:

* **Determinism.** Collecting and computing twice over the same ``.sdd`` tree
  gives byte-identical JSON, for any generated spine.
* **Surface agreement.** The bytes the CLI prints and the bytes the server route
  returns come from the same serialiser applied to the same state, so the two
  surfaces agree for every generated spine -- not just the ones someone thought
  to write a case for.
* **Purity.** ``compute_artifact_health`` never reads the clock or the disk: for
  a fixed state and instant its output is fixed, and the whole time dependence
  is carried by ``at``.
* **Canonical form.** The verdict document is its own canonical JSON, so a
  verifier that re-serialises it reproduces the bytes it was handed.
* **Tamper monotonicity.** A generated byte flip anywhere in a spine row that
  carries the artifact always turns the verdict red and always names the
  offending entry.
* **Attempts never inflate production.** For any mix of productions and attempt
  records, ``production_count`` counts productions only.
"""

from __future__ import annotations

import json
from pathlib import Path

from hypothesis import HealthCheck, given, settings
from hypothesis import strategies as st

from bernstein.core.lineage.artifact_attempt import ATTEMPT_OUTCOME_FAILED, reconcile_declared_outputs
from bernstein.core.lineage.artifact_health import (
    RED,
    artifact_health_json,
    collect_artifact_state,
    compute_artifact_health,
)
from bernstein.core.lineage.spine import LineageSpine

_KEY = b"p" * 32
_URI = "pkg://pypi/bernstein/3.9.0"

# Property tests build a real spine on disk, so they run without a function-scoped
# fixture and manage their own directory per example.
_settings = settings(
    max_examples=25,
    deadline=None,
    suppress_health_check=[HealthCheck.function_scoped_fixture, HealthCheck.too_slow],
)

#: One generated spine: a list of (timestamp, content, actor, model) productions
#: plus a count of attempt records, across a small number of runs.
_production = st.tuples(
    st.integers(min_value=0, max_value=10_000),
    st.binary(min_size=0, max_size=16),
    st.text(alphabet="abcdef-", min_size=0, max_size=8),
    st.text(alphabet="abcdef-", min_size=0, max_size=8),
)
_spine_plan = st.lists(_production, min_size=0, max_size=6)
_attempt_plan = st.lists(st.text(alphabet="0123456789", min_size=1, max_size=3), min_size=0, max_size=3, unique=True)


def _build(root: Path, plan: list[tuple[int, bytes, str, str]], attempts: list[str]) -> None:
    """Materialise a generated spine under ``root``."""
    lineage_root = root / ".sdd" / "lineage"
    for i, (ts, content, actor, model) in enumerate(plan):
        LineageSpine(lineage_root, run_id=f"run-{i % 2}", hmac_key=_KEY).record_entry(
            artifact_path=_URI,
            content=content,
            actor=actor,
            step_id=f"step-{i}",
            model=model,
            timestamp=ts,
        )
    for task_id in attempts:
        reconcile_declared_outputs(
            lineage_root,
            run_id="run-attempts",
            declared=[_URI],
            task_id=f"task-{task_id}",
            actor="agent",
            model="model",
            hmac_key=_KEY,
            timestamp=int(task_id),
            outcome=ATTEMPT_OUTCOME_FAILED,
        )


# ---------------------------------------------------------------------------
# Determinism and surface agreement (AC1)
# ---------------------------------------------------------------------------


@given(plan=_spine_plan, attempts=_attempt_plan, at=st.integers(min_value=0, max_value=20_000))
@_settings
def test_the_same_state_and_instant_give_byte_identical_json(
    tmp_path_factory: object, plan: list, attempts: list, at: int
) -> None:
    root = Path(tmp_path_factory.mktemp("health"))  # type: ignore[attr-defined]
    _build(root, plan, attempts)

    first = artifact_health_json(root, _URI, hmac_key=_KEY, at=at)
    second = artifact_health_json(root, _URI, hmac_key=_KEY, at=at)
    assert first == second


@given(plan=_spine_plan, attempts=_attempt_plan, at=st.integers(min_value=0, max_value=20_000))
@_settings
def test_the_cli_and_the_route_emit_the_same_bytes(
    tmp_path_factory: object, monkeypatch: object, plan: list, attempts: list, at: int
) -> None:
    """Driven end to end: the real command and the real route, over any spine.

    The existing parity tests check a handful of hand-built states. This one
    generates them, so a divergence that only shows up for, say, an artifact with
    tied timestamps or with attempts but no productions is caught here rather
    than in the field as a dashboard that disagrees with the CLI.
    """
    from click.testing import CliRunner
    from fastapi import FastAPI
    from fastapi.testclient import TestClient

    from bernstein.cli.commands.artifact_cmd import artifact_group
    from bernstein.core.routes.artifacts import router as artifacts_router

    root = Path(tmp_path_factory.mktemp("health"))  # type: ignore[attr-defined]
    _build(root, plan, attempts)

    monkeypatch.setattr("bernstein.cli.commands.artifact_cmd._spine_hmac_key", lambda: _KEY)  # type: ignore[attr-defined]
    monkeypatch.setattr("bernstein.core.routes.artifacts._hmac_key", lambda: _KEY)  # type: ignore[attr-defined]

    cli_out = (
        CliRunner()
        .invoke(artifact_group, ["health", _URI, "-w", str(root), "--at", str(at), "--output-json"])
        .output.strip()
    )

    app = FastAPI()
    app.include_router(artifacts_router)
    app.state.workdir = root
    route_out = TestClient(app).get("/artifacts/health", params={"uri": _URI, "at": at}).text

    assert cli_out == route_out
    assert json.loads(cli_out)["evaluated_at"] == at


@given(plan=_spine_plan, attempts=_attempt_plan, at=st.integers(min_value=0, max_value=20_000))
@_settings
def test_the_verdict_document_is_its_own_canonical_json(
    tmp_path_factory: object, plan: list, attempts: list, at: int
) -> None:
    root = Path(tmp_path_factory.mktemp("health"))  # type: ignore[attr-defined]
    _build(root, plan, attempts)

    payload = artifact_health_json(root, _URI, hmac_key=_KEY, at=at)
    assert payload == json.dumps(json.loads(payload), ensure_ascii=False, separators=(",", ":"), sort_keys=True)


@given(
    plan=_spine_plan,
    attempts=_attempt_plan,
    at=st.integers(min_value=0, max_value=20_000),
    cadence=st.one_of(st.none(), st.integers(min_value=1, max_value=5_000)),
)
@_settings
def test_compute_is_pure_over_state_and_instant(
    tmp_path_factory: object, plan: list, attempts: list, at: int, cadence: int | None
) -> None:
    """All the time dependence lives in ``at``; nothing else moves the answer."""
    root = Path(tmp_path_factory.mktemp("health"))  # type: ignore[attr-defined]
    _build(root, plan, attempts)

    state = collect_artifact_state(root, _URI, hmac_key=_KEY)
    a = compute_artifact_health(state, at=at, cadence_seconds=cadence)
    b = compute_artifact_health(state, at=at, cadence_seconds=cadence)
    assert a.to_dict() == b.to_dict()
    assert a.evaluated_at == at


# ---------------------------------------------------------------------------
# Tamper (AC2) and attempt accounting
# ---------------------------------------------------------------------------


@given(
    plan=st.lists(_production, min_size=1, max_size=5),
    field=st.sampled_from(["content_hash", "actor", "model", "timestamp", "hmac", "step_id"]),
    index=st.integers(min_value=0, max_value=4),
)
@_settings
def test_any_byte_flip_in_a_carrying_row_turns_the_verdict_red(
    tmp_path_factory: object, plan: list, field: str, index: int
) -> None:
    root = Path(tmp_path_factory.mktemp("health"))  # type: ignore[attr-defined]
    _build(root, plan, [])

    run_dir = root / ".sdd" / "lineage" / "run-0"
    rows = [json.loads(line) for line in run_dir.joinpath("spine.jsonl").read_bytes().strip().split(b"\n")]
    target = index % len(rows)
    value = rows[target][field]
    rows[target][field] = value + 1 if isinstance(value, int) else str(value) + "x"
    run_dir.joinpath("spine.jsonl").write_bytes(
        b"".join(
            json.dumps(r, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode() + b"\n" for r in rows
        )
    )

    verdict = json.loads(artifact_health_json(root, _URI, hmac_key=_KEY, at=50_000))
    assert verdict["verdict"] == RED
    integrity = next(leg for leg in verdict["legs"] if leg["name"] == "chain_integrity")
    assert integrity["detail"]


@given(plan=_spine_plan, attempts=_attempt_plan)
@_settings
def test_attempts_never_inflate_the_production_count(tmp_path_factory: object, plan: list, attempts: list) -> None:
    root = Path(tmp_path_factory.mktemp("health"))  # type: ignore[attr-defined]
    _build(root, plan, attempts)

    verdict = json.loads(artifact_health_json(root, _URI, hmac_key=_KEY, at=50_000))
    assert verdict["production_count"] == len(plan)
    assert verdict["attempt_count"] == len(attempts)
