"""Unit tests for skip-worktree CLAUDE.md hygiene on startup/crash (#4394).

When an agent run is killed mid-flight, the skip-worktree bit and task-specific
CLAUDE.md survive reset --hard and clean -fd. Pre-startup hygiene sweeps
git ls-files -v to clear skip-worktree flags and restore files to HEAD.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from bernstein.core.git.git_hygiene import run_hygiene
from bernstein.core.git.worktree_claude_md import restore_claude_md


def _init_git_repo(path: Path) -> None:
    """Initialize a git repository with initial commit containing CLAUDE.md."""
    subprocess.run(["git", "init", "-b", "main"], cwd=path, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=path, check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=path, check=True, capture_output=True)

    claude_md = path / "CLAUDE.md"
    claude_md.write_text("# Project Documentation\nReal developer guidelines.", encoding="utf-8")

    subprocess.run(["git", "add", "CLAUDE.md"], cwd=path, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "Initial commit"], cwd=path, check=True, capture_output=True)


def test_hygiene_clears_skip_worktree_claude_md(tmp_path: Path) -> None:
    """Hygiene clears skip-worktree bit and restores CLAUDE.md to HEAD."""
    _init_git_repo(tmp_path)

    claude_md = tmp_path / "CLAUDE.md"
    # Simulate a crashed agent run that overwrote CLAUDE.md and set skip-worktree
    claude_md.write_text(
        "# Bernstein Agent: backend (sess-abc123)\nThis file was auto-generated by Bernstein for this agent session.",
        encoding="utf-8",
    )
    subprocess.run(
        ["git", "update-index", "--skip-worktree", "CLAUDE.md"], cwd=tmp_path, check=True, capture_output=True
    )

    # Verify skip-worktree is active ('S CLAUDE.md')
    res = subprocess.run(
        ["git", "ls-files", "-v", "CLAUDE.md"], cwd=tmp_path, capture_output=True, text=True, check=True
    )
    assert res.stdout.strip().startswith("S")

    # Run git hygiene (as done on orchestrator startup)
    run_hygiene(tmp_path, full=True)

    # Verify bit is cleared and file is restored to HEAD
    res_after = subprocess.run(
        ["git", "ls-files", "-v", "CLAUDE.md"], cwd=tmp_path, capture_output=True, text=True, check=True
    )
    assert res_after.stdout.strip().startswith("H")

    content = claude_md.read_text(encoding="utf-8")
    assert content == "# Project Documentation\nReal developer guidelines."
    assert "Bernstein Agent" not in content


def test_restore_claude_md_helper(tmp_path: Path) -> None:
    """restore_claude_md clears skip-worktree bit and restores from HEAD."""
    _init_git_repo(tmp_path)

    claude_md = tmp_path / "CLAUDE.md"
    claude_md.write_text("# Bernstein Agent: qa (sess-xyz789)", encoding="utf-8")
    subprocess.run(
        ["git", "update-index", "--skip-worktree", "CLAUDE.md"], cwd=tmp_path, check=True, capture_output=True
    )

    success = restore_claude_md(tmp_path)
    assert success is True

    res = subprocess.run(
        ["git", "ls-files", "-v", "CLAUDE.md"], cwd=tmp_path, capture_output=True, text=True, check=True
    )
    assert res.stdout.strip().startswith("H")

    content = claude_md.read_text(encoding="utf-8")
    assert content == "# Project Documentation\nReal developer guidelines."


def test_hygiene_clears_generic_skip_worktree_file(tmp_path: Path) -> None:
    """Hygiene sweeps and restores any tracked file with skip-worktree set."""
    _init_git_repo(tmp_path)

    extra_file = tmp_path / "config.txt"
    extra_file.write_text("production_value", encoding="utf-8")
    subprocess.run(["git", "add", "config.txt"], cwd=tmp_path, check=True, capture_output=True)
    subprocess.run(["git", "commit", "-m", "Add config"], cwd=tmp_path, check=True, capture_output=True)

    # Overwrite and mark skip-worktree
    extra_file.write_text("tampered_value", encoding="utf-8")
    subprocess.run(
        ["git", "update-index", "--skip-worktree", "config.txt"], cwd=tmp_path, check=True, capture_output=True
    )

    run_hygiene(tmp_path)

    res = subprocess.run(
        ["git", "ls-files", "-v", "config.txt"], cwd=tmp_path, capture_output=True, text=True, check=True
    )
    assert res.stdout.strip().startswith("H")
    assert extra_file.read_text(encoding="utf-8") == "production_value"
