# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cluster_pb2 as bernstein_dot_v1_dot_cluster__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bernstein/v1/cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterServiceStub:
    """Cluster-internal node management and task stealing.
    Replaces HTTP heartbeats and node registration with low-latency gRPC.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/bernstein.v1.ClusterService/RegisterNode',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/bernstein.v1.ClusterService/Heartbeat',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.StreamHeartbeats = channel.stream_stream(
                '/bernstein.v1.ClusterService/StreamHeartbeats',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UnregisterNode = channel.unary_unary(
                '/bernstein.v1.ClusterService/UnregisterNode',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.UnregisterNodeRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.UnregisterNodeResponse.FromString,
                _registered_method=True)
        self.CordonNode = channel.unary_unary(
                '/bernstein.v1.ClusterService/CordonNode',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.CordonRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.FromString,
                _registered_method=True)
        self.UncordonNode = channel.unary_unary(
                '/bernstein.v1.ClusterService/UncordonNode',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.UncordonRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.FromString,
                _registered_method=True)
        self.DrainNode = channel.unary_unary(
                '/bernstein.v1.ClusterService/DrainNode',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.DrainRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.FromString,
                _registered_method=True)
        self.ListNodes = channel.unary_unary(
                '/bernstein.v1.ClusterService/ListNodes',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.ListNodesRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.ListNodesResponse.FromString,
                _registered_method=True)
        self.GetClusterStatus = channel.unary_unary(
                '/bernstein.v1.ClusterService/GetClusterStatus',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.ClusterStatusRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.ClusterStatusResponse.FromString,
                _registered_method=True)
        self.StealTasks = channel.unary_unary(
                '/bernstein.v1.ClusterService/StealTasks',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.StealTasksRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.StealTasksResponse.FromString,
                _registered_method=True)


class ClusterServiceServicer:
    """Cluster-internal node management and task stealing.
    Replaces HTTP heartbeats and node registration with low-latency gRPC.
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHeartbeats(self, request_iterator, context):
        """Bidirectional heartbeat stream — nodes keep a persistent connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnregisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CordonNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UncordonNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DrainNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClusterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StealTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.RegisterNodeRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatResponse.SerializeToString,
            ),
            'StreamHeartbeats': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamHeartbeats,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UnregisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UnregisterNode,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.UnregisterNodeRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.UnregisterNodeResponse.SerializeToString,
            ),
            'CordonNode': grpc.unary_unary_rpc_method_handler(
                    servicer.CordonNode,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.CordonRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.SerializeToString,
            ),
            'UncordonNode': grpc.unary_unary_rpc_method_handler(
                    servicer.UncordonNode,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.UncordonRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.SerializeToString,
            ),
            'DrainNode': grpc.unary_unary_rpc_method_handler(
                    servicer.DrainNode,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.DrainRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.SerializeToString,
            ),
            'ListNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNodes,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.ListNodesRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.ListNodesResponse.SerializeToString,
            ),
            'GetClusterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClusterStatus,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.ClusterStatusRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.ClusterStatusResponse.SerializeToString,
            ),
            'StealTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.StealTasks,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.StealTasksRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.StealTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bernstein.v1.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bernstein.v1.ClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterService:
    """Cluster-internal node management and task stealing.
    Replaces HTTP heartbeats and node registration with low-latency gRPC.
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/RegisterNode',
            bernstein_dot_v1_dot_cluster__pb2.RegisterNodeRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/Heartbeat',
            bernstein_dot_v1_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamHeartbeats(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bernstein.v1.ClusterService/StreamHeartbeats',
            bernstein_dot_v1_dot_cluster__pb2.HeartbeatRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnregisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/UnregisterNode',
            bernstein_dot_v1_dot_cluster__pb2.UnregisterNodeRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.UnregisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CordonNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/CordonNode',
            bernstein_dot_v1_dot_cluster__pb2.CordonRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UncordonNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/UncordonNode',
            bernstein_dot_v1_dot_cluster__pb2.UncordonRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DrainNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/DrainNode',
            bernstein_dot_v1_dot_cluster__pb2.DrainRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.NodeStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/ListNodes',
            bernstein_dot_v1_dot_cluster__pb2.ListNodesRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.ListNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClusterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/GetClusterStatus',
            bernstein_dot_v1_dot_cluster__pb2.ClusterStatusRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.ClusterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StealTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.ClusterService/StealTasks',
            bernstein_dot_v1_dot_cluster__pb2.StealTasksRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.StealTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BulletinServiceStub:
    """Cross-agent bulletin board messaging.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PostBulletin = channel.unary_unary(
                '/bernstein.v1.BulletinService/PostBulletin',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.PostBulletinRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.PostBulletinResponse.FromString,
                _registered_method=True)
        self.ReadBulletins = channel.unary_unary(
                '/bernstein.v1.BulletinService/ReadBulletins',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.ReadBulletinsRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.ReadBulletinsResponse.FromString,
                _registered_method=True)
        self.StreamBulletins = channel.unary_stream(
                '/bernstein.v1.BulletinService/StreamBulletins',
                request_serializer=bernstein_dot_v1_dot_cluster__pb2.StreamBulletinsRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_cluster__pb2.BulletinMessage.FromString,
                _registered_method=True)


class BulletinServiceServicer:
    """Cross-agent bulletin board messaging.
    """

    def PostBulletin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBulletins(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamBulletins(self, request, context):
        """Server-push stream of new bulletins.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BulletinServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PostBulletin': grpc.unary_unary_rpc_method_handler(
                    servicer.PostBulletin,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.PostBulletinRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.PostBulletinResponse.SerializeToString,
            ),
            'ReadBulletins': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBulletins,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.ReadBulletinsRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.ReadBulletinsResponse.SerializeToString,
            ),
            'StreamBulletins': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamBulletins,
                    request_deserializer=bernstein_dot_v1_dot_cluster__pb2.StreamBulletinsRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_cluster__pb2.BulletinMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bernstein.v1.BulletinService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bernstein.v1.BulletinService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BulletinService:
    """Cross-agent bulletin board messaging.
    """

    @staticmethod
    def PostBulletin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.BulletinService/PostBulletin',
            bernstein_dot_v1_dot_cluster__pb2.PostBulletinRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.PostBulletinResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBulletins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.BulletinService/ReadBulletins',
            bernstein_dot_v1_dot_cluster__pb2.ReadBulletinsRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.ReadBulletinsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamBulletins(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bernstein.v1.BulletinService/StreamBulletins',
            bernstein_dot_v1_dot_cluster__pb2.StreamBulletinsRequest.SerializeToString,
            bernstein_dot_v1_dot_cluster__pb2.BulletinMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
