# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import tasks_pb2 as bernstein_dot_v1_dot_tasks__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bernstein/v1/tasks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TaskServiceStub:
    """Internal task operations for cluster communication.
    REST remains the external API; gRPC is for node-to-node and orchestrator-to-agent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
                '/bernstein.v1.TaskService/CreateTask',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.CreateTaskRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ClaimTask = channel.unary_unary(
                '/bernstein.v1.TaskService/ClaimTask',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.ClaimTaskRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.CompleteTask = channel.unary_unary(
                '/bernstein.v1.TaskService/CompleteTask',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.CompleteTaskRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.FailTask = channel.unary_unary(
                '/bernstein.v1.TaskService/FailTask',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.FailTaskRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.ReportProgress = channel.unary_unary(
                '/bernstein.v1.TaskService/ReportProgress',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.ProgressRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/bernstein.v1.TaskService/ListTasks',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.ListTasksResponse.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/bernstein.v1.TaskService/GetTask',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.GetTaskRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.StreamTaskEvents = channel.unary_stream(
                '/bernstein.v1.TaskService/StreamTaskEvents',
                request_serializer=bernstein_dot_v1_dot_tasks__pb2.StreamTasksRequest.SerializeToString,
                response_deserializer=bernstein_dot_v1_dot_tasks__pb2.TaskEvent.FromString,
                _registered_method=True)


class TaskServiceServicer:
    """Internal task operations for cluster communication.
    REST remains the external API; gRPC is for node-to-node and orchestrator-to-agent.
    """

    def CreateTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClaimTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FailTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskEvents(self, request, context):
        """Server-push stream of task lifecycle events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTask,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.CreateTaskRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.SerializeToString,
            ),
            'ClaimTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimTask,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.ClaimTaskRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.SerializeToString,
            ),
            'CompleteTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteTask,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.CompleteTaskRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.SerializeToString,
            ),
            'FailTask': grpc.unary_unary_rpc_method_handler(
                    servicer.FailTask,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.FailTaskRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.SerializeToString,
            ),
            'ReportProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportProgress,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.ProgressRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.ProgressResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.ListTasksRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.ListTasksResponse.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.GetTaskRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.TaskResponse.SerializeToString,
            ),
            'StreamTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskEvents,
                    request_deserializer=bernstein_dot_v1_dot_tasks__pb2.StreamTasksRequest.FromString,
                    response_serializer=bernstein_dot_v1_dot_tasks__pb2.TaskEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bernstein.v1.TaskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bernstein.v1.TaskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TaskService:
    """Internal task operations for cluster communication.
    REST remains the external API; gRPC is for node-to-node and orchestrator-to-agent.
    """

    @staticmethod
    def CreateTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/CreateTask',
            bernstein_dot_v1_dot_tasks__pb2.CreateTaskRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClaimTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/ClaimTask',
            bernstein_dot_v1_dot_tasks__pb2.ClaimTaskRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/CompleteTask',
            bernstein_dot_v1_dot_tasks__pb2.CompleteTaskRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FailTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/FailTask',
            bernstein_dot_v1_dot_tasks__pb2.FailTaskRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/ReportProgress',
            bernstein_dot_v1_dot_tasks__pb2.ProgressRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/ListTasks',
            bernstein_dot_v1_dot_tasks__pb2.ListTasksRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bernstein.v1.TaskService/GetTask',
            bernstein_dot_v1_dot_tasks__pb2.GetTaskRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bernstein.v1.TaskService/StreamTaskEvents',
            bernstein_dot_v1_dot_tasks__pb2.StreamTasksRequest.SerializeToString,
            bernstein_dot_v1_dot_tasks__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
