"""Per-agent session token consumption breakdown.

Combines pre-session prompt token analysis with actual API usage to show
where context budget was spent:

- **system_prompt** — role template / persona instructions (Bernstein overhead)
- **context** — project state, lessons, predecessors, rich context
- **user_prompt** — task description, instructions, protocol boilerplate
- **tool_results** — tool call outputs accumulated during execution
  (actual_input - estimated_prompt, i.e. dynamic turn content)
- **output** — tokens generated by the assistant

Usage::

    from bernstein.core.agent_session_token_breakdown import load_session_breakdown

    breakdown = load_session_breakdown(sdd_dir, session_id="abc123")
    if breakdown:
        print(breakdown.summary())
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------


@dataclass
class AgentSessionTokenBreakdown:
    """Token consumption breakdown for a single agent session.

    Attributes:
        session_id: Agent session identifier.
        system_prompt_tokens: Estimated tokens for role/persona instructions.
        context_tokens: Estimated tokens for context sections (files, lessons).
        user_prompt_tokens: Estimated tokens for task description and boilerplate.
        tool_result_tokens: Dynamic tokens added during execution (tool outputs).
            Computed as max(0, actual_input - estimated_prompt_total).
        output_tokens: Tokens generated by the assistant.
        actual_input_tokens: Actual input tokens billed (from cost tracker).
        cache_read_tokens: Tokens served from prompt cache.
        cache_write_tokens: Tokens written to prompt cache.
        estimated_prompt_total: Sum of system_prompt + context + user_prompt estimates.
        model: Model used for this session.
        cost_usd: Total cost in USD for this session.
        task_id: Task the agent was working on.
        optimization_notes: Actionable notes about token usage (e.g. over-budget sections).
    """

    session_id: str
    system_prompt_tokens: int = 0
    context_tokens: int = 0
    user_prompt_tokens: int = 0
    tool_result_tokens: int = 0
    output_tokens: int = 0
    actual_input_tokens: int = 0
    cache_read_tokens: int = 0
    cache_write_tokens: int = 0
    estimated_prompt_total: int = 0
    model: str = ""
    cost_usd: float = 0.0
    task_id: str = ""
    optimization_notes: list[str] = field(default_factory=list)

    @property
    def total_tokens(self) -> int:
        """Total tokens consumed (actual input + output)."""
        return self.actual_input_tokens + self.output_tokens

    def percentages(self) -> dict[str, float]:
        """Return token category percentages relative to total_tokens.

        Returns:
            Dict mapping category name to percentage of total (0.0-100.0).
        """
        total = self.total_tokens
        if total == 0:
            return {
                "system_prompt": 0.0,
                "context": 0.0,
                "user_prompt": 0.0,
                "tool_results": 0.0,
                "output": 0.0,
            }
        return {
            "system_prompt": round(self.system_prompt_tokens / total * 100, 1),
            "context": round(self.context_tokens / total * 100, 1),
            "user_prompt": round(self.user_prompt_tokens / total * 100, 1),
            "tool_results": round(self.tool_result_tokens / total * 100, 1),
            "output": round(self.output_tokens / total * 100, 1),
        }

    def summary(self) -> str:
        """Return a human-readable summary of the token breakdown.

        Returns:
            Multi-line string suitable for logging or CLI output.
        """
        pct = self.percentages()
        lines = [
            f"## Token breakdown (session: {self.session_id or 'N/A'})",
            f"Model: {self.model or 'unknown'}  |  Cost: ${self.cost_usd:.4f}",
            f"Total: {self.total_tokens:,} tokens  "
            f"(input: {self.actual_input_tokens:,}  output: {self.output_tokens:,})",
            "",
            f"{'Category':<35} {'Tokens':>8} {'Pct':>6}",
            "-" * 53,
            f"{'System prompt (Bernstein overhead)':<35} {self.system_prompt_tokens:>8,} {pct['system_prompt']:>5.1f}%",
            f"{'Context (files, lessons, state)':<35} {self.context_tokens:>8,} {pct['context']:>5.1f}%",
            f"{'User prompt (task + boilerplate)':<35} {self.user_prompt_tokens:>8,} {pct['user_prompt']:>5.1f}%",
            f"{'Tool results (dynamic, exec-time)':<35} {self.tool_result_tokens:>8,} {pct['tool_results']:>5.1f}%",
            f"{'Assistant output':<35} {self.output_tokens:>8,} {pct['output']:>5.1f}%",
        ]
        if self.cache_read_tokens or self.cache_write_tokens:
            lines.append(f"\nCache: read {self.cache_read_tokens:,} tokens, write {self.cache_write_tokens:,} tokens")
        if self.optimization_notes:
            lines += ["", "Optimization notes:"]
            for note in self.optimization_notes:
                lines.append(f"  • {note}")
        return "\n".join(lines)

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dict."""
        return {
            "session_id": self.session_id,
            "model": self.model,
            "task_id": self.task_id,
            "cost_usd": round(self.cost_usd, 6),
            "actual_input_tokens": self.actual_input_tokens,
            "output_tokens": self.output_tokens,
            "total_tokens": self.total_tokens,
            "cache_read_tokens": self.cache_read_tokens,
            "cache_write_tokens": self.cache_write_tokens,
            "breakdown": {
                "system_prompt_tokens": self.system_prompt_tokens,
                "context_tokens": self.context_tokens,
                "user_prompt_tokens": self.user_prompt_tokens,
                "tool_result_tokens": self.tool_result_tokens,
                "output_tokens": self.output_tokens,
            },
            "percentages": self.percentages(),
            "estimated_prompt_total": self.estimated_prompt_total,
            "optimization_notes": self.optimization_notes,
        }


# ---------------------------------------------------------------------------
# Loading and combining data
# ---------------------------------------------------------------------------


def _load_prompt_token_report(sdd_dir: Path, session_id: str) -> dict[str, Any] | None:
    """Load a saved prompt token usage report for a session.

    Args:
        sdd_dir: Project root ``.sdd/`` directory.
        session_id: Agent session identifier.

    Returns:
        Parsed JSON dict, or None if no report exists.
    """
    metrics_dir = sdd_dir / "metrics"
    report_path = metrics_dir / f"prompt_token_usage_{session_id}.json"
    if not report_path.exists():
        return None
    try:
        return json.loads(report_path.read_text(encoding="utf-8"))  # type: ignore[no-any-return]
    except (OSError, json.JSONDecodeError) as exc:
        # Strip CR/LF from the user-controlled session_id before logging
        # so an attacker cannot inject fake log lines (CodeQL
        # py/log-injection #98).
        safe_sid = session_id.replace("\r", "").replace("\n", "")
        logger.debug("Cannot load prompt token report for %s: %s", safe_sid, exc)
        return None


def load_session_breakdown(
    sdd_dir: Path,
    session_id: str,
    actual_input_tokens: int = 0,
    actual_output_tokens: int = 0,
    cache_read_tokens: int = 0,
    cache_write_tokens: int = 0,
    model: str = "",
    cost_usd: float = 0.0,
    task_id: str = "",
) -> AgentSessionTokenBreakdown:
    """Build a token breakdown for a single agent session.

    Loads the pre-session prompt token analysis (if available) to determine
    the system_prompt/context/user_prompt split, then derives tool_result_tokens
    as the remainder of actual_input beyond what was estimated.

    Args:
        sdd_dir: Path to the ``.sdd/`` directory.
        session_id: Agent session identifier.
        actual_input_tokens: Actual billed input tokens (from cost tracker).
        actual_output_tokens: Actual billed output tokens (from cost tracker).
        cache_read_tokens: Cache-read tokens (from cost tracker).
        cache_write_tokens: Cache-write tokens (from cost tracker).
        model: Model used for the session.
        cost_usd: Cost in USD for the session.
        task_id: Task the agent was working on.

    Returns:
        :class:`AgentSessionTokenBreakdown` with the full breakdown.
    """
    system_tokens = 0
    context_tokens = 0
    user_tokens = 0
    notes: list[str] = []

    prompt_report = _load_prompt_token_report(sdd_dir, session_id)
    if prompt_report:
        system_tokens = int(prompt_report.get("system_prompt_tokens", 0))
        context_tokens = int(prompt_report.get("context_tokens", 0))
        user_tokens = int(prompt_report.get("user_prompt_tokens", 0))
        # Carry over reduction suggestions as optimization notes
        for s in prompt_report.get("suggestions", []):
            notes.append(str(s))

    estimated_total = system_tokens + context_tokens + user_tokens

    # Tool results are the delta between actual input and the pre-session estimate.
    # If actual_input is less than estimated (e.g. cache read dominated), clamp to 0.
    tool_result_tokens = max(0, actual_input_tokens - estimated_total)

    # If we have actual data but no prompt analysis, note the gap
    if not prompt_report and actual_input_tokens > 0:
        notes.append(
            "No pre-session prompt analysis found — run breakdown is input/output only. "
            "Enable prompt token analysis in spawn_prompt to get full breakdown."
        )

    # Flag if context is unusually large relative to actual input
    if estimated_total > 0 and actual_input_tokens > 0:
        context_pct = context_tokens / actual_input_tokens * 100
        if context_pct > 55:
            notes.append(
                f"Context sections are {context_pct:.0f}% of input tokens. Consider trimming unused context files."
            )

    return AgentSessionTokenBreakdown(
        session_id=session_id,
        system_prompt_tokens=system_tokens,
        context_tokens=context_tokens,
        user_prompt_tokens=user_tokens,
        tool_result_tokens=tool_result_tokens,
        output_tokens=actual_output_tokens,
        actual_input_tokens=actual_input_tokens,
        cache_read_tokens=cache_read_tokens,
        cache_write_tokens=cache_write_tokens,
        estimated_prompt_total=estimated_total,
        model=model,
        cost_usd=cost_usd,
        task_id=task_id,
        optimization_notes=notes,
    )


def load_all_session_breakdowns(sdd_dir: Path) -> list[AgentSessionTokenBreakdown]:
    """Load breakdowns for all sessions found in cost tracker data.

    Scans ``.sdd/runtime/costs/`` for cost files, enumerates each usage
    record, and builds a breakdown by combining it with any saved prompt
    token analysis.

    Args:
        sdd_dir: Path to the ``.sdd/`` directory.

    Returns:
        List of breakdowns, one per agent_id x task_id combination, newest first.
    """
    # Avoid circular import: cost_tracker imports from models
    try:
        from bernstein.core.cost_tracker import CostTracker
    except ImportError:
        logger.warning("CostTracker not available; returning empty breakdown list")
        return []

    costs_dir = sdd_dir / "runtime" / "costs"
    if not costs_dir.exists():
        return []

    cost_files = sorted(costs_dir.glob("*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    results: list[AgentSessionTokenBreakdown] = []
    seen: set[str] = set()

    for cost_file in cost_files:
        tracker = CostTracker.load(sdd_dir, cost_file.stem)
        if tracker is None:
            continue
        for usage in tracker.usages:
            key = usage.agent_id
            if key in seen:
                continue
            seen.add(key)
            breakdown = load_session_breakdown(
                sdd_dir=sdd_dir,
                session_id=usage.agent_id,
                actual_input_tokens=usage.input_tokens,
                actual_output_tokens=usage.output_tokens,
                cache_read_tokens=usage.cache_read_tokens,
                cache_write_tokens=usage.cache_write_tokens,
                model=usage.model,
                cost_usd=usage.cost_usd,
                task_id=usage.task_id,
            )
            results.append(breakdown)

    return results
