"""Install-rev identity module - passive, operator-decodable install fingerprint.

This sub-package emits a short, benign-looking 16-character base32 token
(``bernstein-rev: <token>``) that the operator can search for in public
GitHub artefacts (``gh search code 'bernstein-rev:'``) to discover real
Bernstein installs.

Design promise: **no telemetry, no network egress**.  The host process
never sends the token anywhere - it lands in user-authored config,
trace, and prompt files that the user *voluntarily* pushes to GitHub.
The operator's discovery is passive observation of public artefacts.

Public surface:

* :func:`get_install_rev` - cached 16-char token for the current install.
* :func:`render_yaml_comment` / :func:`render_trace_header` /
  :func:`render_md_footer` - pre-formatted snippets for the three
  embedding slots (YAML config, trace JSONL header, role-prompt md
  footer).
* :class:`bernstein.core.identity.principal.AgentPrincipal` - the one
  identity an authority decision is checked against, and the two adapters
  that project the JWT-store record and the signed capability card onto it.
* :func:`verify_token` - operator-side: given a token + the operator's
  256-bit seed (env: ``BERNSTEIN_IDENTITY_SEED``), confirm whether the
  token was generated by a real Bernstein install.

Kill switches:

* ``BERNSTEIN_DISABLE_IDENTITY=1`` - replaces the token with the
  fixed sentinel ``0000000000000000``. User-facing opt-out.
* :data:`IDENTITY_EMISSION_ENABLED` - module-level flag, default
  ``False`` until the operator flips it after generating their seed.
  Caller code that wires up emitters MUST gate on this flag.

See ``.sdd/audit/2026-05-09-fingerprint-design.md`` (operator-only,
gitignored) for the full design rationale and threat model.
"""

from __future__ import annotations

from bernstein.core.identity.install_rev import (
    DISABLED_SENTINEL,
    IDENTITY_EMISSION_ENABLED,
    InvalidTokenError,
    SeedNotConfiguredError,
    get_install_rev,
    render_md_footer,
    render_trace_header,
    render_yaml_comment,
    verify_token,
)
from bernstein.core.identity.principal import (
    AgentPrincipal,
    CredentialFormat,
    CredentialRef,
    PrincipalStatus,
    principal_from_agent_identity,
    principal_from_identity_card,
)

__all__ = [
    "DISABLED_SENTINEL",
    "IDENTITY_EMISSION_ENABLED",
    "AgentPrincipal",
    "CredentialFormat",
    "CredentialRef",
    "InvalidTokenError",
    "PrincipalStatus",
    "SeedNotConfiguredError",
    "get_install_rev",
    "principal_from_agent_identity",
    "principal_from_identity_card",
    "render_md_footer",
    "render_trace_header",
    "render_yaml_comment",
    "verify_token",
]
