#!/usr/bin/env python
"""Apply dependency fixes, test them, and create a PR.

This script:
  1. Reads the dependency report
  2. Upgrades packages in pyproject.toml
  3. Updates the lockfile (uv.lock)
  4. Runs the full test suite
  5. Creates a PR if all tests pass
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import click
from rich.console import Console

console = Console()


def run_command(cmd: list[str], check: bool = True) -> tuple[int, str, str]:
    """Run a command and return exit code, stdout, stderr."""
    result = subprocess.run(cmd, capture_output=True, text=True)
    if check and result.returncode != 0:
        console.print(f"[red]Command failed:[/red] {' '.join(cmd)}")
        console.print(f"[red]stdout:[/red] {result.stdout}")
        console.print(f"[red]stderr:[/red] {result.stderr}")
        sys.exit(1)
    return result.returncode, result.stdout, result.stderr


def load_report(path: str) -> dict:
    """Load dependency report."""
    with open(path) as f:
        return json.load(f)


def apply_upgrades(resolutions: list[dict]) -> None:
    """Apply dependency upgrades to pyproject.toml."""
    console.print("[bold cyan]Applying upgrades to pyproject.toml[/bold cyan]")

    pyproject_path = Path("pyproject.toml")
    content = pyproject_path.read_text()

    for resolution in resolutions:
        package = resolution["package"]
        suggested = resolution["suggested"]

        # Skip pip as it's not in project dependencies
        if package.lower() == "pip":
            console.print(f"  ⊘ Skipping {package} (not a project dependency)")
            continue

        # Update the dependency requirement
        old_pattern = f"{package}>="

        if old_pattern in content:
            lines = content.split("\n")
            updated = False
            for i, line in enumerate(lines):
                if package in line and ">=" in line:
                    # Extract current requirement
                    before = line.split('"')[0] + '"'
                    after = '"' + line.split('"')[-1]
                    lines[i] = f"{before}{package}>={suggested}{after}"
                    updated = True
                    console.print(f"  ✓ Updated {package} to >={suggested}")

            if updated:
                content = "\n".join(lines)

    pyproject_path.write_text(content)


def update_lockfile() -> None:
    """Update uv.lock by running uv sync."""
    console.print("[bold cyan]Updating lockfile with uv sync[/bold cyan]")
    run_command(["uv", "sync"])
    console.print("  ✓ Lockfile updated")


def run_tests() -> bool:
    """Run the full test suite."""
    console.print("[bold cyan]Running test suite[/bold cyan]")
    exit_code, stdout, _stderr = run_command(["uv", "run", "python", "scripts/run_tests.py", "-x"], check=False)

    if exit_code == 0:
        console.print("  ✓ All tests passed")
        return True
    else:
        console.print("[red]  ✗ Tests failed[/red]")
        console.print(f"[dim]{stdout}[/dim]")
        return False


def create_pr(report: dict, tested: bool) -> None:
    """Create a GitHub PR with the changes."""
    if not tested:
        console.print("[red]Skipping PR creation — tests failed[/red]")
        return

    console.print("[bold cyan]Creating pull request[/bold cyan]")

    cves = report["cves"]
    resolutions = [r for r in report["suggested_resolutions"] if r["package"].lower() != "pip"]

    # Prepare PR details
    cve_list = "\n".join([f"- {cve['cve_id']}: {cve['package']} {cve['current_version']}" for cve in cves])
    resolution_list = "\n".join([f"- {r['package']}: {r['current']} → {r['suggested']}" for r in resolutions])

    body = f"""## Dependency Security Updates

This PR resolves detected CVEs and dependency conflicts.

### CVEs Fixed
{cve_list}

### Upgrades Applied
{resolution_list}

### Verification
- [x] Lockfile updated
- [x] All tests passing
- [x] No breaking changes detected

---
Generated by Bernstein Dependency Conflict Resolver.
"""

    # Create the PR using git and gh
    branch_name = "deps/security-updates"
    run_command(["git", "checkout", "-b", branch_name], check=False)
    run_command(["git", "add", "-A"])
    run_command(["git", "commit", "-m", "fix: apply security dependency updates"], check=False)
    run_command(["git", "push", "-u", "origin", branch_name], check=False)

    # Create PR using gh
    run_command(
        ["gh", "pr", "create", "--title", "[Security] Apply dependency CVE fixes", "--body", body, "--base", "main"],
        check=False,
    )

    console.print("  ✓ PR created")


@click.command()
@click.option("--report", default=".sdd/dependency-report.json", help="Path to dependency report")
@click.option("--create-pr", is_flag=True, default=False, help="Create a PR if tests pass")
def main(report: str, create_pr: bool) -> None:
    """Apply dependency fixes and test them."""
    console.print("[bold]Bernstein Dependency Fix Applier[/bold]\n")

    # Load report
    dep_report = load_report(report)

    resolutions = dep_report["suggested_resolutions"]
    if not resolutions:
        console.print("[yellow]No resolutions to apply[/yellow]")
        return

    console.print(f"Found {len(resolutions)} resolutions to apply\n")

    # Apply upgrades
    apply_upgrades(resolutions)

    # Update lockfile
    update_lockfile()

    # Run tests
    tests_passed = run_tests()

    if tests_passed and create_pr:
        create_pr(dep_report, tests_passed)

    if tests_passed:
        console.print("\n[bold green]✓ Dependency updates complete and tested[/bold green]")
        sys.exit(0)
    else:
        console.print("\n[bold red]✗ Tests failed — not creating PR[/bold red]")
        sys.exit(1)


if __name__ == "__main__":
    main()
