#!/usr/bin/env python3
"""gen_brand_svgs.py - write the Bernstein identity SVGs from their geometry.

The mark is a regular pointy-top hexagon (circumradius 240 on an 800 x 800
canvas) with 50 px rounded corners and the terminal prompt ``>_`` cut through
it. Everything here is derived from those numbers, so a change to the geometry
is a change to this file, not to twelve hand-edited SVGs. The wordmark is the
word "bernstein" set in Fraunces (weight 500) and converted to outlines, so it
renders identically wherever the SVG is shown; GitHub's README renderer and
most social crawlers do not load web fonts.

Run from the repository root:

    uv run --with 'fonttools[woff]' python scripts/gen_brand_svgs.py \\
        --fraunces /path/to/fraunces-latin.woff2 --geist /path/to/Geist-Regular.ttf

Outputs (all overwritten):

    docs/assets/brand/bernstein-mark.svg                mark, transparent, padded 800 x 800
    docs/assets/brand/bernstein-mark-mono.svg           one-colour mark (currentColor), tight
    docs/assets/brand/bernstein-logo-square-dark.svg    mark on the dark token background
    docs/assets/brand/bernstein-logo-square-light.svg   mark on the paper token background
    docs/assets/brand/bernstein-social-1280x640.svg     GitHub social preview
    docs/assets/brand/bernstein-og-1200x630.svg         docs site og:image
    docs/assets/logo-dark.svg, docs/assets/logo-light.svg   wordmark (hotlink-stable paths)
    packages/vscode/media/bernstein-icon.svg            activity-bar icon (mono)

PNG exports come from scripts/render_brand_assets.sh (rsvg-convert).
Colours are the design tokens in docs/design/tokens.json plus the mark's own
amber, which docs/design/brand.md defines.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BRAND = ROOT / "docs" / "assets" / "brand"

AMBER = "#F5A524"
AMBER_FACET = "#FFC96A"
INK_DARK_BG = "#13130F"  # tokens: bg dark
PAPER_BG = "#F8F1E7"  # tokens: bg light
TEXT_ON_DARK = "#F2EFE6"  # tokens: text dark
TEXT_ON_PAPER = "#181614"  # tokens: text light
MUTED_ON_DARK = "#A39D8C"
MUTED_ON_PAPER = "#575552"

TAGLINE = "The open-source governance layer for AI agents."
SITE = "bernstein.run"


# ── mark geometry ─────────────────────────────────────────────────────────


def rounded_hexagon_path(cx: float, cy: float, r: float, corner: float) -> str:
    """Regular pointy-top hexagon, corners rounded with arcs of radius `corner`.

    The visible shape is the r-hexagon grown by `corner` on every side, which is
    what a round-joined stroke of width 2*corner would draw. Straight edges are
    offset outward, each corner is a 60-degree arc centred on the original vertex.
    """
    cmds = []
    for i in range(6):
        theta = math.radians(-90 + 60 * i)
        vx, vy = cx + r * math.cos(theta), cy + r * math.sin(theta)
        a0, a1 = theta - math.radians(30), theta + math.radians(30)
        sx, sy = vx + corner * math.cos(a0), vy + corner * math.sin(a0)
        ex, ey = vx + corner * math.cos(a1), vy + corner * math.sin(a1)
        cmds.append(f"{'M' if i == 0 else 'L'} {sx:.2f} {sy:.2f}")
        cmds.append(f"A {corner} {corner} 0 0 1 {ex:.2f} {ey:.2f}")
    cmds.append("Z")
    return " ".join(cmds)


# The prompt glyph on the 800 canvas: a chevron with vertical end cuts and an
# underscore, together centred at x=400.
CHEVRON = "M 216 290 L 433 400 L 216 510 L 216 450 L 315 400 L 216 350 Z"
UNDERSCORE = "M 453 452 H 583 V 510 H 453 Z"
HEX = rounded_hexagon_path(400, 400, 240, 50)

# One facet along the upper-left edge: a band 45 px wide, clipped by the mask.
FACET = "452,70 88,280 110.5,319 474.5,109"

TIGHT_VIEWBOX = "80 80 640 640"  # the mark with no padding, still square


def mark_group(with_facet: bool = True) -> str:
    """The coloured mark as a masked group (true cut-out, transparent behind)."""
    facet = f'\n    <polygon points="{FACET}" fill="{AMBER_FACET}"/>' if with_facet else ""
    return f"""  <defs>
    <mask id="hex" maskUnits="userSpaceOnUse" x="0" y="0" width="800" height="800">
      <path d="{HEX}" fill="#fff"/>
      <path d="{CHEVRON} {UNDERSCORE}" fill="#000"/>
    </mask>
  </defs>
  <g mask="url(#hex)">
    <rect width="800" height="800" fill="{AMBER}"/>{facet}
  </g>"""


def mark_path_evenodd(fill: str) -> str:
    """The mark as one path, no mask: for renderers that only do paths."""
    return f'<path fill-rule="evenodd" fill="{fill}" d="{HEX} {CHEVRON} {UNDERSCORE}"/>'


def svg(width: int, height: int, viewbox: str, body: str, comment: str) -> str:
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="{viewbox}">\n'
        f"  <!-- {comment} Generated by scripts/gen_brand_svgs.py; edit that, not this. -->\n"
        f"{body}\n</svg>\n"
    )


# ── text to outlines ──────────────────────────────────────────────────────


def load_font(path: Path, wght: float | None):
    from fontTools.ttLib import TTFont

    font = TTFont(str(path))
    if wght is not None and "fvar" in font:
        from fontTools.varLib.instancer import instantiateVariableFont

        font = instantiateVariableFont(font, {"wght": wght})
    return font


def text_path(font, text: str, size: float, x: float, baseline: float) -> tuple[str, float]:
    """Return (path d, advance width in px) for `text` set at `size` px."""
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen

    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    scale = size / font["head"].unitsPerEm
    kern = _kern_table(font)
    parts: list[str] = []
    pen_x = 0.0
    prev = None
    for ch in text:
        name = cmap[ord(ch)]
        if prev is not None:
            pen_x += kern.get((prev, name), 0)
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(TransformPen(pen, (scale, 0, 0, -scale, x + pen_x * scale, baseline)))
        d = pen.getCommands()
        if d:
            parts.append(d)
        pen_x += glyphs[name].width
        prev = name
    return " ".join(parts), pen_x * scale


def _kern_table(font) -> dict[tuple[str, str], float]:
    """Pair kerning from GPOS PairPos format 1 (the common case); empty otherwise."""
    table: dict[tuple[str, str], float] = {}
    if "GPOS" not in font:
        return table
    for lookup in font["GPOS"].table.LookupList.Lookup:
        for sub in lookup.SubTable:
            if getattr(sub, "LookupType", lookup.LookupType) == 9:
                sub = sub.ExtSubTable
            if sub.LookupType != 2 or sub.Format != 1:
                continue
            firsts = sub.Coverage.glyphs
            for first, pairset in zip(firsts, sub.PairSet, strict=False):
                for rec in pairset.PairValueRecord:
                    v = rec.Value1
                    if v is not None and getattr(v, "XAdvance", 0):
                        table[(first, rec.SecondGlyph)] = v.XAdvance
    return table


# ── outputs ──────────────────────────────────────────────────────────────


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(ROOT)}")


def wordmark(fraunces, dark: bool) -> str:
    text_fill = TEXT_ON_DARK if dark else TEXT_ON_PAPER
    d, _adv = text_path(fraunces, "bernstein", size=46, x=76, baseline=55)
    # the mark, scaled from its tight 640 box to 60 px tall, left of the word
    body = f"""  <g transform="translate(8 10) scale(0.09375) translate(-80 -80)">
{mark_group()}
  </g>
  <path fill="{text_fill}" d="{d}"/>"""
    theme = "dark" if dark else "light"
    return svg(400, 80, "0 0 400 80", body, f"Bernstein wordmark, {theme} surfaces.")


def banner(fraunces, geist, width: int, height: int) -> str:
    """Mark + wordmark + tagline on paper, for link previews."""
    pad = 96
    mark_h = 260
    mark_scale = mark_h / 640
    mark_y = (height - mark_h) / 2 - 20
    x_text = pad + mark_h * (560 / 640) + 40
    name_size = 128
    name_base = mark_y + mark_h * 0.50
    name_d, _ = text_path(fraunces, "bernstein", size=name_size, x=x_text, baseline=name_base)
    tag_d, _ = text_path(geist, TAGLINE, size=36, x=x_text, baseline=name_base + 70)
    foot_d, _ = text_path(geist, f"{SITE}  ·  Apache-2.0", size=24, x=pad, baseline=height - pad + 8)
    body = f"""  <rect width="{width}" height="{height}" fill="{PAPER_BG}"/>
  <g transform="translate({pad} {mark_y:.1f}) scale({mark_scale:.5f}) translate(-80 -80)">
{mark_group()}
  </g>
  <path fill="{TEXT_ON_PAPER}" d="{name_d}"/>
  <path fill="{TEXT_ON_PAPER}" d="{tag_d}"/>
  <path fill="{MUTED_ON_PAPER}" d="{foot_d}"/>"""
    return svg(width, height, f"0 0 {width} {height}", body, f"Bernstein link preview {width}x{height}.")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--fraunces", type=Path, required=True, help="Fraunces variable font (woff2/ttf)")
    ap.add_argument("--geist", type=Path, required=True, help="Geist Regular (ttf)")
    args = ap.parse_args()
    fraunces = load_font(args.fraunces, wght=500)
    geist = load_font(args.geist, wght=None)

    write(BRAND / "bernstein-mark.svg", svg(800, 800, "0 0 800 800", mark_group(), "Bernstein mark, transparent."))
    write(
        BRAND / "bernstein-mark-mono.svg",
        svg(640, 640, TIGHT_VIEWBOX, "  " + mark_path_evenodd("currentColor"), "Bernstein mark, one colour."),
    )
    for theme, bg in (("dark", INK_DARK_BG), ("light", PAPER_BG)):
        body = f'  <rect width="800" height="800" fill="{bg}"/>\n{mark_group()}'
        write(
            BRAND / f"bernstein-logo-square-{theme}.svg",
            svg(800, 800, "0 0 800 800", body, f"Bernstein logo on the {theme} background."),
        )
    write(ROOT / "docs" / "assets" / "logo-dark.svg", wordmark(fraunces, dark=True))
    write(ROOT / "docs" / "assets" / "logo-light.svg", wordmark(fraunces, dark=False))
    write(BRAND / "bernstein-social-1280x640.svg", banner(fraunces, geist, 1280, 640))
    write(BRAND / "bernstein-og-1200x630.svg", banner(fraunces, geist, 1200, 630))
    write(
        ROOT / "packages" / "vscode" / "media" / "bernstein-icon.svg",
        svg(24, 24, TIGHT_VIEWBOX, "  " + mark_path_evenodd("currentColor"), "Bernstein activity-bar icon."),
    )


if __name__ == "__main__":
    main()
