"""Generate 200 YAML ticket files for Bernstein backlog (batch 030426)."""

from __future__ import annotations

from pathlib import Path

OUTPUT_DIR = Path(__file__).resolve().parent.parent / ".sdd" / "backlog" / "open"

COMPLEXITY_LABEL = {0: "minimal", 1: "low", 2: "medium", 3: "high", 4: "epic"}
COMPLEXITY_MINUTES = {0: 15, 1: 60, 2: 180, 3: 360, 4: 480}
SCOPE_MAP = {0: "small", 1: "small", 2: "medium", 3: "large", 4: "large"}

PILLAR_ROLE = {
    "memory-knowledge": "backend",
    "tool-ecosystem": "backend",
    "agent-self-org": "architect",
    "developer-experience": "frontend",
    "enterprise-runtime": "devops",
    "plugin-skill-ecosystem": "backend",
    "performance-native": "backend",
    "future-bets": "architect",
}

PILLAR_TAG = {
    "memory-knowledge": "memory-knowledge",
    "tool-ecosystem": "tool-ecosystem",
    "agent-self-org": "agent-self-org",
    "developer-experience": "developer-experience",
    "enterprise-runtime": "enterprise-runtime",
    "plugin-skill-ecosystem": "plugin-skill-ecosystem",
    "performance-native": "performance-native",
    "future-bets": "future-bets",
}


def _ticket(
    tid: int,
    priority: int,
    complexity: int,
    kebab: str,
    title: str,
    summary: str,
    criteria: list[str],
    source_ref: str,
    pillar: str,
) -> dict:
    return {
        "tid": tid,
        "priority": priority,
        "complexity": complexity,
        "kebab": kebab,
        "title": title,
        "summary": summary,
        "criteria": criteria,
        "source_ref": source_ref,
        "pillar": pillar,
    }


TICKETS: list[dict] = [
    # ── Pillar 1: Memory & Knowledge (25 tickets) ──
    _ticket(651, 0, 2, "typed-memory-taxonomy", "Implement typed memory taxonomy for lessons",
            "Add user/feedback/project/reference memory types to lessons.py. Inspired by memdir/memoryTypes.ts typed categories.",
            ["Extend LessonRecord with memory_type enum field", "Add per-type decay rates (user slowest, feedback fastest)", "Update retrieval to filter by memory type"],
            "memdir/memoryTypes.ts", "memory-knowledge"),
    _ticket(652, 0, 1, "memory-staleness-caveat", "Add staleness metadata to surfaced lessons",
            "When lessons.py surfaces lessons to agents, include freshness caveat text for lessons older than 1 day.",
            ["Add memoryAge-style helper to lessons.py", "Inject staleness warning in lesson prompt text", "Test: lesson >1d old includes caveat"],
            "memdir/memoryAge.ts", "memory-knowledge"),
    _ticket(653, 0, 2, "memory-prompt-injection", "Implement memory-as-prompt-injection pattern",
            "Inject relevant lessons into agent system prompts at spawn time rather than providing as separate context.",
            ["Modify spawn_prompt.py to include relevant lessons in system prompt", "Budget max 5K tokens for memory injection", "Test: spawned agent prompt includes formatted lessons"],
            "memdir/memdir.ts", "memory-knowledge"),
    _ticket(654, 0, 1, "memory-truncation-warning", "Add truncation warnings when memory exceeds budget",
            "When memory content exceeds token budget, truncate with human-readable warning explaining what was removed.",
            ["Add truncation helper with line+byte dual-cap", "Append warning text listing removed items", "Test: oversized memory shows truncation notice"],
            "memdir/memdir.ts", "memory-knowledge"),
    _ticket(655, 1, 2, "lesson-secret-scanning", "Scan lessons for secrets before persisting",
            "Add gitleaks-pattern secret scanning to bulletin.py and lessons.py before writing to disk.",
            ["Integrate secret pattern matching", "Reject lessons containing API keys, passwords, tokens", "Log redacted content to metrics"],
            "services/teamMemorySync/index.ts", "memory-knowledge"),
    _ticket(656, 1, 3, "cross-agent-memory-sync", "Implement cross-agent lesson synchronization",
            "Enable lessons learned by one agent to be shared with others via bulletin board with hash-based dedup.",
            ["Add SHA-256 content hashing for lesson dedup", "Sync lessons via bulletin board append", "ETag-style conditional reads for efficiency"],
            "services/teamMemorySync/index.ts", "memory-knowledge"),
    _ticket(657, 1, 2, "memory-extraction-forked-agent", "Add forked-agent pattern for lesson extraction",
            "Quality gates should fork from the completed agent's context rather than starting fresh.",
            ["Add fork_from_context option to quality_gates.py", "Share prompt prefix for cache efficiency", "Test: forked gate sees parent's context"],
            "services/extractMemories/extractMemories.ts", "memory-knowledge"),
    _ticket(658, 1, 1, "trailing-run-coalescence", "Implement trailing run coalescence for quality gates",
            "Prevent duplicate quality gate runs when tasks complete in rapid succession.",
            ["Add in_progress flag with pending queue", "Coalesce pending into single trailing run", "Test: rapid completions produce one gate run"],
            "services/extractMemories/extractMemories.ts", "memory-knowledge"),
    _ticket(659, 0, 2, "three-gate-periodic-scheduling", "Implement three-gate scheduling for periodic tasks",
            "Add time+volume+lock gate pattern for metrics collection and retrospective generation.",
            ["Create ThreeGateScheduler with time, volume, and lock gates", "Apply to retrospective.py and metric_collector.py", "Test: all three gates must pass before execution"],
            "services/autoDream/autoDream.ts", "memory-knowledge"),
    _ticket(660, 0, 1, "lock-mtime-rollback-on-failure", "Add lock mtime rollback for crash-safe periodic tasks",
            "When a periodic task fails or is killed, reset lock mtime to allow retry on next schedule.",
            ["Implement mtime rollback in finally block", "Test: killed periodic task runs again on next cycle"],
            "services/autoDream/autoDream.ts", "memory-knowledge"),
    _ticket(661, 2, 2, "agent-scoped-memory", "Add agent-scoped persistent memory",
            "Implement user/project/local memory scopes for agents that persist across sessions.",
            ["Create .sdd/memory/{scope}/ directories", "Load scope-appropriate memories at agent spawn", "Test: memories persist across bernstein runs"],
            "tools/AgentTool/agentMemory.ts", "memory-knowledge"),
    _ticket(662, 2, 3, "memory-consolidation-dream", "Implement periodic memory consolidation",
            "Background task that consolidates accumulated lessons into higher-level patterns.",
            ["Create consolidation task with 24h time gate", "Summarize similar lessons into meta-patterns", "Delete or archive superseded individual lessons"],
            "services/autoDream/autoDream.ts", "memory-knowledge"),
    _ticket(663, 2, 1, "memory-manifest-format", "Add numbered memory manifest for agent context",
            "Format memories as a numbered list with age annotations for agent system prompts.",
            ["Create format_memory_manifest() helper", "Include age annotation per memory", "Cap at 200 items with freshness sort"],
            "memdir/memoryScan.ts", "memory-knowledge"),
    _ticket(664, 2, 2, "git-worktree-aware-memory", "Make memory canonical across git worktrees",
            "Ensure worktrees of the same repo share one memory directory via canonical git root resolution.",
            ["Add find_canonical_git_root() to worktree.py", "Use canonical root for memory path resolution", "Test: worktree agents share parent's memories"],
            "memdir/paths.ts", "memory-knowledge"),
    _ticket(665, 2, 1, "memory-relevance-scoring", "Add LLM-powered memory relevance selection",
            "Use cheap model to select most relevant memories for current task from full set.",
            ["Query small model with task context + memory list", "Return top-5 relevant memories", "Test: relevant memories ranked higher"],
            "memdir/findRelevantMemories.ts", "memory-knowledge"),
    _ticket(666, 1, 2, "mutual-exclusion-memory-writes", "Prevent duplicate memory writes between agent and gates",
            "Detect if main agent already wrote lessons and skip gate-level extraction.",
            ["Track lesson writes per task", "Gate checks for recent writes before extracting", "Test: no duplicate lessons when agent self-documents"],
            "services/extractMemories/extractMemories.ts", "memory-knowledge"),
    _ticket(667, 2, 1, "memory-type-decay-rates", "Configure per-type memory decay rates",
            "Different memory types should decay at different rates (feedback fast, user slow).",
            ["Add DECAY_RATES dict in lessons.py", "Apply rate during retrieval confidence calculation", "Test: old feedback lessons decay faster than user lessons"],
            "memdir/memoryTypes.ts", "memory-knowledge"),
    _ticket(668, 3, 2, "team-memory-path-security", "Add path traversal protection for memory files",
            "Validate memory file paths against null bytes, URL encoding, symlink attacks.",
            ["Port PathTraversalError and validation from teamMemPaths.ts", "Add realpath-based symlink verification", "Test: path traversal attempts rejected"],
            "memdir/teamMemPaths.ts", "memory-knowledge"),
    _ticket(669, 3, 3, "session-memory-post-sampling", "Add post-completion memory extraction hook",
            "Register hook that runs after each task completion to extract learnable memories.",
            ["Add post_task_complete hook for memory extraction", "Restrict extraction agent to read + memory-dir writes", "Test: lessons extracted after task completion"],
            "services/SessionMemory/sessionMemory.ts", "memory-knowledge"),
    _ticket(670, 3, 1, "memory-freshness-text", "Add human-readable freshness text for old memories",
            "Generate 'saved 2 days ago' style text for surfaced memories.",
            ["Add memory_freshness_text(timestamp) helper", "Include in surfaced lesson output", "Test: correct relative time strings"],
            "memdir/memoryAge.ts", "memory-knowledge"),
    _ticket(671, 0, 2, "sandboxed-tool-permissions", "Implement per-subagent tool restrictions",
            "Hard tool restrictions per spawned agent instead of just prompt-based.",
            ["Add allowed_tools/denied_tools to spawn config", "Enforce in spawner before tool execution", "Test: agent with deny=[bash] cannot run bash"],
            "services/extractMemories/extractMemories.ts", "memory-knowledge"),
    _ticket(672, 1, 3, "knowledge-base-context-budget", "Add token budget for knowledge base context injection",
            "Budget context window space when injecting knowledge base content into agent prompts.",
            ["Add max_context_tokens param to knowledge_base.py", "Track and cap injection at 50K tokens", "Test: large projects stay within budget"],
            "services/compact/compact.ts", "memory-knowledge"),
    _ticket(673, 3, 2, "memory-dedup-by-hash", "Deduplicate memories by content hash",
            "Use SHA-256 hashing to detect and merge duplicate lessons from different agents.",
            ["Add content_hash field to LessonRecord", "Skip insert if hash already exists, boost confidence instead", "Test: duplicate lessons merge rather than duplicate"],
            "services/teamMemorySync/index.ts", "memory-knowledge"),
    _ticket(674, 2, 2, "context-restoration-after-compaction", "Re-inject critical state after context compaction",
            "When agent context is compacted, re-inject .sdd/ state, active plan, and relevant files.",
            ["Create post_compaction_reinjection() helper", "Re-inject: task spec, role template, recent files (5k/file cap)", "Test: agent retains context after compaction"],
            "services/compact/compact.ts", "memory-knowledge"),
    _ticket(675, 3, 1, "memory-kairos-daily-log", "Design daily-log memory paradigm",
            "Document and prototype an append-only daily log with periodic consolidation.",
            ["Create design doc for daily-log memory model", "Add append-only log file format", "Create consolidation trigger spec"],
            "memdir/memdir.ts", "memory-knowledge"),

    # ── Pillar 2: Tool Ecosystem Compatibility (25 tickets) ──
    _ticket(676, 0, 2, "skill-md-format-compat", "Support SKILL.md format with YAML frontmatter",
            "Role templates should support Claude Code's SKILL.md format with frontmatter metadata.",
            ["Parse YAML frontmatter from role template .md files", "Extract: name, description, hooks, paths, context, effort", "Test: role template with frontmatter loads correctly"],
            "skills/loadSkillsDir.ts", "tool-ecosystem"),
    _ticket(677, 0, 2, "conditional-context-activation", "Activate context based on task file scope",
            "Activate role-specific context when task scope matches file patterns.",
            ["Add .gitignore-style path matching for context rules", "Activate matching context at task claim time", "Test: backend context activates for src/backend/ files"],
            "skills/loadSkillsDir.ts", "tool-ecosystem"),
    _ticket(678, 0, 1, "shell-command-in-prompts", "Support shell command embedding in role templates",
            "Allow role templates to include dynamic context via shell command output.",
            ["Parse !`command` syntax in templates", "Execute command and inject stdout into prompt", "Test: template with !`git branch` injects branch name"],
            "skills/loadSkillsDir.ts", "tool-ecosystem"),
    _ticket(679, 1, 2, "tool-interrupt-behavior", "Add per-tool interrupt behavior (cancel vs block)",
            "Different tools should respond differently to interrupts.",
            ["Add interrupt_behavior() to adapter base", "Bash: cancel on interrupt, FileEdit: block until complete", "Test: bash tool cancels, file edit blocks"],
            "services/tools/StreamingToolExecutor.ts", "tool-ecosystem"),
    _ticket(680, 1, 2, "tool-concurrency-safety", "Add input-dependent tool concurrency classification",
            "Classify tool safety for parallel execution based on input.",
            ["Add is_concurrency_safe(input) to tool definitions", "Conservative default on parse failure", "Test: read-only bash commands classified as safe"],
            "services/tools/toolOrchestration.ts", "tool-ecosystem"),
    _ticket(681, 0, 3, "28-hook-events", "Expand hook system to 28 lifecycle events",
            "Add PreToolUse, PostToolUse, SessionStart, CwdChanged, FileChanged and more hooks.",
            ["Add 22 new hook events to hookspecs.py", "Implement PreToolUse and PostToolUse with blocking semantics", "Add exit code 2 = blocking, 0 = success, other = non-blocking"],
            "utils/hooks/", "tool-ecosystem"),
    _ticket(682, 1, 1, "hook-exit-code-semantics", "Implement hook exit code semantics",
            "Exit code 0=success, 2=blocking (stop operation), other=non-blocking error.",
            ["Map exit codes in hook executor", "Exit 2 surfaces stderr to agent and blocks operation", "Test: exit code 2 prevents tool execution"],
            "utils/hooks/", "tool-ecosystem"),
    _ticket(683, 1, 2, "async-hooks-support", "Add async hook execution",
            "Hooks should support async execution via config flag or runtime detection.",
            ["Add async: true flag in hook config", "Detect first-line JSON {async:true} for runtime async", "Test: async hook runs without blocking main flow"],
            "utils/hooks/", "tool-ecosystem"),
    _ticket(684, 0, 2, "layered-permission-graph", "Implement layered permission decision graph",
            "Multi-layer permission resolution: deny\u2192ask\u2192tool.check\u2192safety\u2192mode\u2192allow.",
            ["Create PermissionResolver with layered pipeline", "Support blanket deny/ask rules, tool-specific checks, safety checks", "Test: deny rule overrides tool allow"],
            "utils/permissions/permissions.ts", "tool-ecosystem"),
    _ticket(685, 1, 2, "hook-permission-resolution", "Add hook-permission resolution matrix",
            "PreToolUse hook allow should not bypass deny/ask rules.",
            ["Implement resolution matrix: hook allow + rule deny = deny", "Hook deny always wins", "Test: hook allow does not bypass deny rule"],
            "utils/permissions/toolHooks.ts", "tool-ecosystem"),
    _ticket(686, 2, 2, "tool-search-discovery", "Add model-visible tool search for deferred tools",
            "Allow agents to discover and activate deferred tools by keyword search.",
            ["Create tool_search() function with keyword scoring", "Return tool references for activation", "Test: agent finds deferred tool by description"],
            "tools/ToolSearchTool/", "tool-ecosystem"),
    _ticket(687, 2, 1, "tool-result-integrity", "Add tool result integrity verification",
            "Track tool-use IDs to prevent duplicate or orphaned results.",
            ["Add resolved_tool_use_ids set to agent context", "Verify each result maps to a known tool-use", "Test: orphaned result detected and logged"],
            "cli/structuredIO.ts", "tool-ecosystem"),
    _ticket(688, 2, 3, "diagnostic-tracking-integration", "Add IDE diagnostic tracking for edit quality",
            "Capture diagnostics before and after agent edits for quality measurement.",
            ["Integrate with LSP/linter to capture pre/post diagnostics", "Record diagnostic deltas in .sdd/metrics/", "Test: diagnostic improvement measured after edit"],
            "services/diagnosticTracking.ts", "tool-ecosystem"),
    _ticket(689, 0, 1, "orphan-tool-result-prevention", "Prevent orphan tool results on agent fallback",
            "Emit synthetic tool results for in-flight tools when agent switches or fails.",
            ["On agent failure, emit synthetic results for pending tool-uses", "Mark as 'abandoned' with reason", "Test: no orphan tool-use IDs after fallback"],
            "query.ts", "tool-ecosystem"),
    _ticket(690, 2, 2, "compaction-boundary-markers", "Add compaction boundary markers in agent context",
            "Mark where compaction occurred so agents know context was summarized.",
            ["Insert SystemCompactBoundaryMessage after compaction", "Include: what was compacted, token reduction", "Test: agent can detect compaction boundary"],
            "services/compact/compact.ts", "tool-ecosystem"),
    _ticket(691, 2, 1, "tool-batching-partition", "Improve tool call partitioning by safety class",
            "Partition tool calls into concurrent/serial batches based on safety.",
            ["Implement partition_tool_calls with safety classification", "Consecutive safe tools in same batch, unsafe tools solo", "Test: file reads batched, bash calls serialized"],
            "services/tools/toolOrchestration.ts", "tool-ecosystem"),
    _ticket(692, 3, 2, "sibling-abort-on-bash-error", "Add sibling abort when bash tool fails",
            "When a bash tool errors, abort sibling concurrent tools.",
            ["Add sibling abort controller to tool executor", "Only bash errors trigger abort (other tools don't)", "Test: bash error aborts concurrent file read"],
            "services/tools/StreamingToolExecutor.ts", "tool-ecosystem"),
    _ticket(693, 1, 2, "cache-break-detection", "Implement prompt cache break detection with diffs",
            "Detect when prompt cache hit rate drops significantly and alert.",
            ["Hash system text, tools, schemas per agent", "Detect >5% drop in cache tokens AND \u22652K absolute drop", "Log cache break events with diff explanation"],
            "utils/promptCacheBreakDetection.ts", "tool-ecosystem"),
    _ticket(694, 0, 2, "autocompact-circuit-breaker", "Add circuit breaker for auto-compaction",
            "Stop auto-compaction after 3 consecutive failures.",
            ["Add failure counter to compaction logic", "Skip compaction when counter hits 3", "Reset counter on success"],
            "services/compact/autoCompact.ts", "tool-ecosystem"),
    _ticket(695, 2, 1, "post-compact-file-reinjection", "Re-inject recently-read files after compaction",
            "After context compaction, re-inject up to 5 recently-read files within 50K token budget.",
            ["Track recently-read files per agent", "Re-inject with 5K/file and 50K total cap", "Test: agent retains key files after compaction"],
            "services/compact/compact.ts", "tool-ecosystem"),
    _ticket(696, 3, 1, "token-budget-continuation", "Add token budget continuation with nudge messages",
            "When agent hits output token limit, inject meta message to continue.",
            ["Create synthetic user message with isMeta=true", "Recompute budget post-compact", "Test: agent continues after token limit nudge"],
            "query.ts", "tool-ecosystem"),
    _ticket(697, 3, 2, "context-collapse-drain-retry", "Implement context collapse with drain retry",
            "Collapse old context and retry on overflow.",
            ["Add collapse_drain_retry transition to agent lifecycle", "Collapse oldest context groups first", "Test: agent recovers from context overflow"],
            "query.ts", "tool-ecosystem"),
    _ticket(698, 2, 3, "notebook-aware-traces", "Add Jupyter notebook awareness to agent traces",
            "Agent traces should capture notebook cell edits distinctly from file edits.",
            ["Detect .ipynb files in tool results", "Record cell index and cell type in trace", "Test: notebook edit trace includes cell metadata"],
            "tools/NotebookEditTool/", "tool-ecosystem"),
    _ticket(699, 1, 1, "background-query-throttling", "Throttle background query retry on rate limits",
            "Background quality gate queries should not retry on 529 to prevent amplification.",
            ["Add FOREGROUND_RETRY_SOURCES set", "Background sources get zero 529 retries", "Test: background gate skips retry on 529"],
            "services/api/withRetry.ts", "tool-ecosystem"),
    _ticket(700, 3, 2, "persistent-unattended-retry", "Add persistent retry for unattended mode",
            "In headless mode, infinite retry on 429/529 with heartbeat chunks.",
            ["Add persistent_retry mode to agent spawner", "30s heartbeat chunks during retry wait", "Test: headless agent survives rate limit storm"],
            "services/api/withRetry.ts", "tool-ecosystem"),

    # ── Pillar 3: Agent Self-Organization (25 tickets) ──
    _ticket(701, 0, 3, "verification-nudge-system", "Implement verification nudge for unverified completions",
            "Track when agents complete tasks without running verification and flag them.",
            ["Add verification_count to task completion tracking", "Flag tasks with completions > verifications", "Alert in TUI/status when nudge threshold exceeded"],
            "tools/TaskUpdateTool/", "agent-self-org"),
    _ticket(702, 1, 3, "agent-task-self-creation", "Allow agents to create subtasks via API",
            "Agents should be able to decompose their work into subtasks during execution.",
            ["Add POST /tasks/self-create endpoint", "Agent creates child tasks with parent_id linkage", "Test: agent creates subtask and it appears in backlog"],
            "tools/TaskCreateTool/", "agent-self-org"),
    _ticket(703, 1, 2, "agent-task-blocking-graph", "Add blocking/blockedBy relationships between tasks",
            "Tasks should track which other tasks they block or are blocked by.",
            ["Add blocks and blocked_by fields to Task model", "Update task_lifecycle.py to check blockers before claiming", "Test: blocked task not claimable until blockers complete"],
            "tools/TaskGetTool/", "agent-self-org"),
    _ticket(704, 0, 2, "parent-child-abort-chain", "Implement parent\u2192child abort propagation",
            "When parent agent is killed, children should receive abort signal.",
            ["Create linked asyncio.Event chain for abort", "Parent abort propagates to all children", "Test: killing parent kills child agents"],
            "tasks/LocalAgentTask/LocalAgentTask.tsx", "agent-self-org"),
    _ticket(705, 1, 2, "task-eviction-grace-period", "Add grace period before completed task state cleanup",
            "Completed tasks should remain visible for 30s before cleanup.",
            ["Add PANEL_GRACE_MS (30000) to task lifecycle", "Don't evict completed tasks until grace period expires", "Test: completed task visible for 30s in status"],
            "tasks/LocalAgentTask/LocalAgentTask.tsx", "agent-self-org"),
    _ticket(706, 2, 3, "plan-mode-read-only", "Implement plan mode as permission context change",
            "Planning should use same tools in read-only mode, not separate execution.",
            ["Add plan mode flag to agent context", "In plan mode: all write tools return read-only results", "Test: agent in plan mode cannot modify files"],
            "tools/EnterPlanModeTool/", "agent-self-org"),
    _ticket(707, 2, 2, "plan-persistence-to-disk", "Persist plans to disk for approval workflow",
            "Agent-generated plans should be saved as YAML files for review.",
            ["Write plan to .sdd/plans/{task_id}.yaml on plan exit", "Include plan text, allowed actions, scope", "Test: plan file created and readable"],
            "tools/ExitPlanModeTool/", "agent-self-org"),
    _ticket(708, 1, 3, "fork-subagent-cache-sharing", "Implement fork subagent with byte-identical prefix",
            "Quality gates and reviewers should share prompt cache with parent via byte-identical prefixes.",
            ["Create fork_from_agent() that copies system prompt exactly", "Only vary the final directive text", "Test: forked agent achieves cache hit on parent's prefix"],
            "tools/AgentTool/forkSubagent.ts", "agent-self-org"),
    _ticket(709, 2, 2, "dream-crash-safe-retry", "Implement crash-safe retry for periodic tasks",
            "Lock mtime rollback on failure allows retry on next schedule.",
            ["On periodic task failure, reset lock file mtime to 0", "Next schedule check sees stale lock and retries", "Test: failed periodic task retries on next cycle"],
            "tasks/DreamTask/DreamTask.ts", "agent-self-org"),
    _ticket(710, 2, 2, "structured-agent-messages", "Add structured message types for agent communication",
            "Support typed messages (shutdown_request, plan_approval, task_assignment) in bulletin.",
            ["Define message type enum for bulletin board", "Parse and route by message type", "Test: shutdown_request message handled correctly"],
            "tools/SendMessageTool/", "agent-self-org"),
    _ticket(711, 0, 2, "coordinator-mode-phases", "Enhance coordinator with named phases",
            "Research\u2192Synthesis\u2192Implementation\u2192Verification phase progression.",
            ["Add phase enum to orchestrator state", "Phase-appropriate tool filtering", "Log phase transitions to metrics"],
            "coordinator/coordinatorMode.ts", "agent-self-org"),
    _ticket(712, 2, 2, "scratchpad-directory", "Add cross-agent scratchpad directory",
            "Durable knowledge sharing directory for agents within a run.",
            ["Create .sdd/runtime/scratchpad/ at bootstrap", "Inject scratchpad path in agent prompts", "Test: agent writes to scratchpad, other agent reads it"],
            "coordinator/coordinatorMode.ts", "agent-self-org"),
    _ticket(713, 3, 3, "team-file-management", "Implement team file for multi-cell metadata",
            "Structured team configuration with member metadata.",
            ["Create team config JSON with member: id, name, role, model, color", "Track active/inactive state", "Test: team file persists across cell lifecycle"],
            "utils/swarm/", "agent-self-org"),
    _ticket(714, 3, 2, "mailbox-async-messaging", "Add mailbox-based async agent-to-agent messaging",
            "Leaders and workers communicate via persistent mailboxes.",
            ["Create mailbox per agent in .sdd/runtime/mailboxes/", "Write/read/poll semantics with message ordering", "Test: leader sends message, worker receives it"],
            "utils/swarm/", "agent-self-org"),
    _ticket(715, 1, 2, "worker-badge-identity", "Add visual identity badges for concurrent agents",
            "Each agent gets a unique color/name for log and TUI distinction.",
            ["Assign deterministic color from palette by agent index", "Include badge in log prefix and TUI display", "Test: 3 agents get distinct colors"],
            "utils/swarm/", "agent-self-org"),
    _ticket(716, 2, 1, "task-notification-protocol", "Implement worker status notification protocol",
            "Workers report progress via structured XML notifications.",
            ["Define <task-notification> format with status, progress, findings", "Parse notifications in orchestrator", "Test: worker notification updates task state"],
            "coordinator/coordinatorMode.ts", "agent-self-org"),
    _ticket(717, 3, 3, "agent-resume-from-transcript", "Support agent resumption from saved transcripts",
            "Resume interrupted agents from their saved trace state.",
            ["Save agent state to .sdd/traces/ on interruption", "Restore messages and tool state on resume", "Test: interrupted agent resumes from checkpoint"],
            "tools/AgentTool/resumeAgent.ts", "agent-self-org"),
    _ticket(718, 2, 2, "multi-agent-spawn-backends", "Support multiple agent spawn backends",
            "tmux split-pane, separate windows, in-process modes.",
            ["Add SpawnBackend enum: tmux_split, tmux_window, in_process", "Propagate CLI flags and environment to children", "Test: agent spawns in tmux split pane"],
            "shared/spawnMultiAgent.ts", "agent-self-org"),
    _ticket(719, 0, 1, "task-hook-rejection", "Allow hooks to reject task operations",
            "TaskCreated/TaskCompleted hooks should be able to block the operation.",
            ["Add hook execution before task state changes", "If hook returns blocking, rollback the operation", "Test: hook blocks task creation with error message"],
            "tools/TaskCreateTool/", "agent-self-org"),
    _ticket(720, 2, 2, "foreground-background-promotion", "Support runtime task mode switching",
            "Tasks should be promotable from foreground to background.",
            ["Add promote_to_background() with asyncio.Event signal", "Status updates reflect current mode", "Test: foreground task promoted, continues in background"],
            "tasks/LocalAgentTask/LocalAgentTask.tsx", "agent-self-org"),
    _ticket(721, 1, 1, "progress-tracking-cumulative", "Implement cumulative token accounting per agent",
            "Track additive output tokens and latest input tokens per agent.",
            ["Add AgentProgress dataclass with cumulative counters", "Update on each streaming message", "Test: progress shows accurate cumulative tokens"],
            "tasks/LocalAgentTask/LocalAgentTask.tsx", "agent-self-org"),
    _ticket(722, 3, 2, "async-local-storage-isolation", "Add async context isolation for concurrent agents",
            "Concurrent agent async tasks should not leak context.",
            ["Use contextvars for per-agent context isolation", "Each agent gets isolated context chain", "Test: concurrent agents don't see each other's state"],
            "tasks/LocalAgentTask/LocalAgentTask.tsx", "agent-self-org"),
    _ticket(723, 0, 2, "convergence-guard-spawn-wave", "Implement convergence guard before spawn waves",
            "Check system convergence before spawning new agent batches.",
            ["Create ConvergenceGuard checking: pending merges, active agents, error rate", "Block spawn if system not converged", "Test: high error rate blocks new spawn wave"],
            "bio-adapt (external)", "agent-self-org"),
    _ticket(724, 2, 3, "typed-task-graph-edges", "Add typed edges to task dependency graph",
            "Support conditional, filtered, review-gate, and fan-out edge types.",
            ["Extend graph.py with edge_type field", "Support: depends_on, conditional_on, review_gate, fan_out", "Test: conditional edge skips when condition false"],
            "Neuron (external)", "agent-self-org"),
    _ticket(725, 3, 2, "task-deadline-field", "Add deadline field to task specifications",
            "Tasks should have optional deadline for SLA enforcement.",
            ["Add deadline field to Task model", "Alert when task approaches deadline", "Test: overdue task flagged in status"],
            "agent-task-protocol (external)", "agent-self-org"),

    # ── Pillar 4: Developer Experience (25 tickets) ──
    _ticket(726, 0, 3, "bernstein-doctor", "Implement comprehensive bernstein doctor command",
            "Guided diagnostic command with preflight checks, agent discovery, MCP health, .sdd/ integrity.",
            ["Check: agent CLIs installed, API keys valid, ports available", "Check: .sdd/ directory structure, stale locks, orphan PIDs", "Check: MCP servers reachable, worktree state", "Output: actionable remediation for each issue"],
            "screens/Doctor.tsx", "developer-experience"),
    _ticket(727, 0, 1, "git-safety-protocol-prompts", "Inject Git Safety Protocol into all agent prompts",
            "All agents should receive git safety rules in their system prompt.",
            ["Add git safety section to base role template", "Rules: no force push, no hook skip, no secret commits", "Test: agent prompt includes git safety protocol"],
            "commands/commit-push-pr.ts", "developer-experience"),
    _ticket(728, 0, 2, "context-token-accounting", "Show context window token accounting",
            "Display where context budget is spent (system prompt, memory, tools, RAG).",
            ["Add context_analysis() returning per-category token counts", "Display in bernstein status with percentages", "Test: token accounting matches actual prompt size"],
            "utils/analyzeContext.ts", "developer-experience"),
    _ticket(729, 1, 2, "session-analytics-insights", "Analyze .sdd/traces/ for per-task facets",
            "LLM-powered analysis of task traces to extract goals, satisfaction, friction.",
            ["Parse JSONL traces into SessionMeta objects", "Extract facets: goal, category, agent helpfulness", "Generate summary report in .sdd/reports/"],
            "commands/insights.ts", "developer-experience"),
    _ticket(730, 1, 2, "api-preconnect-warmup", "Warm API connections before first agent spawn",
            "Fire-and-forget HEAD request to warm connection pool.",
            ["Add api_preconnect() in bootstrap.py", "10s timeout, skip for local/proxy providers", "Test: first API call latency reduced"],
            "utils/apiPreconnect.ts", "developer-experience"),
    _ticket(731, 2, 1, "side-question-btw", "Support side-question mode for quick queries",
            "Agent can ask clarifying questions without interrupting main task flow.",
            ["Add /btw-style side query to bulletin protocol", "Side query uses cache-aligned params for efficiency", "Test: side query doesn't disrupt main task context"],
            "commands/btw/", "developer-experience"),
    _ticket(732, 2, 2, "terminal-screenshot-export", "Export terminal output as PNG/SVG",
            "Generate shareable screenshots of agent output.",
            ["Implement ansi_to_png() with bitmap font rendering", "Implement ansi_to_svg() with proper color mapping", "Test: output produces valid PNG/SVG files"],
            "utils/ansiToPng.ts", "developer-experience"),
    _ticket(733, 1, 2, "keybinding-system-tui", "Add customizable keybinding system to TUI",
            "Support chord keys, contexts, and user customization.",
            ["Define DEFAULT_BINDINGS with action\u2192key mappings", "Support ~/.bernstein/keybindings.json user overrides", "Reserve ctrl+c and ctrl+d as non-rebindable"],
            "keybindings/", "developer-experience"),
    _ticket(734, 2, 3, "transcript-search-overlay", "Add fuzzy search overlay for agent transcripts",
            "Search and navigate through agent conversation history.",
            ["Implement fuzzy matching over transcript messages", "Preview panel with matched context", "Test: search finds partial matches across messages"],
            "components/HistorySearchDialog.tsx", "developer-experience"),
    _ticket(735, 2, 2, "diff-folding-display", "Add collapsible diff display in TUI",
            "Large diffs should be foldable to show summary first.",
            ["Implement fold/expand for file diffs", "Show line count and change summary when folded", "Test: large diff starts folded, expands on action"],
            "components/", "developer-experience"),
    _ticket(736, 2, 1, "activity-tracking-metrics", "Track user vs agent activity time",
            "Measure active time with dedup via operation IDs.",
            ["Create ActivityManager with user/agent tracking", "5s idle window for user activity", "Emit metrics to .sdd/metrics/"],
            "utils/activityManager.ts", "developer-experience"),
    _ticket(737, 3, 2, "rename-session-command", "Add session rename with auto-naming",
            "Allow renaming orchestration sessions with LLM-generated names.",
            ["Add bernstein rename command", "Auto-generate name from task descriptions via cheap model", "Test: session renamed in .sdd/runtime/"],
            "commands/rename/", "developer-experience"),
    _ticket(738, 3, 2, "rewind-checkpoint-command", "Add rewind to previous checkpoint",
            "Restore orchestration state to earlier point.",
            ["Add bernstein rewind command", "List available checkpoints with timestamps", "Test: state restored to selected checkpoint"],
            "commands/rewind/", "developer-experience"),
    _ticket(739, 1, 1, "output-style-customization", "Support customizable output styles",
            "Allow users to configure agent output format via markdown templates.",
            ["Load output styles from .bernstein/output-styles/", "YAML frontmatter: name, description, keep-coding-instructions", "Test: custom output style applied to agent output"],
            "outputStyles/", "developer-experience"),
    _ticket(740, 2, 1, "release-notes-display", "Show changelog in bernstein version",
            "Display formatted release notes with auto-fetch.",
            ["Fetch CHANGELOG.md with 500ms timeout, fallback to URL", "Format as numbered list in terminal", "Test: release notes display correctly"],
            "commands/release-notes/", "developer-experience"),
    _ticket(741, 0, 2, "doctor-context-warnings", "Add context warnings to bernstein doctor",
            "Warn about stale configs, unreachable rules, MCP issues.",
            ["Check CLAUDE.md/agents for parse errors", "Check MCP server reachability", "Check permission rules for unreachable conditions"],
            "utils/doctorContextWarnings.ts", "developer-experience"),
    _ticket(742, 2, 2, "progressive-permission-prompts", "Add progressive disclosure for permission requests",
            "Permission prompts should expand into feedback mode, not just yes/no.",
            ["Add explain option to permission prompts", "Show tool context and operation details on expand", "Test: user can request explanation before approving"],
            "components/permissions/PermissionPrompt.tsx", "developer-experience"),
    _ticket(743, 3, 1, "session-tag-system", "Add searchable tags for orchestration sessions",
            "Tag sessions for categorization and retrieval.",
            ["Add tags field to session metadata", "Support add/remove/list tags CLI", "Test: session filterable by tag"],
            "commands/tag/", "developer-experience"),
    _ticket(744, 3, 3, "security-review-command", "Add automated security review command",
            "3-phase security audit of agent-produced changes.",
            ["Phase 1: surface scan of changed files", "Phase 2: deep analysis of patterns (injection, auth, crypto)", "Phase 3: synthesis with confidence scores", "Test: security review produces actionable report"],
            "commands/security-review.ts", "developer-experience"),
    _ticket(745, 1, 1, "installation-mismatch-detection", "Detect and warn about installation mismatches",
            "Doctor should detect multiple installations and config/reality conflicts.",
            ["Check for multiple bernstein installations in PATH", "Warn if config references unavailable features", "Test: dual installation detected and reported"],
            "cli/update.ts", "developer-experience"),
    _ticket(746, 2, 2, "agent-summary-periodic", "Add 30s periodic activity summaries for background agents",
            "Generate short activity descriptions for dashboard display.",
            ["Fork agent to produce 3-5 word activity summary", "Update every 30s via periodic polling", "Test: summary updates reflect current agent activity"],
            "services/AgentSummary/agentSummary.ts", "developer-experience"),
    _ticket(747, 2, 1, "away-summary-generation", "Generate 'since you were away' recap",
            "Produce summary of changes since last user interaction.",
            ["Use cheap model on last 30 messages + session context", "Return null gracefully on error", "Test: away summary covers recent completions"],
            "services/awaySummary.ts", "developer-experience"),
    _ticket(748, 3, 2, "prompt-suggestion-engine", "Add smart prompt suggestions",
            "Suggest next actions based on project state.",
            ["Analyze recent task outcomes and backlog", "Generate top-3 suggested next steps", "Test: suggestions relevant to current project state"],
            "services/PromptSuggestion/", "developer-experience"),
    _ticket(749, 3, 1, "contextual-tips-system", "Add contextual tips with cooldown",
            "Display relevant tips with session-based cooldown.",
            ["Create tip registry with relevance checks", "Cooldown: skip tip for N sessions after shown", "Test: tip shown once, then cooled down"],
            "services/tips/", "developer-experience"),
    _ticket(750, 2, 1, "commit-attribution-stats", "Add code attribution to agent commits",
            "Include contribution stats in commit messages.",
            ["Extract lines added/removed per file", "Add git trailer with attribution", "Test: commit message includes attribution stats"],
            "utils/attribution.ts", "developer-experience"),

    # ── Pillar 5: Enterprise Runtime (25 tickets) ──
    _ticket(751, 0, 3, "settings-cascade-5-layer", "Implement 5-layer settings cascade",
            "Settings from user\u2192project\u2192local\u2192CLI\u2192managed with provenance tracking.",
            ["Create SettingsCascade with 5 sources", "Zod validation at each layer", "Provenance tracking: which source provided each value"],
            "utils/settings/", "enterprise-runtime"),
    _ticket(752, 0, 2, "policy-limits-fail-open", "Implement policy limits with fail-open defaults",
            "Enterprise feature restrictions with sensible fail-open behavior.",
            ["Fetch policy from API with ETag caching", "Fail-open by default, deny-on-miss for security-critical", "Background polling every hour"],
            "services/policyLimits/index.ts", "enterprise-runtime"),
    _ticket(753, 1, 3, "remote-worker-poll-distribution", "Add poll-based remote worker distribution",
            "Remote agents receive work via configurable poll intervals.",
            ["Implement poll endpoint with configurable intervals", "Capacity management: max concurrent sessions", "Wake signal when capacity frees"],
            "bridge/bridgeMain.ts", "enterprise-runtime"),
    _ticket(754, 1, 3, "jwt-token-lifecycle", "Implement JWT token lifecycle with proactive refresh",
            "Proactive token refresh 5 minutes before expiry.",
            ["Create TokenRefreshScheduler with 5min buffer", "Max 3 refresh failures before fatal", "Generation tracking prevents stale refresh"],
            "bridge/jwtUtils.ts", "enterprise-runtime"),
    _ticket(755, 2, 3, "trusted-device-enrollment", "Add trusted device enrollment for elevated security",
            "OS keychain-backed device trust for sensitive operations.",
            ["Store device token in OS keychain", "Include X-Trusted-Device-Token header", "Test: elevated operations require trusted device"],
            "bridge/trustedDevice.ts", "enterprise-runtime"),
    _ticket(756, 1, 2, "etag-conditional-requests", "Implement ETag-based conditional requests",
            "All remote API interactions should use conditional requests.",
            ["Add ETag tracking to API client", "Send If-None-Match header, handle 304", "Test: unchanged data returns 304 without transfer"],
            "services/teamMemorySync/index.ts", "enterprise-runtime"),
    _ticket(757, 2, 2, "settings-provenance-tracking", "Track which source provided each setting value",
            "Every effective setting should know where it came from.",
            ["Add source field to resolved settings", "Log conflicts between layers", "Test: provenance traced for overridden settings"],
            "bootstrap/state.ts", "enterprise-runtime"),
    _ticket(758, 2, 3, "remote-transport-recovery", "Implement transport recovery with epoch tracking",
            "Remote connections should recover from interruptions.",
            ["Track transport epoch for reconnection", "Detect message gaps and request replay", "Crash bundle capture for diagnostics"],
            "bridge/remoteBridgeCore.ts", "enterprise-runtime"),
    _ticket(759, 2, 2, "managed-settings-mdm", "Support MDM-managed settings for enterprise",
            "Enterprise admins push settings via managed configuration.",
            ["Read managed-settings.json from system paths", "Merge into settings cascade at highest priority", "Test: managed setting overrides user setting"],
            "utils/settings/", "enterprise-runtime"),
    _ticket(760, 0, 2, "poll-config-tunable", "Add GrowthBook-style tunable poll intervals",
            "Poll intervals tunable remotely with safety invariants.",
            ["Create PollConfig with Zod-validated intervals", "Safety: min 100ms, max 600s, at least one liveness mechanism", "Test: invalid config rejected by validation"],
            "bridge/pollConfig.ts", "enterprise-runtime"),
    _ticket(761, 1, 2, "capacity-wake-signal", "Implement capacity wake signal pattern",
            "Merged abort signal from outer loop + capacity-free events.",
            ["Create CapacityWake with merged abort sources", "Wake poll loop early when capacity available", "Test: wake signal fires when agent completes"],
            "bridge/capacityWake.ts", "enterprise-runtime"),
    _ticket(762, 2, 2, "sleep-detection-poll", "Add sleep detection for poll intervals",
            "Detect laptop sleep/wake to avoid false alarm resets.",
            ["Track poll interval timing", "2x cap threshold = sleep detected", "Test: simulated sleep triggers detection"],
            "bridge/bridgeMain.ts", "enterprise-runtime"),
    _ticket(763, 3, 3, "ndjson-streaming-protocol", "Implement NDJSON streaming for agent communication",
            "Parent/child processes communicate via newline-delimited JSON.",
            ["Define message types: assistant, result, control_request, user", "Parse NDJSON from agent stdout line-by-line", "Test: full message round-trip via NDJSON"],
            "bridge/sessionRunner.ts", "enterprise-runtime"),
    _ticket(764, 3, 2, "bridge-session-spawner", "Add child process spawner for remote sessions",
            "Spawn Claude Code instances with proper environment setup.",
            ["Build child process args with session ID", "Set environment: CLAUDE_CODE_ENVIRONMENT_KIND=bridge", "Test: child process starts with correct env"],
            "bridge/sessionRunner.ts", "enterprise-runtime"),
    _ticket(765, 1, 2, "oauth-pkce-flow", "Implement OAuth PKCE authorization flow",
            "Support OAuth 2.0 Authorization Code + PKCE for web dashboard.",
            ["Generate code_verifier (128-char) and code_challenge (SHA-256)", "Support automatic (browser) and manual (paste code) modes", "Test: full OAuth flow produces valid tokens"],
            "services/oauth/index.ts", "enterprise-runtime"),
    _ticket(766, 2, 2, "flush-gate-queue", "Implement flush gate for message queuing",
            "Queue messages during initial sync to prevent interleaving.",
            ["Create FlushGate state machine with queue/drain phases", "Drain queued messages on sync complete", "Test: messages queued during flush, delivered after"],
            "bridge/flushGate.ts", "enterprise-runtime"),
    _ticket(767, 3, 2, "compliance-mode-enum", "Add compliance mode configuration",
            "DEVELOPMENT/STANDARD/REGULATED modes with fail-fast validation.",
            ["Create ComplianceMode enum", "REGULATED mode enables strictest validation", "Test: invalid config in REGULATED mode fails fast"],
            "intentusnet (external)", "enterprise-runtime"),
    _ticket(768, 0, 1, "initialization-timeout-guard", "Add 30s timeout guard for initialization paths",
            "Prevent deadlocks during startup.",
            ["Add 30s timeout to all initialization awaits", "Log timeout with diagnostic context", "Test: stuck initialization times out gracefully"],
            "services/policyLimits/index.ts", "enterprise-runtime"),
    _ticket(769, 3, 3, "wal-hash-chained-records", "Implement WAL with hash-chained execution records",
            "Append-only log with cryptographic integrity for audit.",
            ["Create WAL with SHA-256 chain linking records", "Support replay from arbitrary checkpoint", "Test: tampered record detected by chain verification"],
            "intentusnet (external)", "enterprise-runtime"),
    _ticket(770, 2, 1, "settings-snapshot-in-traces", "Include settings snapshot in execution traces",
            "Reproducible runs require knowing exact settings used.",
            ["Serialize effective settings to .sdd/traces/ at run start", "Include provenance for each value", "Test: trace includes complete settings snapshot"],
            "bootstrap/state.ts", "enterprise-runtime"),
    _ticket(771, 2, 2, "backoff-with-caps", "Implement backoff with caps and give-up thresholds",
            "Exponential backoff with configurable cap and total give-up time.",
            ["Create Backoff class with initial, cap, give_up params", "Jitter: random factor on each delay", "Test: backoff caps at configured ceiling"],
            "bridge/bridgeMain.ts", "enterprise-runtime"),
    _ticket(772, 1, 1, "fatal-vs-retryable-errors", "Classify errors as fatal vs retryable",
            "Error classification for proper retry behavior.",
            ["Create ErrorClassification enum: fatal, retryable, suppressible", "Map HTTP codes: 401/403/404/410=fatal, 429/529=retryable", "Test: fatal error stops retry loop"],
            "bridge/bridgeApi.ts", "enterprise-runtime"),
    _ticket(773, 3, 1, "idempotent-operations", "Ensure idempotent task completion",
            "Duplicate completion calls should succeed without side effects.",
            ["Return 409 on duplicate completion", "Treat 409 as success (already done)", "Test: double-complete produces no error"],
            "bridge/bridgeApi.ts", "enterprise-runtime"),
    _ticket(774, 0, 2, "managed-plugin-policy", "Implement enterprise plugin allowlist/blocklist",
            "Admin-controlled plugin policies for enterprise deployments.",
            ["Read .bernstein/plugins-policy.yaml", "Support: allowlist, blocklist, managed plugins", "Test: blocked plugin rejected at load time"],
            "utils/plugins/pluginPolicy.ts", "enterprise-runtime"),
    _ticket(775, 3, 2, "inbound-message-normalization", "Normalize inbound messages from different sources",
            "Handle format differences from mobile, web, CLI clients.",
            ["Normalize image blocks (camelCase \u2192 snake_case media_type)", "Handle missing fields gracefully", "Test: mobile-format message normalized correctly"],
            "bridge/inboundMessages.ts", "enterprise-runtime"),

    # ── Pillar 6: Plugin & Skill Ecosystem (25 tickets) ──
    _ticket(776, 0, 3, "plugin-manifest-validation", "Implement Zod-style plugin manifest validation",
            "Strict validation with anti-impersonation and path traversal prevention.",
            ["Create PluginManifest schema with Zod-equivalent validation", "Block official name impersonation patterns", "Reject .. path traversal in all paths"],
            "utils/plugins/schemas.ts", "plugin-skill-ecosystem"),
    _ticket(777, 0, 2, "multi-source-plugin-install", "Support multi-source plugin installation",
            "Install plugins from GitHub, git, npm, file, and directory sources.",
            ["Create PluginSource union type with 5 variants", "Each source has its own install/update logic", "Test: plugin installs from GitHub release URL"],
            "utils/plugins/schemas.ts", "plugin-skill-ecosystem"),
    _ticket(778, 1, 3, "plugin-hot-reload", "Add hot-reload for plugins and role templates",
            "File watcher triggers reload on changes.",
            ["Watch plugin/role directories with file watcher", "Debounced reload clears caches and reloads", "Test: modified role template picked up without restart"],
            "utils/skills/skillChangeDetector.ts", "plugin-skill-ecosystem"),
    _ticket(779, 1, 2, "plugin-subsystem-separation", "Separate plugin subsystems (commands, hooks, MCP, etc)",
            "Each plugin subsystem loaded by a separate module.",
            ["Split plugin loading: commands, agents, hooks, MCP servers", "Independent error handling per subsystem", "Test: hook loading failure doesn't break command loading"],
            "utils/plugins/", "plugin-skill-ecosystem"),
    _ticket(780, 1, 2, "plugin-auto-uninstall-delisted", "Auto-uninstall delisted plugins",
            "Reconcile installed plugins against marketplace on startup.",
            ["Compare installed vs marketplace on startup", "Auto-remove plugins no longer in marketplace", "Test: delisted plugin removed on next start"],
            "utils/plugins/pluginBlocklist.ts", "plugin-skill-ecosystem"),
    _ticket(781, 2, 3, "plugin-marketplace-ui", "Add plugin marketplace browsing UI",
            "TUI interface for discovering, installing, managing plugins.",
            ["Browse available plugins with descriptions", "Install/uninstall with confirmation", "Show plugin health and version info"],
            "commands/plugin/", "plugin-skill-ecosystem"),
    _ticket(782, 2, 2, "plugin-trust-warning", "Show trust warning before plugin installation",
            "Display plugin source, permissions, and trust level.",
            ["Show plugin source, author, requested permissions", "Require explicit confirmation for untrusted sources", "Test: untrusted plugin shows warning"],
            "commands/plugin/PluginTrustWarning.tsx", "plugin-skill-ecosystem"),
    _ticket(783, 2, 2, "plugin-options-storage", "Add plugin-specific option storage",
            "Plugins can define and persist user configuration.",
            ["Create per-plugin options file", "Validate options against plugin-defined schema", "Test: plugin option persisted and loaded"],
            "utils/plugins/pluginOptionsStorage.ts", "plugin-skill-ecosystem"),
    _ticket(784, 2, 2, "plugin-dependency-resolver", "Add plugin dependency resolution",
            "Handle plugin interdependencies at install time.",
            ["Build dependency graph from manifests", "Topological sort for install order", "Test: dependent plugin installed after dependency"],
            "utils/plugins/dependencyResolver.ts", "plugin-skill-ecosystem"),
    _ticket(785, 1, 2, "mcp-to-skill-bridge", "Bridge MCP servers to skill-like prompts",
            "MCP servers should be able to provide skill-like prompt templates.",
            ["Register MCP skill builders from MCP server tools", "Break import cycles with write-once registry", "Test: MCP server provides discoverable skill"],
            "skills/mcpSkillBuilders.ts", "plugin-skill-ecosystem"),
    _ticket(786, 2, 2, "bundled-skill-extraction", "Support bundled skill extraction to disk",
            "Skills extracted securely with O_WRONLY|O_CREAT|O_EXCL|O_NOFOLLOW.",
            ["Extract bundled skills to .bernstein/skills/ on first use", "Secure file write with exclusive create", "Test: extracted skill file has 0o600 permissions"],
            "skills/bundledSkills.ts", "plugin-skill-ecosystem"),
    _ticket(787, 2, 1, "skill-dedup-by-realpath", "Deduplicate skills by realpath",
            "Prevent loading the same skill from multiple paths.",
            ["Use realpath for skill identity comparison", "Skip duplicate skills from different source paths", "Test: symlinked skill loaded once"],
            "skills/loadSkillsDir.ts", "plugin-skill-ecosystem"),
    _ticket(788, 1, 1, "skill-token-estimation", "Estimate skill frontmatter token usage",
            "Budget skill injection against context window.",
            ["Count tokens in skill frontmatter + content", "Cap total skill tokens in context", "Test: oversized skill collection trimmed to budget"],
            "skills/loadSkillsDir.ts", "plugin-skill-ecosystem"),
    _ticket(789, 2, 3, "skill-ui-grouped-by-source", "Group skills by source in UI",
            "Display skills organized by where they came from.",
            ["Group: managed, user, project, plugin, MCP", "Show source indicator for each skill", "Test: skills grouped correctly in status output"],
            "components/skills/SkillsMenu.tsx", "plugin-skill-ecosystem"),
    _ticket(790, 3, 2, "skill-fork-execution", "Support fork execution mode for skills",
            "Skills with context='fork' should run as separate agent.",
            ["Detect fork mode in skill frontmatter", "Run skill as forked agent with isolated context", "Test: forked skill runs in separate agent process"],
            "tools/SkillTool/", "plugin-skill-ecosystem"),
    _ticket(791, 3, 3, "plugin-migration-path", "Create migration path from built-in to plugin",
            "Built-in features should be migratable to plugins.",
            ["Create createMovedToPluginFeature() helper", "Show redirect message when old feature used", "Test: moved feature redirects to plugin"],
            "commands/security-review.ts", "plugin-skill-ecosystem"),
    _ticket(792, 2, 1, "skill-arg-substitution", "Support argument substitution in skill prompts",
            "Replace CLAUDE_SKILL_DIR, CLAUDE_SESSION_ID in skill templates.",
            ["Define substitution variables and their sources", "Replace variables at skill load time", "Test: CLAUDE_SKILL_DIR replaced with actual path"],
            "skills/loadSkillsDir.ts", "plugin-skill-ecosystem"),
    _ticket(793, 3, 2, "plugin-reconciliation", "Reconcile marketplace state on startup",
            "Align installed plugin state with declared marketplace intent.",
            ["Diff marketplace declarations vs installed state", "Install missing, update outdated, remove orphaned", "Test: startup reconciliation fixes drift"],
            "utils/plugins/reconciler.ts", "plugin-skill-ecosystem"),
    _ticket(794, 1, 2, "plugin-scoped-naming", "Namespace plugin-provided servers to prevent collisions",
            "Plugin-scoped naming for MCP/LSP servers.",
            ["Prefix server names with plugin name", "Prevent naming collisions across plugins", "Test: two plugins with same server name don't conflict"],
            "services/lsp/config.ts", "plugin-skill-ecosystem"),
    _ticket(795, 2, 2, "skill-change-detection", "Watch skill directories for changes",
            "Detect skill modifications and trigger reload.",
            ["Watch .bernstein/skills/ and .claude/skills/ directories", "Debounced reload on file change", "Test: modified skill content picked up automatically"],
            "utils/skills/skillChangeDetector.ts", "plugin-skill-ecosystem"),
    _ticket(796, 3, 1, "plugin-error-reporting", "Surface plugin loading errors clearly",
            "Plugin errors should be visible in doctor and status.",
            ["Collect PluginError[] during loading", "Display in bernstein doctor and bernstein status", "Test: broken plugin shows error in doctor"],
            "commands/plugin/PluginErrors.tsx", "plugin-skill-ecosystem"),
    _ticket(797, 0, 2, "skill-discovery-priority", "Implement skill discovery priority order",
            "Skills discovered from managed\u2192user\u2192project\u2192additional\u2192plugin\u2192MCP.",
            ["Define 6-level discovery priority", "Later sources don't override earlier ones", "Test: managed skill wins over user skill with same name"],
            "skills/loadSkillsDir.ts", "plugin-skill-ecosystem"),
    _ticket(798, 2, 1, "skill-safe-properties-autoallow", "Auto-allow skills with only safe properties",
            "Skills that only read shouldn't require permission.",
            ["Define safe skill properties (read-only, no shell)", "Auto-allow skills matching safe profile", "Test: read-only skill executes without prompt"],
            "tools/SkillTool/", "plugin-skill-ecosystem"),
    _ticket(799, 3, 2, "plugin-autoupdate", "Add plugin auto-update logic",
            "Check for and apply plugin updates automatically.",
            ["Check marketplace for newer versions on startup", "Apply updates in background", "Test: outdated plugin updated on next start"],
            "utils/plugins/pluginAutoupdate.ts", "plugin-skill-ecosystem"),
    _ticket(800, 1, 2, "builtin-plugin-registry", "Create built-in plugin registry",
            "Register built-in features as toggleable plugins.",
            ["Create BUILTIN_PLUGINS map with definitions", "Support enable/disable via settings", "Test: built-in plugin disabled via settings"],
            "plugins/builtinPlugins.ts", "plugin-skill-ecosystem"),

    # ── Pillar 7: Performance & Native (25 tickets) ──
    _ticket(801, 0, 1, "api-preconnect-pool-warming", "Fire-and-forget API connection pool warming",
            "HEAD request to warm connection pool before first API call.",
            ["Add preconnect() at bootstrap after config load", "10s timeout, idempotent, skip local/proxy providers", "Test: preconnect fires during startup"],
            "utils/apiPreconnect.ts", "performance-native"),
    _ticket(802, 0, 1, "query-guard-concurrency", "Add generation-counted concurrency guard",
            "Prevent overlapping orchestrator ticks.",
            ["Create QueryGuard with idle/dispatching/running states", "Generation counter invalidates stale callbacks", "Test: concurrent tick attempts blocked"],
            "utils/QueryGuard.ts", "performance-native"),
    _ticket(803, 0, 2, "file-type-token-estimation", "File-type-aware token estimation",
            "JSON at 2 bytes/token, code at 4 bytes/token.",
            ["Add bytes_per_token_for_file_type() helper", "Apply in token_monitor.py estimates", "Test: JSON files estimate more tokens per byte"],
            "services/tokenEstimation.ts", "performance-native"),
    _ticket(804, 1, 2, "cascading-token-count", "Cascading token count strategy",
            "API\u2192cheap model\u2192rough estimation fallback chain.",
            ["Try API token counting first", "Fall back to cheap model counting", "Final fallback to bytes/4 estimation"],
            "services/tokenEstimation.ts", "performance-native"),
    _ticket(805, 0, 2, "vcr-fixture-dehydration", "VCR fixture pattern with dehydration/hydration",
            "Deterministic test fixtures with environment placeholder substitution.",
            ["Replace CWD, UUIDs, timestamps with __CWD__ etc.", "Reverse on replay (hydration)", "Track hypothetical cost on replay"],
            "services/vcr.ts", "performance-native"),
    _ticket(806, 1, 2, "vcr-streaming-fixtures", "Streaming API response fixtures",
            "Save and replay streaming LLM responses for tests.",
            ["Capture streaming chunks as fixture data", "Replay as async generator", "Test: streaming fixture produces identical output"],
            "services/vcr.ts", "performance-native"),
    _ticket(807, 1, 3, "fuzzy-file-indexing", "Implement fuzzy file path matching with bitmap rejection",
            "O(1) candidate rejection plus scored fuzzy matching.",
            ["Bitmap-based char existence check", "Scoring: boundary=8, camel=6, consecutive=4, test=-5%", "Async loading yielding every 4ms"],
            "native-ts/file-index/index.ts", "performance-native"),
    _ticket(808, 2, 2, "lazy-import-expensive-modules", "Lazy-load expensive dependencies",
            "Defer loading of heavy modules until first use.",
            ["Identify modules >1MB import cost", "Wrap with lazy_import() pattern", "Test: startup time reduced by deferring heavy imports"],
            "native-ts/color-diff/index.ts", "performance-native"),
    _ticket(809, 2, 2, "cooperative-scheduling-file-ops", "Yield to event loop during long file operations",
            "Prevent UI blocking during file discovery.",
            ["Add yield every ~4ms during directory scans", "Use asyncio.sleep(0) for cooperative scheduling", "Test: TUI responsive during large directory scan"],
            "native-ts/file-index/index.ts", "performance-native"),
    _ticket(810, 2, 1, "dirty-flag-layout-caching", "Add dirty-flag caching for layout calculations",
            "Skip layout recalculation when nothing changed.",
            ["Track dirty flag per component", "Skip layout if not dirty", "Test: unchanged components skip layout pass"],
            "native-ts/yoga-layout/index.ts", "performance-native"),
    _ticket(811, 1, 2, "prompt-cache-prefix-stability", "Ensure byte-identical prompt prefixes for cache hits",
            "Agent prompts should maintain stable prefixes for cache efficiency.",
            ["Identify and stabilize prefix components", "Track prefix changes and log breaks", "Test: consecutive spawns achieve cache hit"],
            "utils/forkedAgent.ts", "performance-native"),
    _ticket(812, 2, 2, "token-budget-management", "Implement token budget management per agent",
            "Track and enforce token budgets throughout agent lifecycle.",
            ["Create TokenBudget with initial, used, remaining", "Enforce limits before API calls", "Test: agent stopped when budget exhausted"],
            "services/tokenEstimation.ts", "performance-native"),
    _ticket(813, 2, 1, "cost-on-fixture-replay", "Track hypothetical costs when replaying fixtures",
            "Budget testing should still account for costs.",
            ["On VCR replay, calculate what cost would have been", "Add to session cost tracker", "Test: replay fixture contributes to cost metrics"],
            "services/vcr.ts", "performance-native"),
    _ticket(814, 3, 2, "word-level-diff-rendering", "Implement word-level diff with syntax highlighting",
            "Color-diff with word-level granularity and theme support.",
            ["Tokenize + word-diff for inline changes", "Support Monokai and ANSI themes", "Test: word-level changes highlighted correctly"],
            "native-ts/color-diff/index.ts", "performance-native"),
    _ticket(815, 3, 1, "truecolor-mode-detection", "Auto-detect terminal color mode",
            "Detect truecolor/256-color/ANSI for optimal rendering.",
            ["Probe terminal capabilities", "Fall back gracefully to lower modes", "Test: correct mode detected in CI environment"],
            "native-ts/color-diff/index.ts", "performance-native"),
    _ticket(816, 2, 3, "zero-dep-analytics-queue", "Implement zero-dependency analytics with queue-and-drain",
            "Queue metrics pre-initialization, drain asynchronously.",
            ["No imports in metrics init module", "Queue events until sink attached", "Drain queued events asynchronously post-init"],
            "services/analytics/index.ts", "performance-native"),
    _ticket(817, 1, 2, "type-safe-sensitive-data", "Type-level guards for sensitive data in metrics",
            "Prevent accidental PII logging via type system.",
            ["Create SensitiveData marker type", "Require explicit cast to log sensitive fields", "Strip PII-tagged fields before general storage"],
            "services/analytics/index.ts", "performance-native"),
    _ticket(818, 2, 2, "autocompact-reactive-fallback", "Implement reactive compaction as 413 fallback",
            "When prompt-too-long hits, auto-compact and retry.",
            ["Catch 413 or equivalent error", "Trigger compaction pipeline", "Retry with compacted context"],
            "services/compact/compact.ts", "performance-native"),
    _ticket(819, 3, 2, "image-stripping-before-compact", "Strip images before compaction summarization",
            "Replace image/document blocks with text markers before summarizing.",
            ["Replace image content with [image] marker", "Strip re-injected attachments", "Test: compaction prompt contains no image data"],
            "services/compact/compact.ts", "performance-native"),
    _ticket(820, 3, 1, "ptl-retry-exponential-truncation", "Exponential truncation on prompt-too-long retry",
            "When compact request itself hits PTL, truncate oldest 50% and retry.",
            ["Truncate oldest API-round groups", "Max 3 attempts", "Test: PTL recovered after 2 truncation rounds"],
            "services/compact/compact.ts", "performance-native"),
    _ticket(821, 0, 1, "per-agent-token-progress", "Track per-agent token usage in real-time",
            "Additive output tokens, latest input tokens per agent.",
            ["Create AgentTokenTracker per spawned agent", "Update on each API response", "Display in bernstein status per-agent"],
            "tasks/LocalAgentTask/LocalAgentTask.tsx", "performance-native"),
    _ticket(822, 2, 1, "keepalive-during-compaction", "Send keepalive signals during long compaction",
            "Prevent idle timeout during compaction.",
            ["Send heartbeat every 30s during compaction", "Resume normal flow after completion", "Test: long compaction doesn't timeout"],
            "services/compact/compact.ts", "performance-native"),
    _ticket(823, 1, 3, "repo-index-fuzzy-search", "Enhance repo index with fuzzy search scoring",
            "Apply fuzzy match scoring to file discovery results.",
            ["Integrate fuzzy scoring from file-index algorithm", "Boundary, camelCase, consecutive bonuses", "Test: better results for partial file name matches"],
            "native-ts/file-index/index.ts", "performance-native"),
    _ticket(824, 3, 3, "syntax-highlight-diffs-tui", "Add syntax-highlighted diffs to TUI",
            "Color-coded diffs with language detection.",
            ["Integrate highlight.js-style tokenization", "Apply diff markers with color", "Test: Python diff shows correct syntax colors"],
            "native-ts/color-diff/index.ts", "performance-native"),
    _ticket(825, 2, 1, "fixture-auto-discovery", "Auto-discover test fixture directory",
            "Automatic __fixtures__ directory resolution for test files.",
            ["Use call stack to find test file path", "Resolve __fixtures__/ relative to test file", "Test: fixture directory found automatically"],
            "services/vcr.ts", "performance-native"),

    # ── Pillar 8: Future Bets (25 tickets) ──
    _ticket(826, 4, 3, "voice-mode-architecture", "Design voice input mode architecture",
            "Platform capability probing with native\u2192fallback chains.",
            ["Design VoiceProvider with platform detection", "Support native audio, SoX, arecord fallbacks", "Create design doc with API surface"],
            "voice/", "future-bets"),
    _ticket(827, 4, 2, "voice-keyterm-enrichment", "Design project-specific vocabulary enrichment",
            "Extract project terms for better STT accuracy.",
            ["Extract terms from file names, git branches, imports", "CamelCase/snake_case splitting", "Cap at 50 terms"],
            "services/voiceKeyterms.ts", "future-bets"),
    _ticket(828, 4, 3, "companion-agent-system", "Design companion agent with persistent personality",
            "Deterministic generation seeded by user ID.",
            ["Design CompanionBones (deterministic) + CompanionSoul (editable)", "Seeded PRNG for reproducible traits", "Create design doc for agent personality system"],
            "buddy/", "future-bets"),
    _ticket(829, 4, 2, "session-teleportation", "Design session teleportation across environments",
            "Move execution between local, cloud, and desktop.",
            ["Design teleport protocol with session bundling", "Git bundle upload for code state transfer", "Create design doc for cross-environment resume"],
            "utils/teleport/", "future-bets"),
    _ticket(830, 4, 4, "automated-bug-hunting", "Design continuous automated bug hunting",
            "Background agent that hunts for bugs in codebase.",
            ["Design bughunter pipeline: scan \u2192 analyze \u2192 report", "Priority-ranked finding output", "Create design doc for continuous audit"],
            "commands/bughunter/", "future-bets"),
    _ticket(831, 4, 2, "context-visualization", "Design context window visualization tool",
            "Visual representation of what's in the context window.",
            ["Design context breakdown display", "Show per-category token usage", "Create mockup for context map UI"],
            "commands/ctx_viz/", "future-bets"),
    _ticket(832, 4, 4, "speculative-execution-crdt", "Design speculative execution with CRDT conflict resolution",
            "Run multiple execution paths, merge via CRDTs.",
            ["Research CRDT applicability to code changes", "Design speculation state machine", "Create design doc for speculative execution"],
            "state/AppState.tsx", "future-bets"),
    _ticket(833, 4, 1, "computer-use-mcp-design", "Document computer use MCP integration pattern",
            "Browser automation via MCP server.",
            ["Document MCP protocol for computer use", "Define coordinate modes and action types", "Create design doc for browser automation"],
            "utils/computerUse/", "future-bets"),
    _ticket(834, 3, 4, "signed-task-envelopes", "Implement signed task envelopes for cross-tenant agents",
            "Ed25519 signed canonical JSON for task integrity.",
            ["Port Ed25519 signing from ATP", "Canonical JSON serialization", "Verify signature on task receipt"],
            "agent-task-protocol (external)", "future-bets"),
    _ticket(835, 3, 4, "execution-fingerprinting", "Implement execution fingerprinting for regression gates",
            "SHA-256 fingerprint over intent sequence for determinism.",
            ["Hash task sequence at execution boundaries", "Compare fingerprints across runs", "Alert on fingerprint drift"],
            "intentusnet (external)", "future-bets"),
    _ticket(836, 3, 3, "convergence-monitoring", "Implement convergence monitoring for orchestration",
            "Synchronization metrics as preconditions for merge/spawn.",
            ["Define convergence criteria: pending merges, error rate, active agents", "Block operations when not converged", "Test: spawn blocked during high error rate"],
            "bio-adapt (external)", "future-bets"),
    _ticket(837, 3, 2, "crdt-shared-metrics", "Design CRDT-backed shared metrics store",
            "Convergent global view of metrics without central server.",
            ["Research CRDT types for metrics (counters, sets)", "Design distributed metrics protocol", "Create design doc for P2P metrics"],
            "agi (external)", "future-bets"),
    _ticket(838, 3, 3, "capability-based-mcp-discovery", "Implement capability-based MCP server discovery",
            "Health-aware routing with heartbeat re-resolution.",
            ["Add capability declarations to MCP registry", "Health-based re-resolution on heartbeat failure", "Test: unhealthy MCP server de-prioritized"],
            "mcp-mesh (external)", "future-bets"),
    _ticket(839, 4, 2, "synergy-layer-agent-groups", "Design synergy layer for agent tool sharing",
            "Named middle layer for shared tools and objectives.",
            ["Design Synergy abstraction for agent groups", "Tool inheritance from synergy to agents", "Create design doc for synergy-based orchestration"],
            "enzu-go (external)", "future-bets"),
    _ticket(840, 3, 2, "delivery-guarantee-semantics", "Add delivery guarantee semantics to bulletin board",
            "AT_MOST_ONCE, AT_LEAST_ONCE, EXACTLY_ONCE message delivery.",
            ["Define DeliveryGuarantee enum", "AT_LEAST_ONCE: persist + acknowledge", "Test: unacknowledged message redelivered"],
            "Neuron (external)", "future-bets"),
    _ticket(841, 4, 1, "good-agent-reward-loop", "Design positive feedback/reward loop for agents",
            "Track and reward high-performing agents.",
            ["Define agent performance metrics", "Create reward signal in agent prompts", "Design doc for agent motivation system"],
            "commands/good-claude/", "future-bets"),
    _ticket(842, 4, 2, "sticker-gamification", "Design gamification layer for development teams",
            "Achievement/sticker system for team productivity.",
            ["Define achievement categories", "Create milestone tracking", "Design doc for gamification system"],
            "commands/stickers/", "future-bets"),
    _ticket(843, 3, 2, "cron-from-agent-context", "Implement agent-scheduled periodic tasks",
            "Agents can create cron-like scheduled tasks.",
            ["5-field cron expression parser", "Recurring and one-shot modes", "Max 50 jobs per session", "Durable mode: persist to .sdd/"],
            "tools/ScheduleCronTool/", "future-bets"),
    _ticket(844, 3, 3, "agent-triggers-event-driven", "Design event-driven agent triggering",
            "Agents triggered by file changes, webhooks, schedules.",
            ["Design trigger evaluation pipeline", "Support: file watch, webhook, cron, manual", "Integrate with trigger_manager.py"],
            "skills/bundled/loop.ts", "future-bets"),
    _ticket(845, 4, 2, "chrome-extension-mcp", "Design Chrome extension MCP integration",
            "Browser automation via Chrome Native Messaging.",
            ["Document Chrome NM protocol requirements", "Design MCP server wrapper for Chrome", "Create design doc for browser agent integration"],
            "utils/claudeInChrome/", "future-bets"),
    _ticket(846, 4, 2, "mobile-agent-interface", "Design mobile agent interaction",
            "QR code and mobile app integration.",
            ["Design mobile notification pipeline", "Session handoff from CLI to mobile", "Create design doc for mobile UX"],
            "commands/mobile/", "future-bets"),
    _ticket(847, 3, 2, "multi-pass-execution", "Design multi-pass execution pipeline",
            "Multiple analysis passes over the same codebase.",
            ["Define pass types: surface, deep, synthesis", "Each pass builds on previous pass output", "Create design doc for multi-pass architecture"],
            "commands/passes/", "future-bets"),
    _ticket(848, 3, 1, "extra-usage-provisioning", "Design extra usage provisioning",
            "Handle rate limit overage with user approval.",
            ["Design overage detection and user notification", "Approval flow for extended usage", "Create design doc for budget extension"],
            "commands/extra-usage/", "future-bets"),
    _ticket(849, 4, 4, "p2p-agent-network", "Design P2P agent network protocol",
            "Decentralized agent coordination via libp2p-style networking.",
            ["Research P2P protocols for agent communication", "Design gossip-based state propagation", "Create design doc for decentralized orchestration"],
            "agi (external)", "future-bets"),
    _ticket(850, 4, 4, "dream-cross-project-synthesis", "Design cross-project knowledge synthesis",
            "Dream consolidation across multiple projects.",
            ["Design cross-project memory merge protocol", "Privacy-preserving knowledge extraction", "Create design doc for multi-project learning"],
            "services/autoDream/autoDream.ts", "future-bets"),
]


PRIORITY_OVERRIDES: dict[int, int] = {
    659: 3, 660: 3, 671: 3, 694: 3,       # p0→p3 (4 tickets)
    689: 4, 711: 4,                         # p0→p4 (2 tickets)
    699: 4, 721: 4, 682: 4,                 # p1→p4 (3 tickets)
}

COMPLEXITY_OVERRIDES: dict[int, int] = {
    # c1→c0 (1 ticket)
    675: 0,
    # c2→c0 (19 tickets)
    661: 0, 664: 0, 674: 0, 686: 0, 690: 0,
    707: 0, 709: 0, 710: 0, 712: 0, 732: 0,
    742: 0, 757: 0, 766: 0, 771: 0, 783: 0,
    786: 0, 808: 0, 809: 0, 812: 0,
    # c2→c3 (12 tickets)
    655: 3, 666: 3, 677: 3, 684: 3, 693: 3, 728: 3,
    735: 3, 752: 3, 765: 3, 795: 3, 806: 3, 818: 3,
    # c2→c4 (14 tickets)
    651: 4, 653: 4, 657: 4, 676: 4, 679: 4, 680: 4,
    685: 4, 703: 4, 718: 4, 729: 4, 746: 4, 761: 4,
    777: 4, 797: 4,
}


def _apply_overrides(tickets: list[dict]) -> None:
    for t in tickets:
        tid = t["tid"]
        if tid in PRIORITY_OVERRIDES:
            t["priority"] = PRIORITY_OVERRIDES[tid]
        if tid in COMPLEXITY_OVERRIDES:
            t["complexity"] = COMPLEXITY_OVERRIDES[tid]


def _render_yaml(t: dict) -> str:
    p = t["priority"]
    c = t["complexity"]
    clabel = COMPLEXITY_LABEL[c]
    minutes = COMPLEXITY_MINUTES[c]
    scope = SCOPE_MAP[c]
    role = PILLAR_ROLE[t["pillar"]]
    pillar_tag = PILLAR_TAG[t["pillar"]]

    criteria_lines = "\n".join(f"- [ ] {cr}" for cr in t["criteria"])

    return f"""---
id: "T{t['tid']}"
title: "{t['title']}"
status: open
type: feature
priority: {p}
scope: {scope}
complexity: {clabel}
role: {role}
model: auto
effort: normal
estimated_minutes: {minutes}
depends_on: []
blocks: []
tags: ["{pillar_tag}", "claude-code-compat"]
janitor_signals: []
context_files: []
affected_paths: []
max_tokens: null
require_review: false
require_human_approval: false
---

## Summary
{t['summary']}

## Objective & Definition of Done
{criteria_lines}

## Claude Code Reference
- Source: `cloned/claude-code/{t['source_ref']}`

## Verification
- All acceptance criteria met and verified via automated tests or manual inspection
"""


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    _apply_overrides(TICKETS)

    created = 0
    priority_counts: dict[int, int] = {}
    complexity_counts: dict[int, int] = {}
    pillar_counts: dict[str, int] = {}

    for t in TICKETS:
        p = t["priority"]
        c = t["complexity"]
        fname = f"p{p}_c{c}_030426_feat_{t['kebab']}.yaml"
        path = OUTPUT_DIR / fname

        content = _render_yaml(t)
        path.write_text(content)
        created += 1

        priority_counts[p] = priority_counts.get(p, 0) + 1
        complexity_counts[c] = complexity_counts.get(c, 0) + 1
        pillar_counts[t["pillar"]] = pillar_counts.get(t["pillar"], 0) + 1

    print(f"\n{'='*60}")
    print(f"  Generated {created} ticket files")
    print(f"  Output: {OUTPUT_DIR}")
    print(f"{'='*60}")

    print("\n  Priority distribution:")
    for p in sorted(priority_counts):
        print(f"    p{p}: {priority_counts[p]} tickets")

    print("\n  Complexity distribution:")
    for c in sorted(complexity_counts):
        print(f"    c{c} ({COMPLEXITY_LABEL[c]}): {complexity_counts[c]} tickets")

    print("\n  Pillar distribution:")
    for pillar in sorted(pillar_counts):
        print(f"    {pillar}: {pillar_counts[pillar]} tickets")

    print(f"\n  ID range: T{TICKETS[0]['tid']} \u2013 T{TICKETS[-1]['tid']}")
    print()


if __name__ == "__main__":
    main()
