"""Adapter conformance canary matrix (issue #2368).

Upstream CLI churn lands on users when nothing exercises adapter contracts
continuously: version-floor advisories (see :mod:`advisories`) warn about
known-old versions but cannot catch a fresh upstream release breaking an
adapter contract. The canary closes that gap: a nightly run probes every
primary adapter against whatever upstream version is installed and turns
each probe into a receipt, so adapter breakage becomes our finding instead
of a user's broken unattended run.

Design invariants:

* **Each probe result is a content-addressed receipt.** The receipt's
  canonical JSON bytes hash to its identity; two runs that observed the
  same upstream surface at the same timestamp produce byte-identical
  receipts, and a mutated receipt fails verification exactly like a
  tampered chain entry. Receipts are mirrored into the HMAC audit chain
  via :func:`bernstein.core.security.audit_chain.record_adapter_canary_receipt`.
* **The last-green table is a projection of passing receipts.** Every row
  carries the receipt hash that attested it; the docs table and the
  doctor advisory both read the same projection, never a hand-maintained
  list.
* **Issue automation is threshold-gated and deduped.** One upstream flake
  never opens an issue (two consecutive failures required), and the same
  failure fingerprint never opens two.

The nightly workflow (``.github/workflows/adapter-conformance-canary.yml``)
drives :func:`run_matrix` through ``scripts/adapter_canary.py``.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

logger = logging.getLogger(__name__)

__all__ = [
    "CANARY_GOAL",
    "CANARY_MATRIX",
    "CANARY_SCHEMA_VERSION",
    "FAILURE_ISSUE_THRESHOLD",
    "LAST_GREEN_BEGIN",
    "LAST_GREEN_DOC_PATH",
    "LAST_GREEN_END",
    "LAST_GREEN_JSON_PATH",
    "LAST_GREEN_STALE_DAYS",
    "SKIP_ISSUE_THRESHOLD",
    "CanaryOutcome",
    "CanaryTarget",
    "LastGreenEntry",
    "MatrixRunResult",
    "apply_canary_outcome",
    "build_canary_receipt",
    "canary_issue_body",
    "canary_issue_title",
    "canary_skip_issue_body",
    "canary_skip_issue_title",
    "failure_fingerprint",
    "last_green_is_stale",
    "load_canary_state",
    "load_last_green",
    "probe_binary_version",
    "receipt_sha256",
    "render_last_green_table",
    "run_canary_target",
    "run_matrix",
    "save_canary_state",
    "save_last_green",
    "skip_fingerprint",
    "update_last_green",
    "verify_canary_receipt",
    "write_canary_receipt",
]

#: Version stamped into every receipt preimage. Bump only on a wire-format
#: change.
CANARY_SCHEMA_VERSION = 1

#: The one pinned tiny goal every canary run uses. Fixed so run-to-run
#: diffs isolate upstream drift, tiny so daily spend stays bounded.
CANARY_GOAL = "Reply with exactly the word BERNSTEIN-CANARY and stop."

#: Consecutive failures required before the canary proposes an issue.
#: One upstream flake or a transient install problem never pages anyone.
FAILURE_ISSUE_THRESHOLD = 2

#: Consecutive same-reason skips required before the canary proposes a
#: skip-tracking issue. A degraded (``skip``) probe is not a conformance
#: break, but an adapter that skips for the same reason night after night
#: is silently unverified -- the blind spot the canary exists to close. The
#: threshold is higher than :data:`FAILURE_ISSUE_THRESHOLD`: a skip is a
#: weaker signal than a confirmed drift, so it must persist longer before it
#: is worth an operator's attention.
SKIP_ISSUE_THRESHOLD = 3

#: A last-green row older than this many days is flagged stale. The canary
#: refreshes passing rows nightly, so a row that has not moved in this long
#: is no longer evidence the installed surface still conforms.
LAST_GREEN_STALE_DAYS = 7

#: Markers delimiting the generated last-green table inside the docs page.
LAST_GREEN_BEGIN = "<!-- last-green:begin -->"
LAST_GREEN_END = "<!-- last-green:end -->"

#: Packaged last-green projection, regenerated by the nightly canary and
#: shipped in the wheel so ``bernstein doctor`` can read it offline.
LAST_GREEN_JSON_PATH = Path(__file__).parent / "last_green.json"

#: Docs page carrying the rendered last-green table (dev checkout path).
LAST_GREEN_DOC_PATH = Path(__file__).parents[3] / "docs" / "adapters" / "conformance-canary.md"

_ADAPTER_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
#: First dotted-numeric token in a ``--version`` blob. Possessive quantifiers
#: plus the digit-run anchor keep the scan linear on untrusted subprocess
#: output; see the matching constant in ``adapters/security_floor.py``.
_VERSION_TOKEN_RE = re.compile(r"(?<!\d)\d++(?:\.\d++){1,3}")
_VERSION_TIMEOUT_SECONDS = 10


@dataclass(frozen=True)
class CanaryTarget:
    """One row of the canary matrix.

    Attributes:
        adapter: Adapter registry key (also the contract name).
        binary: Binary probed on ``PATH``.
        model: Cheapest usable model for this adapter; pinned so spend
            stays bounded and run-to-run diffs isolate upstream drift.
        goal: The pinned tiny goal; identical across the matrix.
    """

    adapter: str
    binary: str
    model: str
    goal: str = CANARY_GOAL


#: Primary agent CLIs exercised nightly, alphabetical by adapter so the
#: enumeration (and therefore the receipt sequence) is deterministic.
#: Models are the cheapest usable tier per adapter.
CANARY_MATRIX: tuple[CanaryTarget, ...] = (
    # agy exposes no model flag (selection is server-side); "default"
    # records that the probe runs whatever the service serves by default.
    CanaryTarget(adapter="agy", binary="agy", model="default"),
    CanaryTarget(adapter="aider", binary="aider", model="gpt-5-mini"),
    CanaryTarget(adapter="claude", binary="claude", model="haiku"),
    CanaryTarget(adapter="codex", binary="codex", model="gpt-5-mini"),
    CanaryTarget(adapter="copilot", binary="copilot", model="auto"),
    CanaryTarget(adapter="gemini", binary="gemini", model="gemini-3.1-flash-lite"),
    CanaryTarget(adapter="opencode", binary="opencode", model="haiku"),
    CanaryTarget(adapter="qwen", binary="qwen", model="qwen3-coder-flash"),
)


@dataclass(frozen=True)
class CanaryOutcome:
    """Result of probing one canary target.

    Attributes:
        adapter: Adapter registry key.
        binary: Binary name probed.
        model: Model pinned for the probe.
        goal: The pinned goal text.
        installed_version: Parsed ``--version`` token, or ``None``.
        verdict: ``"pass"`` / ``"fail"`` / ``"skip"`` / ``"refuse"``. A
            ``refuse`` verdict marks a below-security-floor version the canary
            declines to certify (see :data:`refused_below_floor`); it never
            enters the last-green projection and is not an upstream-regression
            signal.
        failures: Conformance failure lines (empty unless ``fail`` /
            ``refuse``).
        transcript: Human-readable probe transcript; rides into the
            regression issue so the finding is reproducible from the
            issue alone.
        security_floor: The adapter's minimum-safe floor when tracked, else
            ``None``. Recorded so the last-green guard can reject a below-floor
            version regardless of the conformance verdict.
        refused_below_floor: Whether this outcome is a below-floor refusal.
        skip_reason: Stable, path-independent reason for a ``skip`` verdict
            (``None`` for every other verdict). It is the dedupe key for the
            skip-streak escalation (:func:`skip_fingerprint`): the same
            degraded reason repeating night after night fingerprints
            identically, so a chronic skip escalates exactly once. It is
            deliberately *not* folded into the receipt preimage
            (:func:`build_canary_receipt`) -- the human-readable reason
            already rides in ``transcript`` -- so adding it does not perturb
            any receipt hash.
    """

    adapter: str
    binary: str
    model: str
    goal: str
    installed_version: str | None
    verdict: str
    failures: tuple[str, ...] = ()
    transcript: tuple[str, ...] = ()
    security_floor: str | None = None
    refused_below_floor: bool = False
    skip_reason: str | None = None


@dataclass(frozen=True)
class LastGreenEntry:
    """One adapter's newest conformance-verified upstream version.

    Attributes:
        adapter: Adapter registry key.
        binary: Binary the version was probed from.
        version: Newest version that passed the canary.
        receipt_sha256: Content hash of the passing receipt that attested
            this row; the table is a projection of receipts, so every row
            is independently checkable against its receipt file.
        recorded_at: Timestamp the attesting canary run stamped.
    """

    adapter: str
    binary: str
    version: str
    receipt_sha256: str
    recorded_at: str


@dataclass
class MatrixRunResult:
    """Aggregated result of one canary matrix run.

    Attributes:
        outcomes: Per-target outcomes in matrix order.
        regressions: Adapter names whose verdict was ``fail``.
        refusals: Adapter names refused for a below-security-floor version
            (#2515). Distinct from ``regressions``: a refusal is an
            operator-environment issue, not an upstream conformance break.
        issues_to_open: Threshold-crossing, deduped issue payloads
            (``{"title": ..., "body": ...}``) the workflow should open.
        receipt_paths: Receipt files written this run.
    """

    outcomes: list[CanaryOutcome] = field(default_factory=list)
    regressions: list[str] = field(default_factory=list)
    refusals: list[str] = field(default_factory=list)
    issues_to_open: list[dict[str, str]] = field(default_factory=list)
    receipt_paths: list[Path] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Canonical JSON helpers
# ---------------------------------------------------------------------------


def _canonical_bytes(data: dict[str, Any]) -> bytes:
    return json.dumps(data, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8")


def _sha256_hex(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


# ---------------------------------------------------------------------------
# Probing
# ---------------------------------------------------------------------------


def probe_binary_version(binary_path: str) -> str | None:
    """Return the first dotted-numeric token from ``<binary> --version``.

    Best-effort: any launch failure, timeout, or unparseable output yields
    ``None`` (reported as unknown rather than fabricating a verdict).
    """
    try:
        proc = subprocess.run(
            [binary_path, "--version"],
            capture_output=True,
            text=True,
            timeout=_VERSION_TIMEOUT_SECONDS,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        # Log the exception type only: --version output on agent CLIs can
        # echo credential-adjacent environment fragments.
        logger.debug("canary: version probe failed for %s (%s)", binary_path, type(exc).__name__)
        return None
    blob = f"{proc.stdout}\n{proc.stderr}"
    match = _VERSION_TOKEN_RE.search(blob)
    return match.group(0) if match else None


def run_canary_target(
    target: CanaryTarget,
    *,
    which: Callable[[str], str | None] | None = None,
    contracts_dir: Path | None = None,
) -> CanaryOutcome:
    """Probe one canary target: version capture plus conformance verdict.

    The conformance verdict reuses the in-process contract check that
    ``bernstein adapters check`` runs (:func:`bernstein.adapters.report.
    check_adapter_in_process`): the installed binary's ``--help`` surface
    is matched against the adapter's declared contract. Any missing
    required flag or subcommand is a ``fail`` -- exactly the drift shape
    a fresh upstream release ships.

    Args:
        target: The matrix row to probe.
        which: ``shutil.which``-shaped resolver; tests inject stubs.
        contracts_dir: Contract fixture override for tests.

    Returns:
        A populated :class:`CanaryOutcome`.
    """
    resolver = which if which is not None else shutil.which
    transcript: list[str] = [f"target: adapter={target.adapter} binary={target.binary} model={target.model}"]

    binary_resolved = resolver(target.binary)
    if binary_resolved is None:
        transcript.append(f"{target.binary}: not on PATH")
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=None,
            verdict="skip",
            transcript=tuple(transcript),
            skip_reason="binary not on PATH",
        )

    # Record which file was actually probed. A shadowed or wrong binary on
    # PATH produces an inconclusive skip that is indistinguishable from real
    # drift unless the resolved path is in the receipt (#2842).
    transcript.append(f"{target.binary} resolved: {binary_resolved}")

    installed_version = probe_binary_version(binary_resolved)
    transcript.append(f"{target.binary} --version: {installed_version or 'unknown'}")

    # Security floor gate (#2515): a below-floor upstream version is never
    # certified, regardless of its --help conformance. We refuse before the
    # conformance probe so a known-unsafe binary is not exercised at all, and
    # the refusal receipt (built from this outcome) references the advisory.
    from bernstein.adapters.advisories import check_adapter_version

    floor_hit = check_adapter_version(target.adapter, installed_version)
    if floor_hit is not None:
        transcript.append(
            f"security floor: {installed_version} below {floor_hit.min_safe_version} "
            f"[{floor_hit.advisory_id}]: refusing certification"
        )
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=installed_version,
            verdict="refuse",
            failures=(
                f"{installed_version} below security floor {floor_hit.min_safe_version} "
                f"[{floor_hit.advisory_id}]: {floor_hit.note}",
            ),
            transcript=tuple(transcript),
            security_floor=floor_hit.min_safe_version,
            refused_below_floor=True,
        )

    from bernstein.adapters.report import check_adapter_in_process

    payload = check_adapter_in_process(
        target.adapter,
        binary_resolved=binary_resolved,
        contracts_dir=contracts_dir,
    )
    verdict = str(payload.verdict)
    detail = str(payload.detail or "")
    transcript.append(f"conformance: {verdict}" + (f" ({detail})" if detail else ""))

    if verdict == "fail":
        failures = tuple(part.strip() for part in detail.split(";") if part.strip())
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=installed_version,
            verdict="fail",
            failures=failures,
            transcript=tuple(transcript),
        )
    if verdict == "ok":
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=installed_version,
            verdict="pass",
            transcript=tuple(transcript),
        )
    # The skip reason is the report detail when present (e.g. "probe
    # inconclusive (...)", "no contract", "binary missing"). It is stable for
    # a given adapter on a given host, so the same degraded surface repeating
    # across nights fingerprints identically and the streak escalates exactly
    # once. The resolved path stays out of the reason (it rides in the
    # transcript for forensics) so the dedupe key does not churn on paths.
    return CanaryOutcome(
        adapter=target.adapter,
        binary=target.binary,
        model=target.model,
        goal=target.goal,
        installed_version=installed_version,
        verdict="skip",
        transcript=tuple(transcript),
        skip_reason=detail or "conformance skip",
    )


# ---------------------------------------------------------------------------
# Receipts
# ---------------------------------------------------------------------------


def build_canary_receipt(outcome: CanaryOutcome, *, generated_at: str) -> dict[str, Any]:
    """Bind an outcome into a canonical receipt mapping.

    Determinism: the receipt is a pure function of the outcome and the
    caller-supplied timestamp, so two runs that observed the same upstream
    surface at the same timestamp produce byte-identical receipts (and
    therefore the same :func:`receipt_sha256` identity).
    """
    return {
        "schema_version": CANARY_SCHEMA_VERSION,
        "kind": "adapter.canary_receipt",
        "adapter": outcome.adapter,
        "binary": outcome.binary,
        "model": outcome.model,
        "goal": outcome.goal,
        "installed_version": outcome.installed_version,
        "verdict": outcome.verdict,
        "failures": list(outcome.failures),
        "transcript": list(outcome.transcript),
        "generated_at": generated_at,
    }


def receipt_sha256(receipt: dict[str, Any]) -> str:
    """Content hash (identity) of a receipt's canonical bytes."""
    return _sha256_hex(_canonical_bytes(receipt))


def verify_canary_receipt(doc: dict[str, Any]) -> bool:
    """Check a written receipt document against its embedded content hash.

    A mutated receipt body no longer hashes to the recorded identity, so
    tampering is detected offline with no key material required (the HMAC
    audit chain mirror additionally binds the hash into the chain).
    """
    receipt = doc.get("receipt")
    recorded = doc.get("receipt_sha256")
    if not isinstance(receipt, dict) or not isinstance(recorded, str):
        return False
    return receipt_sha256(receipt) == recorded


def write_canary_receipt(base_dir: Path, receipt: dict[str, Any]) -> Path:
    """Write a receipt to ``base_dir`` under its content-addressed name.

    The filename embeds the adapter name and the receipt hash prefix. The
    adapter component is validated against a strict allow-pattern and the
    final path is resolved and containment-checked against the resolved
    base directory, so a hostile adapter string can never escape the
    receipts directory.

    Raises:
        ValueError: If the adapter name fails validation or the resolved
            path escapes ``base_dir``.
    """
    adapter = str(receipt.get("adapter") or "")
    if not _ADAPTER_NAME_RE.match(adapter):
        raise ValueError(f"invalid adapter name for receipt filename: {adapter!r}")
    sha = receipt_sha256(receipt)
    base_dir.mkdir(parents=True, exist_ok=True)
    resolved_base = base_dir.resolve()
    candidate = (resolved_base / f"{adapter}-{sha[:16]}.json").resolve()
    if not candidate.is_relative_to(resolved_base):
        raise ValueError("receipt path escapes the receipts directory")
    doc = {"receipt": receipt, "receipt_sha256": sha}
    tmp = candidate.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(candidate)
    return candidate


# ---------------------------------------------------------------------------
# Failure threshold + issue dedupe
# ---------------------------------------------------------------------------


def failure_fingerprint(outcome: CanaryOutcome) -> str:
    """Stable dedupe key for one failure shape.

    Depends on the adapter, the installed version, and the failure lines:
    the same regression never opens two issues, while a new upstream
    version failing differently (or the same way) fingerprints fresh.
    """
    return _sha256_hex(
        _canonical_bytes(
            {
                "adapter": outcome.adapter,
                "installed_version": outcome.installed_version,
                "failures": list(outcome.failures),
            }
        )
    )


def skip_fingerprint(outcome: CanaryOutcome) -> str:
    """Stable dedupe key for one degraded-skip shape.

    Depends on the adapter and the skip reason (not the version or any
    resolved path): the same degraded reason repeating night after night
    fingerprints identically, so a chronic skip escalates exactly once,
    while a different degradation restarts the streak and reports afresh.
    """
    return _sha256_hex(
        _canonical_bytes(
            {
                "adapter": outcome.adapter,
                "skip_reason": outcome.skip_reason or "",
            }
        )
    )


def apply_canary_outcome(
    state: dict[str, dict[str, Any]],
    outcome: CanaryOutcome,
) -> tuple[dict[str, dict[str, Any]], bool]:
    """Fold one outcome into the canary state; decide whether to report.

    State shape (per adapter): ``{"consecutive_failures": int,
    "last_fingerprint": str, "reported_fingerprint": str,
    "consecutive_skips": int, "last_skip_fingerprint": str,
    "reported_skip_fingerprint": str}``.

    Rules:

    * ``pass`` resets both the failure and the skip counters and clears
      every fingerprint: a green run is positive evidence that supersedes
      any prior degraded or failing streak.
    * ``refuse`` (#2515) leaves the state untouched: a below-floor version
      is an operator-environment issue, not an upstream signal.
    * ``fail`` counts consecutively *per failure fingerprint*: a failure
      that fingerprints differently from the previous one restarts the
      count at 1, so a churning upstream must fail the same way twice in a
      row before anything is reported. Reporting triggers only when the
      counter reaches :data:`FAILURE_ISSUE_THRESHOLD` AND this fingerprint
      has not been reported yet.
    * ``skip`` counts consecutively *per skip fingerprint*, mirroring the
      failure path on its own counter and threshold
      (:data:`SKIP_ISSUE_THRESHOLD`): a degraded probe that repeats for the
      same reason becomes visible instead of being silently voided, while a
      one-off skip never pages anyone. The skip counters are independent of
      the failure counters, so a skip never perturbs the failure path (and
      vice versa).

    Returns:
        ``(new_state, should_open_issue)``. The input mapping is not
        mutated. ``should_open_issue`` is set for both a threshold-crossing
        fail and a threshold-crossing skip; the caller distinguishes them by
        ``outcome.verdict`` to pick the issue title/body.
    """
    new_state = {name: entry.copy() for name, entry in state.items()}
    if outcome.verdict == "refuse":
        # A below-floor version is an operator-environment issue, not an
        # upstream regression, so it never counts toward any threshold. The
        # refusal is still sealed as a receipt by ``run_matrix``.
        return new_state, False

    entry = new_state.setdefault(
        outcome.adapter,
        {
            "consecutive_failures": 0,
            "last_fingerprint": "",
            "reported_fingerprint": "",
            "consecutive_skips": 0,
            "last_skip_fingerprint": "",
            "reported_skip_fingerprint": "",
        },
    )
    if outcome.verdict == "pass":
        entry["consecutive_failures"] = 0
        entry["last_fingerprint"] = ""
        entry["reported_fingerprint"] = ""
        entry["consecutive_skips"] = 0
        entry["last_skip_fingerprint"] = ""
        entry["reported_skip_fingerprint"] = ""
        return new_state, False

    if outcome.verdict == "skip":
        fingerprint = skip_fingerprint(outcome)
        if entry.get("last_skip_fingerprint") == fingerprint:
            entry["consecutive_skips"] = int(entry.get("consecutive_skips", 0)) + 1
        else:
            entry["consecutive_skips"] = 1
            entry["last_skip_fingerprint"] = fingerprint
        should_open = (
            entry["consecutive_skips"] >= SKIP_ISSUE_THRESHOLD and entry.get("reported_skip_fingerprint") != fingerprint
        )
        if should_open:
            entry["reported_skip_fingerprint"] = fingerprint
        return new_state, should_open

    fingerprint = failure_fingerprint(outcome)
    if entry.get("last_fingerprint") == fingerprint:
        entry["consecutive_failures"] = int(entry.get("consecutive_failures", 0)) + 1
    else:
        entry["consecutive_failures"] = 1
        entry["last_fingerprint"] = fingerprint
    should_open = (
        entry["consecutive_failures"] >= FAILURE_ISSUE_THRESHOLD and entry.get("reported_fingerprint") != fingerprint
    )
    if should_open:
        entry["reported_fingerprint"] = fingerprint
    return new_state, should_open


def load_canary_state(path: Path) -> dict[str, dict[str, Any]]:
    """Load the persisted canary state; missing or malformed means empty."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    adapters = raw.get("adapters") if isinstance(raw, dict) else None
    if not isinstance(adapters, dict):
        return {}
    return {str(name): dict(entry) for name, entry in adapters.items() if isinstance(entry, dict)}


def save_canary_state(path: Path, state: dict[str, dict[str, Any]]) -> None:
    """Persist the canary state atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {"schema_version": CANARY_SCHEMA_VERSION, "adapters": state}
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def canary_issue_title(outcome: CanaryOutcome) -> str:
    """Deterministic title for a canary regression issue."""
    version = outcome.installed_version or "unknown version"
    return f"Adapter conformance canary regression: {outcome.adapter} {version}"


def canary_issue_body(outcome: CanaryOutcome, *, receipt_sha: str) -> str:
    """Issue body carrying the failing conformance transcript.

    Includes the receipt hash so the finding is anchored to a verifiable
    artifact, and the transcript so the regression is reproducible from
    the issue alone.
    """
    lines = [
        f"The nightly adapter conformance canary found `{outcome.adapter}` "
        f"({outcome.installed_version or 'unknown version'}) failing its adapter contract "
        f"on {FAILURE_ISSUE_THRESHOLD} consecutive runs.",
        "",
        "## Conformance failures",
        "",
    ]
    lines.extend(f"- {failure}" for failure in outcome.failures)
    lines.extend(["", "## Probe transcript", "", "```"])
    lines.extend(outcome.transcript)
    lines.extend(
        [
            "```",
            "",
            f"Receipt: `sha256:{receipt_sha}` (canary run artifact; verify with "
            "`bernstein.adapters.canary.verify_canary_receipt`).",
            "",
            "Last-green reference: docs/adapters/conformance-canary.md.",
        ]
    )
    return "\n".join(lines)


def canary_skip_issue_title(outcome: CanaryOutcome) -> str:
    """Deterministic title for a chronic-skip tracking issue.

    Distinct from :func:`canary_issue_title` -- it says "skip", never
    "regression" -- so a degraded probe is never conflated with a confirmed
    drift. The workflow's title-based dedupe keeps one open issue per
    adapter skip streak.
    """
    return f"Adapter conformance canary skip streak: {outcome.adapter}"


def canary_skip_issue_body(outcome: CanaryOutcome, *, receipt_sha: str) -> str:
    """Issue body for a chronic skip: the degraded reason plus transcript.

    A ``skip`` is not a confirmed conformance break; it is a probe that
    could not decide (an uninstalled binary, a broken or wholesale-redesigned
    ``--help``, a shadowed binary on ``PATH``). A skip that repeats for the
    same reason past :data:`SKIP_ISSUE_THRESHOLD` nights means the adapter is
    silently unverified and needs an operator to investigate -- which the
    transcript (carrying the resolved binary path) makes reproducible.
    """
    lines = [
        f"The nightly adapter conformance canary has recorded `{outcome.adapter}` "
        f"({outcome.installed_version or 'unknown version'}) as a degraded `skip` for "
        f"the same reason on {SKIP_ISSUE_THRESHOLD} consecutive runs, so it is "
        "currently unverified rather than confirmed-passing.",
        "",
        "This is not a confirmed conformance regression. A chronic skip usually "
        "means an uninstalled binary, a broken or wholesale-redesigned `--help`, "
        "or a shadowed/wrong binary on `PATH`. Investigate using the transcript "
        "below; the last-green table will not advance until a green run.",
        "",
        "## Skip reason",
        "",
        f"- {outcome.skip_reason or 'unknown'}",
        "",
        "## Probe transcript",
        "",
        "```",
    ]
    lines.extend(outcome.transcript)
    lines.extend(
        [
            "```",
            "",
            f"Receipt: `sha256:{receipt_sha}` (canary run artifact; verify with "
            "`bernstein.adapters.canary.verify_canary_receipt`).",
            "",
            "Last-green reference: docs/adapters/conformance-canary.md.",
        ]
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Last-green projection
# ---------------------------------------------------------------------------


def load_last_green(path: Path | None = None) -> dict[str, LastGreenEntry]:
    """Load the last-green projection (packaged file by default)."""
    source = path if path is not None else LAST_GREEN_JSON_PATH
    try:
        raw = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    adapters = raw.get("adapters") if isinstance(raw, dict) else None
    if not isinstance(adapters, dict):
        return {}
    entries: dict[str, LastGreenEntry] = {}
    for name, entry in adapters.items():
        if not isinstance(entry, dict):
            continue
        try:
            entries[str(name)] = LastGreenEntry(
                adapter=str(name),
                binary=str(entry["binary"]),
                version=str(entry["version"]),
                receipt_sha256=str(entry["receipt_sha256"]),
                recorded_at=str(entry["recorded_at"]),
            )
        except KeyError:
            continue
    return entries


def update_last_green(
    entries: dict[str, LastGreenEntry],
    outcome: CanaryOutcome,
    *,
    receipt_sha: str,
    recorded_at: str,
) -> dict[str, LastGreenEntry]:
    """Fold a passing outcome into the last-green projection.

    Only a ``pass`` verdict with a known version updates the projection;
    failures, skips, and below-floor refusals never touch it, so the table
    always names the newest version a receipt actually attested.

    A below-floor version can never enter the projection even if a caller
    somehow presents it as a ``pass`` (#2515): the last-green table is the
    input to the doctor advisory and the ``bernstein doctor`` version-posture
    surface, so a below-floor row there would silently bless a known-unsafe
    version. The guard is a pure function of the advisory floor map, so the
    property "no last-green row references a below-floor version" holds by
    construction.

    Returns:
        A new mapping; the input is not mutated.
    """
    new_entries = entries.copy()
    if outcome.verdict != "pass" or not outcome.installed_version:
        return new_entries

    from bernstein.adapters.advisories import check_adapter_version

    if check_adapter_version(outcome.adapter, outcome.installed_version) is not None:
        # Below its security floor: refuse to advance last-green onto it.
        return new_entries
    new_entries[outcome.adapter] = LastGreenEntry(
        adapter=outcome.adapter,
        binary=outcome.binary,
        version=outcome.installed_version,
        receipt_sha256=receipt_sha,
        recorded_at=recorded_at,
    )
    return new_entries


def save_last_green(path: Path, entries: dict[str, LastGreenEntry]) -> None:
    """Persist the last-green projection atomically, sorted by adapter."""
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "schema_version": CANARY_SCHEMA_VERSION,
        "adapters": {
            name: {
                "binary": entry.binary,
                "version": entry.version,
                "receipt_sha256": entry.receipt_sha256,
                "recorded_at": entry.recorded_at,
            }
            for name, entry in sorted(entries.items())
        },
    }
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def _parse_recorded_at(value: str) -> datetime | None:
    """Parse a last-green ``recorded_at`` stamp, tolerating a trailing ``Z``.

    Returns ``None`` for an unparseable value (treated as stale by callers:
    a timestamp that cannot be read cannot be proven fresh).
    """
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed if parsed.tzinfo is not None else parsed.replace(tzinfo=UTC)


def last_green_is_stale(
    recorded_at: str,
    *,
    now: datetime,
    max_age_days: int = LAST_GREEN_STALE_DAYS,
) -> bool:
    """Return whether a last-green row is older than ``max_age_days``.

    Time is injected (``now``) so the decision is deterministic and testable;
    the canary passes its run timestamp and the doctor passes ``datetime.now``.
    An unparseable ``recorded_at`` is treated as stale (fail-visible).
    """
    recorded = _parse_recorded_at(recorded_at)
    if recorded is None:
        return True
    return (now - recorded).days > max_age_days


def render_last_green_table(entries: dict[str, LastGreenEntry], *, now: datetime | None = None) -> str:
    """Render the per-adapter last-green table as Markdown.

    Rows sort by adapter name so regeneration is deterministic; each row
    names the receipt hash prefix that attested it. A row whose
    ``recorded_at`` is older than :data:`LAST_GREEN_STALE_DAYS` (as of
    ``now``) is annotated ``(stale)`` so a frozen row stops reading as
    automation-fresh. ``now`` is injected for deterministic tests and set to
    the run timestamp by the canary; it defaults to the current UTC time.
    """
    current = now if now is not None else datetime.now(UTC)
    lines = [
        "| Adapter | Binary | Last-green version | Verified | Receipt |",
        "|---|---|---|---|---|",
    ]
    if not entries:
        lines.append("| _none yet_ | - | - | - | - |")
    for name in sorted(entries):
        entry = entries[name]
        verified = entry.recorded_at
        if last_green_is_stale(entry.recorded_at, now=current):
            verified = f"{entry.recorded_at} (stale)"
        lines.append(
            f"| {entry.adapter} | `{entry.binary}` | {entry.version} | {verified} | `{entry.receipt_sha256[:12]}` |"
        )
    return "\n".join(lines)


def write_last_green_doc(doc_path: Path, entries: dict[str, LastGreenEntry], *, now: datetime | None = None) -> None:
    """Regenerate the last-green table between the doc's markers.

    Idempotent for a fixed ``now``: regenerating with the same entries and
    timestamp leaves the file byte-identical. Content outside the markers is
    preserved verbatim. ``now`` is threaded into the staleness annotation so
    the regenerated table is a deterministic function of ``(entries, now)``.

    Raises:
        ValueError: If the doc is missing either marker.
    """
    text = doc_path.read_text(encoding="utf-8")
    begin = text.find(LAST_GREEN_BEGIN)
    end = text.find(LAST_GREEN_END)
    if -1 in (begin, end) or end < begin:
        raise ValueError(f"{doc_path} is missing the last-green table markers")
    head = text[: begin + len(LAST_GREEN_BEGIN)]
    tail = text[end:]
    table = render_last_green_table(entries, now=now)
    doc_path.write_text(f"{head}\n{table}\n{tail}", encoding="utf-8")


# ---------------------------------------------------------------------------
# Matrix runner
# ---------------------------------------------------------------------------


def run_matrix(
    targets: tuple[CanaryTarget, ...],
    *,
    receipts_dir: Path,
    state_path: Path,
    last_green_path: Path,
    docs_path: Path | None,
    generated_at: str,
    which: Callable[[str], str | None] | None = None,
    contracts_dir: Path | None = None,
    audit_chain: Any | None = None,
) -> MatrixRunResult:
    """Run the canary matrix end to end (the nightly workflow's core).

    For every target: probe, seal a receipt, fold the outcome into the
    failure-threshold state, and update the last-green projection on a
    pass. When ``docs_path`` is given the last-green table in that doc is
    regenerated. When ``audit_chain`` (an ``AuditChainStore``) is given,
    each receipt hash is mirrored into the HMAC audit chain.

    Returns:
        A :class:`MatrixRunResult` with outcomes, regressions, receipt
        paths, and the threshold-crossing deduped issue payloads.
    """
    result = MatrixRunResult()
    state = load_canary_state(state_path)
    last_green = load_last_green(last_green_path)

    for target in targets:
        outcome = run_canary_target(target, which=which, contracts_dir=contracts_dir)
        result.outcomes.append(outcome)

        receipt = build_canary_receipt(outcome, generated_at=generated_at)
        sha = receipt_sha256(receipt)
        result.receipt_paths.append(write_canary_receipt(receipts_dir, receipt))

        if audit_chain is not None:
            from bernstein.core.security.audit_chain import record_adapter_canary_receipt

            record_adapter_canary_receipt(
                chain=audit_chain,
                adapter=outcome.adapter,
                binary=outcome.binary,
                installed_version=outcome.installed_version,
                verdict=outcome.verdict,
                receipt_sha256=sha,
                failures=list(outcome.failures),
            )

        state, should_open = apply_canary_outcome(state, outcome)
        if outcome.verdict == "fail":
            result.regressions.append(outcome.adapter)
        if outcome.refused_below_floor:
            result.refusals.append(outcome.adapter)
        if should_open:
            # A threshold-crossing skip and a threshold-crossing fail are both
            # reported here; the verdict picks the distinctly-labeled payload so
            # a degraded probe is never conflated with a confirmed drift.
            if outcome.verdict == "skip":
                result.issues_to_open.append(
                    {
                        "title": canary_skip_issue_title(outcome),
                        "body": canary_skip_issue_body(outcome, receipt_sha=sha),
                    }
                )
            else:
                result.issues_to_open.append(
                    {
                        "title": canary_issue_title(outcome),
                        "body": canary_issue_body(outcome, receipt_sha=sha),
                    }
                )
        last_green = update_last_green(last_green, outcome, receipt_sha=sha, recorded_at=generated_at)

    save_canary_state(state_path, state)
    save_last_green(last_green_path, last_green)
    if docs_path is not None:
        # Evaluate staleness as-of the run timestamp so the regenerated table
        # is a deterministic function of the run inputs.
        write_last_green_doc(docs_path, last_green, now=_parse_recorded_at(generated_at))
    return result
