"""Adapter conformance canary matrix (issue #2368).

Upstream CLI churn lands on users when nothing exercises adapter contracts
continuously: version-floor advisories (see :mod:`advisories`) warn about
known-old versions but cannot catch a fresh upstream release breaking an
adapter contract. The canary closes that gap: a nightly run probes every
primary adapter against whatever upstream version is installed and turns
each probe into a receipt, so adapter breakage becomes our finding instead
of a user's broken unattended run.

Design invariants:

* **Each probe result is a content-addressed receipt.** The receipt's
  canonical JSON bytes hash to its identity; two runs that observed the
  same upstream surface at the same timestamp produce byte-identical
  receipts, and a mutated receipt fails verification exactly like a
  tampered chain entry. Receipts are mirrored into the HMAC audit chain
  via :func:`bernstein.core.security.audit_chain.record_adapter_canary_receipt`.
* **The last-green table is a projection of passing receipts.** Every row
  carries the receipt hash that attested it; the docs table and the
  doctor advisory both read the same projection, never a hand-maintained
  list.
* **Issue automation is threshold-gated and deduped.** One upstream flake
  never opens an issue (two consecutive failures required), and the same
  failure fingerprint never opens two.

The nightly workflow (``.github/workflows/adapter-conformance-canary.yml``)
drives :func:`run_matrix` through ``scripts/adapter_canary.py``.
"""

from __future__ import annotations

import hashlib
import json
import logging
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from collections.abc import Callable

logger = logging.getLogger(__name__)

__all__ = [
    "CANARY_GOAL",
    "CANARY_MATRIX",
    "CANARY_SCHEMA_VERSION",
    "FAILURE_ISSUE_THRESHOLD",
    "LAST_GREEN_BEGIN",
    "LAST_GREEN_DOC_PATH",
    "LAST_GREEN_END",
    "LAST_GREEN_JSON_PATH",
    "CanaryOutcome",
    "CanaryTarget",
    "LastGreenEntry",
    "MatrixRunResult",
    "apply_canary_outcome",
    "build_canary_receipt",
    "canary_issue_body",
    "canary_issue_title",
    "failure_fingerprint",
    "load_canary_state",
    "load_last_green",
    "probe_binary_version",
    "receipt_sha256",
    "render_last_green_table",
    "run_canary_target",
    "run_matrix",
    "save_canary_state",
    "save_last_green",
    "update_last_green",
    "verify_canary_receipt",
    "write_canary_receipt",
]

#: Version stamped into every receipt preimage. Bump only on a wire-format
#: change.
CANARY_SCHEMA_VERSION = 1

#: The one pinned tiny goal every canary run uses. Fixed so run-to-run
#: diffs isolate upstream drift, tiny so daily spend stays bounded.
CANARY_GOAL = "Reply with exactly the word BERNSTEIN-CANARY and stop."

#: Consecutive failures required before the canary proposes an issue.
#: One upstream flake or a transient install problem never pages anyone.
FAILURE_ISSUE_THRESHOLD = 2

#: Markers delimiting the generated last-green table inside the docs page.
LAST_GREEN_BEGIN = "<!-- last-green:begin -->"
LAST_GREEN_END = "<!-- last-green:end -->"

#: Packaged last-green projection, regenerated by the nightly canary and
#: shipped in the wheel so ``bernstein doctor`` can read it offline.
LAST_GREEN_JSON_PATH = Path(__file__).parent / "last_green.json"

#: Docs page carrying the rendered last-green table (dev checkout path).
LAST_GREEN_DOC_PATH = Path(__file__).parents[3] / "docs" / "adapters" / "conformance-canary.md"

_ADAPTER_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9_-]*$")
_VERSION_TOKEN_RE = re.compile(r"\d+(?:\.\d+){1,3}")
_VERSION_TIMEOUT_SECONDS = 10


@dataclass(frozen=True)
class CanaryTarget:
    """One row of the canary matrix.

    Attributes:
        adapter: Adapter registry key (also the contract name).
        binary: Binary probed on ``PATH``.
        model: Cheapest usable model for this adapter; pinned so spend
            stays bounded and run-to-run diffs isolate upstream drift.
        goal: The pinned tiny goal; identical across the matrix.
    """

    adapter: str
    binary: str
    model: str
    goal: str = CANARY_GOAL


#: Primary agent CLIs exercised nightly, alphabetical by adapter so the
#: enumeration (and therefore the receipt sequence) is deterministic.
#: Models are the cheapest usable tier per adapter.
CANARY_MATRIX: tuple[CanaryTarget, ...] = (
    # agy exposes no model flag (selection is server-side); "default"
    # records that the probe runs whatever the service serves by default.
    CanaryTarget(adapter="agy", binary="agy", model="default"),
    CanaryTarget(adapter="aider", binary="aider", model="gpt-5-mini"),
    CanaryTarget(adapter="claude", binary="claude", model="haiku"),
    CanaryTarget(adapter="codex", binary="codex", model="gpt-5-mini"),
    CanaryTarget(adapter="copilot", binary="copilot", model="auto"),
    CanaryTarget(adapter="gemini", binary="gemini", model="gemini-3.1-flash-lite"),
    CanaryTarget(adapter="opencode", binary="opencode", model="haiku"),
    CanaryTarget(adapter="qwen", binary="qwen", model="qwen3-coder-flash"),
)


@dataclass(frozen=True)
class CanaryOutcome:
    """Result of probing one canary target.

    Attributes:
        adapter: Adapter registry key.
        binary: Binary name probed.
        model: Model pinned for the probe.
        goal: The pinned goal text.
        installed_version: Parsed ``--version`` token, or ``None``.
        verdict: ``"pass"`` / ``"fail"`` / ``"skip"``.
        failures: Conformance failure lines (empty unless ``fail``).
        transcript: Human-readable probe transcript; rides into the
            regression issue so the finding is reproducible from the
            issue alone.
    """

    adapter: str
    binary: str
    model: str
    goal: str
    installed_version: str | None
    verdict: str
    failures: tuple[str, ...] = ()
    transcript: tuple[str, ...] = ()


@dataclass(frozen=True)
class LastGreenEntry:
    """One adapter's newest conformance-verified upstream version.

    Attributes:
        adapter: Adapter registry key.
        binary: Binary the version was probed from.
        version: Newest version that passed the canary.
        receipt_sha256: Content hash of the passing receipt that attested
            this row; the table is a projection of receipts, so every row
            is independently checkable against its receipt file.
        recorded_at: Timestamp the attesting canary run stamped.
    """

    adapter: str
    binary: str
    version: str
    receipt_sha256: str
    recorded_at: str


@dataclass
class MatrixRunResult:
    """Aggregated result of one canary matrix run.

    Attributes:
        outcomes: Per-target outcomes in matrix order.
        regressions: Adapter names whose verdict was ``fail``.
        issues_to_open: Threshold-crossing, deduped issue payloads
            (``{"title": ..., "body": ...}``) the workflow should open.
        receipt_paths: Receipt files written this run.
    """

    outcomes: list[CanaryOutcome] = field(default_factory=list)
    regressions: list[str] = field(default_factory=list)
    issues_to_open: list[dict[str, str]] = field(default_factory=list)
    receipt_paths: list[Path] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Canonical JSON helpers
# ---------------------------------------------------------------------------


def _canonical_bytes(data: dict[str, Any]) -> bytes:
    return json.dumps(data, ensure_ascii=False, separators=(",", ":"), sort_keys=True).encode("utf-8")


def _sha256_hex(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


# ---------------------------------------------------------------------------
# Probing
# ---------------------------------------------------------------------------


def probe_binary_version(binary_path: str) -> str | None:
    """Return the first dotted-numeric token from ``<binary> --version``.

    Best-effort: any launch failure, timeout, or unparseable output yields
    ``None`` (reported as unknown rather than fabricating a verdict).
    """
    try:
        proc = subprocess.run(
            [binary_path, "--version"],
            capture_output=True,
            text=True,
            timeout=_VERSION_TIMEOUT_SECONDS,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        # Log the exception type only: --version output on agent CLIs can
        # echo credential-adjacent environment fragments.
        logger.debug("canary: version probe failed for %s (%s)", binary_path, type(exc).__name__)
        return None
    blob = f"{proc.stdout}\n{proc.stderr}"
    match = _VERSION_TOKEN_RE.search(blob)
    return match.group(0) if match else None


def run_canary_target(
    target: CanaryTarget,
    *,
    which: Callable[[str], str | None] | None = None,
    contracts_dir: Path | None = None,
) -> CanaryOutcome:
    """Probe one canary target: version capture plus conformance verdict.

    The conformance verdict reuses the in-process contract check that
    ``bernstein adapters check`` runs (:func:`bernstein.adapters.report.
    check_adapter_in_process`): the installed binary's ``--help`` surface
    is matched against the adapter's declared contract. Any missing
    required flag or subcommand is a ``fail`` -- exactly the drift shape
    a fresh upstream release ships.

    Args:
        target: The matrix row to probe.
        which: ``shutil.which``-shaped resolver; tests inject stubs.
        contracts_dir: Contract fixture override for tests.

    Returns:
        A populated :class:`CanaryOutcome`.
    """
    resolver = which if which is not None else shutil.which
    transcript: list[str] = [f"target: adapter={target.adapter} binary={target.binary} model={target.model}"]

    binary_resolved = resolver(target.binary)
    if binary_resolved is None:
        transcript.append(f"{target.binary}: not on PATH")
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=None,
            verdict="skip",
            transcript=tuple(transcript),
        )

    installed_version = probe_binary_version(binary_resolved)
    transcript.append(f"{target.binary} --version: {installed_version or 'unknown'}")

    from bernstein.adapters.report import check_adapter_in_process

    payload = check_adapter_in_process(
        target.adapter,
        binary_resolved=binary_resolved,
        contracts_dir=contracts_dir,
    )
    verdict = str(payload.verdict)
    detail = str(payload.detail or "")
    transcript.append(f"conformance: {verdict}" + (f" ({detail})" if detail else ""))

    if verdict == "fail":
        failures = tuple(part.strip() for part in detail.split(";") if part.strip())
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=installed_version,
            verdict="fail",
            failures=failures,
            transcript=tuple(transcript),
        )
    if verdict == "ok":
        return CanaryOutcome(
            adapter=target.adapter,
            binary=target.binary,
            model=target.model,
            goal=target.goal,
            installed_version=installed_version,
            verdict="pass",
            transcript=tuple(transcript),
        )
    return CanaryOutcome(
        adapter=target.adapter,
        binary=target.binary,
        model=target.model,
        goal=target.goal,
        installed_version=installed_version,
        verdict="skip",
        transcript=tuple(transcript),
    )


# ---------------------------------------------------------------------------
# Receipts
# ---------------------------------------------------------------------------


def build_canary_receipt(outcome: CanaryOutcome, *, generated_at: str) -> dict[str, Any]:
    """Bind an outcome into a canonical receipt mapping.

    Determinism: the receipt is a pure function of the outcome and the
    caller-supplied timestamp, so two runs that observed the same upstream
    surface at the same timestamp produce byte-identical receipts (and
    therefore the same :func:`receipt_sha256` identity).
    """
    return {
        "schema_version": CANARY_SCHEMA_VERSION,
        "kind": "adapter.canary_receipt",
        "adapter": outcome.adapter,
        "binary": outcome.binary,
        "model": outcome.model,
        "goal": outcome.goal,
        "installed_version": outcome.installed_version,
        "verdict": outcome.verdict,
        "failures": list(outcome.failures),
        "transcript": list(outcome.transcript),
        "generated_at": generated_at,
    }


def receipt_sha256(receipt: dict[str, Any]) -> str:
    """Content hash (identity) of a receipt's canonical bytes."""
    return _sha256_hex(_canonical_bytes(receipt))


def verify_canary_receipt(doc: dict[str, Any]) -> bool:
    """Check a written receipt document against its embedded content hash.

    A mutated receipt body no longer hashes to the recorded identity, so
    tampering is detected offline with no key material required (the HMAC
    audit chain mirror additionally binds the hash into the chain).
    """
    receipt = doc.get("receipt")
    recorded = doc.get("receipt_sha256")
    if not isinstance(receipt, dict) or not isinstance(recorded, str):
        return False
    return receipt_sha256(receipt) == recorded


def write_canary_receipt(base_dir: Path, receipt: dict[str, Any]) -> Path:
    """Write a receipt to ``base_dir`` under its content-addressed name.

    The filename embeds the adapter name and the receipt hash prefix. The
    adapter component is validated against a strict allow-pattern and the
    final path is resolved and containment-checked against the resolved
    base directory, so a hostile adapter string can never escape the
    receipts directory.

    Raises:
        ValueError: If the adapter name fails validation or the resolved
            path escapes ``base_dir``.
    """
    adapter = str(receipt.get("adapter") or "")
    if not _ADAPTER_NAME_RE.match(adapter):
        raise ValueError(f"invalid adapter name for receipt filename: {adapter!r}")
    sha = receipt_sha256(receipt)
    base_dir.mkdir(parents=True, exist_ok=True)
    resolved_base = base_dir.resolve()
    candidate = (resolved_base / f"{adapter}-{sha[:16]}.json").resolve()
    if not candidate.is_relative_to(resolved_base):
        raise ValueError("receipt path escapes the receipts directory")
    doc = {"receipt": receipt, "receipt_sha256": sha}
    tmp = candidate.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(candidate)
    return candidate


# ---------------------------------------------------------------------------
# Failure threshold + issue dedupe
# ---------------------------------------------------------------------------


def failure_fingerprint(outcome: CanaryOutcome) -> str:
    """Stable dedupe key for one failure shape.

    Depends on the adapter, the installed version, and the failure lines:
    the same regression never opens two issues, while a new upstream
    version failing differently (or the same way) fingerprints fresh.
    """
    return _sha256_hex(
        _canonical_bytes(
            {
                "adapter": outcome.adapter,
                "installed_version": outcome.installed_version,
                "failures": list(outcome.failures),
            }
        )
    )


def apply_canary_outcome(
    state: dict[str, dict[str, Any]],
    outcome: CanaryOutcome,
) -> tuple[dict[str, dict[str, Any]], bool]:
    """Fold one outcome into the canary state; decide whether to report.

    State shape (per adapter): ``{"consecutive_failures": int,
    "reported_fingerprint": str}``.

    State shape (per adapter): ``{"consecutive_failures": int,
    "last_fingerprint": str, "reported_fingerprint": str}``.

    Rules:

    * ``pass`` resets the failure counter and clears both fingerprints.
    * ``skip`` leaves the state untouched (an uninstalled binary is not
      evidence either way).
    * ``fail`` counts consecutively *per fingerprint*: a failure that
      fingerprints differently from the previous one restarts the count
      at 1, so a churning upstream must fail the same way twice in a row
      before anything is reported. Reporting triggers only when the
      counter reaches :data:`FAILURE_ISSUE_THRESHOLD` AND this
      fingerprint has not been reported yet.

    Returns:
        ``(new_state, should_open_issue)``. The input mapping is not
        mutated.
    """
    new_state = {name: dict(entry) for name, entry in state.items()}
    if outcome.verdict == "skip":
        return new_state, False

    entry = new_state.setdefault(
        outcome.adapter,
        {"consecutive_failures": 0, "last_fingerprint": "", "reported_fingerprint": ""},
    )
    if outcome.verdict == "pass":
        entry["consecutive_failures"] = 0
        entry["last_fingerprint"] = ""
        entry["reported_fingerprint"] = ""
        return new_state, False

    fingerprint = failure_fingerprint(outcome)
    if entry.get("last_fingerprint") == fingerprint:
        entry["consecutive_failures"] = int(entry.get("consecutive_failures", 0)) + 1
    else:
        entry["consecutive_failures"] = 1
        entry["last_fingerprint"] = fingerprint
    should_open = (
        entry["consecutive_failures"] >= FAILURE_ISSUE_THRESHOLD and entry.get("reported_fingerprint") != fingerprint
    )
    if should_open:
        entry["reported_fingerprint"] = fingerprint
    return new_state, should_open


def load_canary_state(path: Path) -> dict[str, dict[str, Any]]:
    """Load the persisted canary state; missing or malformed means empty."""
    try:
        raw = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    adapters = raw.get("adapters") if isinstance(raw, dict) else None
    if not isinstance(adapters, dict):
        return {}
    return {str(name): dict(entry) for name, entry in adapters.items() if isinstance(entry, dict)}


def save_canary_state(path: Path, state: dict[str, dict[str, Any]]) -> None:
    """Persist the canary state atomically."""
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {"schema_version": CANARY_SCHEMA_VERSION, "adapters": state}
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def canary_issue_title(outcome: CanaryOutcome) -> str:
    """Deterministic title for a canary regression issue."""
    version = outcome.installed_version or "unknown version"
    return f"Adapter conformance canary regression: {outcome.adapter} {version}"


def canary_issue_body(outcome: CanaryOutcome, *, receipt_sha: str) -> str:
    """Issue body carrying the failing conformance transcript.

    Includes the receipt hash so the finding is anchored to a verifiable
    artifact, and the transcript so the regression is reproducible from
    the issue alone.
    """
    lines = [
        f"The nightly adapter conformance canary found `{outcome.adapter}` "
        f"({outcome.installed_version or 'unknown version'}) failing its adapter contract "
        f"on {FAILURE_ISSUE_THRESHOLD} consecutive runs.",
        "",
        "## Conformance failures",
        "",
    ]
    lines.extend(f"- {failure}" for failure in outcome.failures)
    lines.extend(["", "## Probe transcript", "", "```"])
    lines.extend(outcome.transcript)
    lines.extend(
        [
            "```",
            "",
            f"Receipt: `sha256:{receipt_sha}` (canary run artifact; verify with "
            "`bernstein.adapters.canary.verify_canary_receipt`).",
            "",
            "Last-green reference: docs/adapters/conformance-canary.md.",
        ]
    )
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Last-green projection
# ---------------------------------------------------------------------------


def load_last_green(path: Path | None = None) -> dict[str, LastGreenEntry]:
    """Load the last-green projection (packaged file by default)."""
    source = path if path is not None else LAST_GREEN_JSON_PATH
    try:
        raw = json.loads(source.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    adapters = raw.get("adapters") if isinstance(raw, dict) else None
    if not isinstance(adapters, dict):
        return {}
    entries: dict[str, LastGreenEntry] = {}
    for name, entry in adapters.items():
        if not isinstance(entry, dict):
            continue
        try:
            entries[str(name)] = LastGreenEntry(
                adapter=str(name),
                binary=str(entry["binary"]),
                version=str(entry["version"]),
                receipt_sha256=str(entry["receipt_sha256"]),
                recorded_at=str(entry["recorded_at"]),
            )
        except KeyError:
            continue
    return entries


def update_last_green(
    entries: dict[str, LastGreenEntry],
    outcome: CanaryOutcome,
    *,
    receipt_sha: str,
    recorded_at: str,
) -> dict[str, LastGreenEntry]:
    """Fold a passing outcome into the last-green projection.

    Only a ``pass`` verdict with a known version updates the projection;
    failures and skips never touch it, so the table always names the
    newest version a receipt actually attested.

    Returns:
        A new mapping; the input is not mutated.
    """
    new_entries = dict(entries)
    if outcome.verdict != "pass" or not outcome.installed_version:
        return new_entries
    new_entries[outcome.adapter] = LastGreenEntry(
        adapter=outcome.adapter,
        binary=outcome.binary,
        version=outcome.installed_version,
        receipt_sha256=receipt_sha,
        recorded_at=recorded_at,
    )
    return new_entries


def save_last_green(path: Path, entries: dict[str, LastGreenEntry]) -> None:
    """Persist the last-green projection atomically, sorted by adapter."""
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "schema_version": CANARY_SCHEMA_VERSION,
        "adapters": {
            name: {
                "binary": entry.binary,
                "version": entry.version,
                "receipt_sha256": entry.receipt_sha256,
                "recorded_at": entry.recorded_at,
            }
            for name, entry in sorted(entries.items())
        },
    }
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(json.dumps(doc, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    tmp.replace(path)


def render_last_green_table(entries: dict[str, LastGreenEntry]) -> str:
    """Render the per-adapter last-green table as Markdown.

    Rows sort by adapter name so regeneration is deterministic; each row
    names the receipt hash prefix that attested it.
    """
    lines = [
        "| Adapter | Binary | Last-green version | Verified | Receipt |",
        "|---|---|---|---|---|",
    ]
    if not entries:
        lines.append("| _none yet_ | - | - | - | - |")
    for name in sorted(entries):
        entry = entries[name]
        lines.append(
            f"| {entry.adapter} | `{entry.binary}` | {entry.version} "
            f"| {entry.recorded_at} | `{entry.receipt_sha256[:12]}` |"
        )
    return "\n".join(lines)


def write_last_green_doc(doc_path: Path, entries: dict[str, LastGreenEntry]) -> None:
    """Regenerate the last-green table between the doc's markers.

    Idempotent: regenerating with the same entries leaves the file
    byte-identical. Content outside the markers is preserved verbatim.

    Raises:
        ValueError: If the doc is missing either marker.
    """
    text = doc_path.read_text(encoding="utf-8")
    begin = text.find(LAST_GREEN_BEGIN)
    end = text.find(LAST_GREEN_END)
    if begin == -1 or end == -1 or end < begin:
        raise ValueError(f"{doc_path} is missing the last-green table markers")
    head = text[: begin + len(LAST_GREEN_BEGIN)]
    tail = text[end:]
    table = render_last_green_table(entries)
    doc_path.write_text(f"{head}\n{table}\n{tail}", encoding="utf-8")


# ---------------------------------------------------------------------------
# Matrix runner
# ---------------------------------------------------------------------------


def run_matrix(
    targets: tuple[CanaryTarget, ...],
    *,
    receipts_dir: Path,
    state_path: Path,
    last_green_path: Path,
    docs_path: Path | None,
    generated_at: str,
    which: Callable[[str], str | None] | None = None,
    contracts_dir: Path | None = None,
    audit_chain: Any | None = None,
) -> MatrixRunResult:
    """Run the canary matrix end to end (the nightly workflow's core).

    For every target: probe, seal a receipt, fold the outcome into the
    failure-threshold state, and update the last-green projection on a
    pass. When ``docs_path`` is given the last-green table in that doc is
    regenerated. When ``audit_chain`` (an ``AuditChainStore``) is given,
    each receipt hash is mirrored into the HMAC audit chain.

    Returns:
        A :class:`MatrixRunResult` with outcomes, regressions, receipt
        paths, and the threshold-crossing deduped issue payloads.
    """
    result = MatrixRunResult()
    state = load_canary_state(state_path)
    last_green = load_last_green(last_green_path)

    for target in targets:
        outcome = run_canary_target(target, which=which, contracts_dir=contracts_dir)
        result.outcomes.append(outcome)

        receipt = build_canary_receipt(outcome, generated_at=generated_at)
        sha = receipt_sha256(receipt)
        result.receipt_paths.append(write_canary_receipt(receipts_dir, receipt))

        if audit_chain is not None:
            from bernstein.core.security.audit_chain import record_adapter_canary_receipt

            record_adapter_canary_receipt(
                chain=audit_chain,
                adapter=outcome.adapter,
                binary=outcome.binary,
                installed_version=outcome.installed_version,
                verdict=outcome.verdict,
                receipt_sha256=sha,
                failures=list(outcome.failures),
            )

        state, should_open = apply_canary_outcome(state, outcome)
        if outcome.verdict == "fail":
            result.regressions.append(outcome.adapter)
        if should_open:
            result.issues_to_open.append(
                {
                    "title": canary_issue_title(outcome),
                    "body": canary_issue_body(outcome, receipt_sha=sha),
                }
            )
        last_green = update_last_green(last_green, outcome, receipt_sha=sha, recorded_at=generated_at)

    save_canary_state(state_path, state)
    save_last_green(last_green_path, last_green)
    if docs_path is not None:
        write_last_green_doc(docs_path, last_green)
    return result
