"""Volunteer-workers substrate: opt-in project policy and its trust anchor.

A project joins the volunteer program by committing one file,
``.bernstein/volunteer.json``.  That file is the project's declared policy:
which gates a submission must pass, which paths a patch may touch, which
hosts the sandbox may reach, and how long a task may run.

Both artefacts here are content-addressed, and the digests chain:

    manifest bytes -> manifest digest -> sandbox profile digest -> receipt

A result receipt carries the manifest digest as ``manifest_sha256`` and the
profile digest as its sandbox identifier, so a maintainer verifying a
volunteer's submission can prove the volunteer ran *the policy this project
declared* behind *the containment that policy implies* -- without taking
anyone's word for either.
"""

from __future__ import annotations

from bernstein.core.volunteer.budget import (
    DEFAULT_BUDGET_CONFIG_PATH,
    DEFAULT_BUDGET_DIR,
    DEFAULT_LEDGER_PATH,
    LEDGER_SCHEMA_VERSION,
    BudgetClaimError,
    BudgetConfigError,
    BudgetLedger,
    BudgetLedgerError,
    BudgetLineItem,
    BudgetRemaining,
    BudgetReservation,
    ClaimRefusal,
    VolunteerBudget,
    budget_line_items,
    complete_claim,
    filter_local_profiles,
    load_budget_config,
    load_ledger,
    refuses_claim,
    remaining,
    remaining_wall_clock_minutes,
    reserve_claim,
    save_budget_config,
    save_ledger,
    with_budget_overrides,
)
from bernstein.core.volunteer.claim import (
    CLAIM_MARKER,
    DEFAULT_CLAIM_STALENESS,
    ClaimClient,
    ClaimComment,
    IssueClaimState,
    SkipDecision,
    SkipReason,
    find_own_claim,
    repo_slug,
    should_skip,
)
from bernstein.core.volunteer.clean_room import (
    CLEAN_ROOM_REFUSAL_REASONS,
    CLEAN_ROOM_VERIFY_PREDICATE_TYPE,
    CLEAN_ROOM_VERIFY_SCHEMA_VERSION,
    DEFAULT_CLEAN_ROOM_RECEIPT_PATH,
    REASON_BASE_COMMIT_UNAVAILABLE,
    REASON_BUNDLE_INVALID,
    REASON_MANIFEST_UNREADABLE,
    REASON_PATCH_CONFLICT,
    CleanRoomReceiptVerification,
    CleanRoomResult,
    CleanRoomVerificationReceipt,
    GateDivergence,
    build_clean_room_receipt,
    clean_room_receipt_from_result,
    load_clean_room_receipt,
    parse_clean_room_receipt,
    verify_clean_room_receipt,
    verify_in_clean_room,
    write_clean_room_receipt,
)
from bernstein.core.volunteer.consent import (
    CONSENT_RECEIPT_PREDICATE_TYPE,
    CONSENT_SCHEMA_VERSION,
    DEFAULT_CONSENT_PATH,
    GENESIS_ANCHOR,
    ChainLink,
    ConsentError,
    ConsentReceipt,
    build_consent_receipt,
    load_consent,
    parse_consent,
    verify_consent_receipt,
    write_consent,
)
from bernstein.core.volunteer.issue_sanitize import (
    ISSUE_TEXT_FENCE_LABEL,
    normalize_untrusted_text,
    sanitize_issue_text,
    strip_html_comments,
)
from bernstein.core.volunteer.lease_store import (
    DEFAULT_WORKER_KEY_PATH,
    LEASE_STORE_SCHEMA_VERSION,
    Lease,
    LeaseRefusal,
    LeaseRefusalReason,
    LeaseStore,
    LeaseStoreError,
    ReassignedLease,
    Submission,
    load_or_create_worker_key,
)
from bernstein.core.volunteer.manifest import (
    OSI_APPROVED_LICENSES,
    SUPPORTED_SCHEMA_VERSIONS,
    VOLUNTEER_MANIFEST_PATH,
    GateCommand,
    UnenforcedManifestFieldWarning,
    VolunteerManifest,
    VolunteerManifestError,
    canonical_manifest_bytes,
    load_manifest,
    load_manifest_from_repo,
    manifest_digest,
)
from bernstein.core.volunteer.registry import (
    BrowseResult,
    DroppedEntry,
    HTTPResponse,
    HTTPTransport,
    IndexEntry,
    browse_indexes,
)
from bernstein.core.volunteer.runner import (
    ALLOWED_REPO_SCHEMES,
    HOST_GIT_ENV_PASSTHROUGH,
    AgentArgvBuilder,
    AgentInvocation,
    ClaimedTask,
    DonorLimits,
    IssueTextSanitizer,
    RefusalStage,
    TaskDiff,
    TaskOutcome,
    TaskRefusal,
    WallClockBudget,
    build_prompt,
    host_git_env,
    mock_agent_argv,
    repo_url_problem,
    run_claimed_task,
)
from bernstein.core.volunteer.sandbox_profile import (
    BACKEND_PREFERENCE,
    PACKAGE_REGISTRY_HOSTS,
    SANDBOX_ENV_ALLOWLIST,
    VOLUNTEER_PROFILE_NAME,
    SandboxProfileRefusal,
    VolunteerSandboxProfile,
    backend_options,
    build_volunteer_profile,
    describe_refusal,
    effective_egress,
    profile_matches,
    sandbox_env,
)
from bernstein.core.volunteer.task_board import (
    DEFAULT_TASK_BOARD_PATH,
    HUB_TASK_ID_PREFIX,
    TASK_BOARD_SCHEMA_VERSION,
    HubTask,
    TaskBoard,
    TaskBoardError,
    TaskPublishError,
    hub_task_id,
    is_hub_native,
)
from bernstein.core.volunteer.task_finish import (
    REFUSAL_REASONS,
    SignedResultBundle,
    TaskProvenance,
    VolunteerRefusal,
    enforce_allowed_paths,
    finish_volunteer_task,
)
from bernstein.core.volunteer.wall_clock import (
    TERM_GRACE_SECONDS,
    WallClockOutcome,
    run_under_wall_clock,
)

__all__ = [
    "ALLOWED_REPO_SCHEMES",
    "BACKEND_PREFERENCE",
    "CLAIM_MARKER",
    "CLEAN_ROOM_REFUSAL_REASONS",
    "CLEAN_ROOM_VERIFY_PREDICATE_TYPE",
    "CLEAN_ROOM_VERIFY_SCHEMA_VERSION",
    "CONSENT_RECEIPT_PREDICATE_TYPE",
    "CONSENT_SCHEMA_VERSION",
    "DEFAULT_BUDGET_CONFIG_PATH",
    "DEFAULT_BUDGET_DIR",
    "DEFAULT_CLAIM_STALENESS",
    "DEFAULT_CLEAN_ROOM_RECEIPT_PATH",
    "DEFAULT_CONSENT_PATH",
    "DEFAULT_LEDGER_PATH",
    "DEFAULT_TASK_BOARD_PATH",
    "DEFAULT_WORKER_KEY_PATH",
    "GENESIS_ANCHOR",
    "HOST_GIT_ENV_PASSTHROUGH",
    "HUB_TASK_ID_PREFIX",
    "ISSUE_TEXT_FENCE_LABEL",
    "LEASE_STORE_SCHEMA_VERSION",
    "LEDGER_SCHEMA_VERSION",
    "OSI_APPROVED_LICENSES",
    "PACKAGE_REGISTRY_HOSTS",
    "REASON_BASE_COMMIT_UNAVAILABLE",
    "REASON_BUNDLE_INVALID",
    "REASON_MANIFEST_UNREADABLE",
    "REASON_PATCH_CONFLICT",
    "REFUSAL_REASONS",
    "SANDBOX_ENV_ALLOWLIST",
    "SUPPORTED_SCHEMA_VERSIONS",
    "TASK_BOARD_SCHEMA_VERSION",
    "TERM_GRACE_SECONDS",
    "VOLUNTEER_MANIFEST_PATH",
    "VOLUNTEER_PROFILE_NAME",
    "AgentArgvBuilder",
    "AgentInvocation",
    "BrowseResult",
    "BudgetClaimError",
    "BudgetConfigError",
    "BudgetLedger",
    "BudgetLedgerError",
    "BudgetLineItem",
    "BudgetRemaining",
    "BudgetReservation",
    "ChainLink",
    "ClaimClient",
    "ClaimComment",
    "ClaimRefusal",
    "ClaimedTask",
    "CleanRoomReceiptVerification",
    "CleanRoomResult",
    "CleanRoomVerificationReceipt",
    "ConsentError",
    "ConsentReceipt",
    "DonorLimits",
    "DroppedEntry",
    "GateCommand",
    "GateDivergence",
    "HTTPResponse",
    "HTTPTransport",
    "HubTask",
    "IndexEntry",
    "IssueClaimState",
    "IssueTextSanitizer",
    "Lease",
    "LeaseRefusal",
    "LeaseRefusalReason",
    "LeaseStore",
    "LeaseStoreError",
    "ReassignedLease",
    "RefusalStage",
    "SandboxProfileRefusal",
    "SignedResultBundle",
    "SkipDecision",
    "SkipReason",
    "Submission",
    "TaskBoard",
    "TaskBoardError",
    "TaskDiff",
    "TaskOutcome",
    "TaskProvenance",
    "TaskPublishError",
    "TaskRefusal",
    "UnenforcedManifestFieldWarning",
    "VolunteerBudget",
    "VolunteerManifest",
    "VolunteerManifestError",
    "VolunteerRefusal",
    "VolunteerSandboxProfile",
    "WallClockBudget",
    "WallClockOutcome",
    "backend_options",
    "browse_indexes",
    "budget_line_items",
    "build_clean_room_receipt",
    "build_consent_receipt",
    "build_prompt",
    "build_volunteer_profile",
    "canonical_manifest_bytes",
    "clean_room_receipt_from_result",
    "complete_claim",
    "describe_refusal",
    "effective_egress",
    "enforce_allowed_paths",
    "filter_local_profiles",
    "find_own_claim",
    "finish_volunteer_task",
    "host_git_env",
    "hub_task_id",
    "is_hub_native",
    "load_budget_config",
    "load_clean_room_receipt",
    "load_consent",
    "load_ledger",
    "load_manifest",
    "load_manifest_from_repo",
    "load_or_create_worker_key",
    "manifest_digest",
    "mock_agent_argv",
    "normalize_untrusted_text",
    "parse_clean_room_receipt",
    "parse_consent",
    "profile_matches",
    "refuses_claim",
    "remaining",
    "remaining_wall_clock_minutes",
    "repo_slug",
    "repo_url_problem",
    "reserve_claim",
    "run_claimed_task",
    "run_under_wall_clock",
    "sandbox_env",
    "sanitize_issue_text",
    "save_budget_config",
    "save_ledger",
    "should_skip",
    "strip_html_comments",
    "verify_clean_room_receipt",
    "verify_consent_receipt",
    "verify_in_clean_room",
    "with_budget_overrides",
    "write_clean_room_receipt",
    "write_consent",
]
