{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bernstein.fullname" . }}-auth
  labels:
    {{- include "bernstein.labels" . | nindent 4 }}
type: Opaque
data:
  auth-token: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
