"""Backward-compat shim — re-exports from bernstein.core.observability.prometheus."""

from bernstein.core.observability.prometheus import (
    agent_spawn_duration,
    agent_transition_reasons_total,
    agents_active,
    cost_usd_by_model_total,
    cost_usd_total,
    evolution_errors_by_type,
    evolve_proposals_total,
    generate_latest,
    get_transition_reason_histogram,
    merge_duration,
    record_transition_reason,
    registry,
    set_prometheus_enabled,
    task_duration_seconds,
    task_queue_depth,
    task_transition_reasons_total,
    tasks_active,
    tasks_total,
    update_metrics_from_status,
)

__all__ = [
    "agent_spawn_duration",
    "agent_transition_reasons_total",
    "agents_active",
    "cost_usd_by_model_total",
    "cost_usd_total",
    "evolution_errors_by_type",
    "evolve_proposals_total",
    "generate_latest",
    "get_transition_reason_histogram",
    "merge_duration",
    "record_transition_reason",
    "registry",
    "set_prometheus_enabled",
    "task_duration_seconds",
    "task_queue_depth",
    "task_transition_reasons_total",
    "tasks_active",
    "tasks_total",
    "update_metrics_from_status",
]
