"""The release bump commits every manifest it regenerates (#4053).

`scripts/bump_version.py` rewrites `pyproject.toml`, runs `uv lock`, then shells
`scripts/gen_distribution_manifests.py`, which writes five files. The bump PR is
opened by `create-pull-request`, and that action commits only the paths listed in
`add-paths`. That list was maintained by hand and named four of the seven, so
every major/minor bump PR opened with `plugin.json` and `CITATION.cff` still on
the previous version, reddening `Repo hygiene`'s drift check and
`test_repository_citation_cff_matches_the_package_version`.

Both gates were correct. The bump simply did not feed them, and the fix was a
manual regenerate-and-push on the release branch.

This test derives its expectation from `GENERATED_MANIFESTS` rather than
restating the list, because a second hand-kept list is what produced the bug.
Adding a sixth manifest without adding it to `add-paths` reddens this.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[2]
WORKFLOW = REPO_ROOT / ".github" / "workflows" / "release-major-minor.yml"

sys.path.insert(0, str(REPO_ROOT / "scripts"))
from gen_distribution_manifests import GENERATED_MANIFESTS

#: Bump inputs that are not generator outputs, so the derived set cannot cover them.
HAND_LISTED_INPUTS = ("pyproject.toml", "uv.lock")


def add_paths() -> tuple[str, ...]:
    """The `add-paths` block from the release workflow's create-pull-request step."""
    document = yaml.safe_load(WORKFLOW.read_text(encoding="utf-8"))
    for job in document["jobs"].values():
        for step in job.get("steps", []):
            paths = step.get("with", {}).get("add-paths")
            if paths is not None:
                return tuple(line.strip() for line in paths.splitlines() if line.strip())
    pytest.fail(f"no create-pull-request step with add-paths in {WORKFLOW.name}")


@pytest.mark.parametrize("manifest", GENERATED_MANIFESTS)
def test_add_paths_covers_every_generated_manifest(manifest: str) -> None:
    """A regenerated file the bump does not commit ships a release behind."""
    assert manifest in add_paths(), (
        f"{manifest} is regenerated by the bump but missing from add-paths in "
        f"{WORKFLOW.name}, so a bump PR would open with it stale"
    )


@pytest.mark.parametrize("required", HAND_LISTED_INPUTS)
def test_add_paths_still_carries_the_bump_inputs(required: str) -> None:
    """`pyproject.toml` and `uv.lock` are edited directly, not generated."""
    assert required in add_paths()


def test_add_paths_names_nothing_the_bump_does_not_touch() -> None:
    """The other direction: a stale entry reads as a promise the bump does not keep."""
    expected = set(GENERATED_MANIFESTS) | set(HAND_LISTED_INPUTS)
    assert set(add_paths()) == expected


def test_generated_manifests_matches_what_the_script_writes() -> None:
    """The constant is only trustworthy if it tracks the `targets` mapping.

    `main()` fails when the two disagree, so this asserts the pairing exists
    rather than re-deriving it: without it the constant could drift and every
    assertion above would keep passing against a stale list.
    """
    source = (REPO_ROOT / "scripts" / "gen_distribution_manifests.py").read_text(encoding="utf-8")
    assert "GENERATED_MANIFESTS is stale" in source

    # `.mcp.json` is read to project `mcp.json`; listing it as an output is the
    # mistake a hand-kept list makes, so pin that it is not in the set.
    assert ".mcp.json" not in GENERATED_MANIFESTS
    assert "mcp.json" in GENERATED_MANIFESTS
