"""Distribution-manifest contracts for the agent skill / plugin surface (#2369).

The MCP registry manifest (``server.json``), the plugin manifest
(``.plugin/plugin.json``), the Agent Plugins 1.0.0 root manifests
(``plugin.json`` / ``mcp.json``, #3540), and the bundled ``bernstein-run``
skill are release artifacts generated by
``scripts/gen_distribution_manifests.py``. These tests pin:

1. Version sync - every manifest carries the ``pyproject.toml`` version,
   so a release cannot ship a stale registry listing.
2. Shape - the manifests reference assets that actually exist in the
   tree (skills dir, commands, agents, rules, ``.mcp.json``).
3. Determinism - regenerating the manifests is byte-stable, so the
   release-workflow check step can diff instead of trusting hand edits.
"""

from __future__ import annotations

import importlib.util
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[2]


#: The MCP registry rejects a longer ``description`` with a 422 at publish time.
_REGISTRY_DESCRIPTION_MAX = 100


def _pyproject_version() -> str:
    with (_REPO / "pyproject.toml").open("rb") as fh:
        return tomllib.load(fh)["project"]["version"]


def test_server_json_version_matches_pyproject() -> None:
    data = json.loads((_REPO / "server.json").read_text(encoding="utf-8"))
    version = _pyproject_version()
    assert data["version"] == version
    packages = {p["registryType"]: p for p in data["packages"]}
    assert packages["pypi"]["identifier"] == "bernstein"
    assert packages["pypi"]["version"] == version
    # The registry schema forbids a top-level version on OCI packages;
    # the version rides in the identifier tag instead.
    assert "version" not in packages["oci"]
    assert packages["oci"]["identifier"] == f"ghcr.io/sipyourdrink-ltd/bernstein:{version}"


def test_server_json_description_fits_the_registry_limit() -> None:
    """The MCP registry caps ``description`` at 100 characters.

    It enforces this at publish time with a 422, which lands *after* the tag
    and the PyPI upload have already gone out - so the listing silently stays
    on the previous version while every other artifact ships. A description
    edit that overruns is invisible until then; this pins it at commit time
    instead.
    """
    data = json.loads((_REPO / "server.json").read_text(encoding="utf-8"))
    description = data["description"]
    assert len(description) <= _REGISTRY_DESCRIPTION_MAX, (
        f"server.json description is {len(description)} characters; the MCP registry "
        f"rejects anything over {_REGISTRY_DESCRIPTION_MAX} with a 422 during publish. "
        f"Shorten it: {description!r}"
    )


def test_plugin_manifest_version_and_paths() -> None:
    manifest = json.loads((_REPO / ".plugin" / "plugin.json").read_text(encoding="utf-8"))
    assert manifest["version"] == _pyproject_version()
    assert manifest["skills"] == "./skills/"
    for key in ("commands", "agents", "rules", "skills"):
        rel = manifest[key]
        assert (_REPO / rel).is_dir(), f"plugin.json {key} path {rel} missing"
    mcp_rel = manifest["mcpServers"]
    mcp = json.loads((_REPO / mcp_rel).read_text(encoding="utf-8"))
    assert "bernstein" in mcp["mcpServers"]


def test_bundled_skill_has_frontmatter_and_stays_ascii() -> None:
    skill_md = _REPO / "skills" / "bernstein-run" / "SKILL.md"
    body = skill_md.read_text(encoding="utf-8")
    assert body.startswith("---")
    assert "name: bernstein-run" in body
    assert "description:" in body
    assert "—" not in body, "em-dash characters are not allowed in shipped skill text"
    assert body.isascii(), "shipped skill text must stay ASCII"


def test_render_server_json_retags_oci_identifier_on_version_bump() -> None:
    spec = importlib.util.spec_from_file_location(
        "gen_distribution_manifests",
        _REPO / "scripts" / "gen_distribution_manifests.py",
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    rendered = json.loads(module.render_server_json("9.9.9"))
    packages = {p["registryType"]: p for p in rendered["packages"]}
    assert packages["oci"]["identifier"] == "ghcr.io/sipyourdrink-ltd/bernstein:9.9.9"
    assert "version" not in packages["oci"]
    assert packages["pypi"]["version"] == "9.9.9"


def _gen_module() -> object:
    spec = importlib.util.spec_from_file_location(
        "gen_distribution_manifests",
        _REPO / "scripts" / "gen_distribution_manifests.py",
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_CITATION_SAMPLE = """cff-version: 1.2.0
title: "Bernstein"
abstract: >-
  A folded block that a YAML round-trip would reflow.
version: "3.10.0"
date-released: "2026-07-26"
preferred-citation:
  type: software
  year: 2026
"""


def test_citation_cff_is_stamped_from_the_package_version() -> None:
    """A CITATION.cff behind the released version is drift, not a style nit.

    It shipped 3.10.0 while 3.14.159 was on PyPI (#3571), so anyone citing the
    project from the repository cited a version that was four releases old.
    """
    module = _gen_module()

    stamped = module.render_citation_cff("3.14.159", _CITATION_SAMPLE, today="2026-08-10")

    assert 'version: "3.14.159"' in stamped
    assert 'date-released: "2026-08-10"' in stamped
    assert "cff-version: 1.2.0" in stamped, "cff-version is a different key and must survive"
    assert "abstract: >-" in stamped, "the folded block must not be reflowed by the stamp"
    assert "  year: 2026" in stamped, "indented keys under preferred-citation are not top level"


def test_citation_cff_stamp_preserves_the_date_when_the_version_is_current() -> None:
    """Re-running on a matching version must not move date-released to today.

    ``--check`` compares the rendered projection against the file on disk. If
    the date tracked the clock, every day after a release would report drift and
    the gate would be noise within a week.
    """
    module = _gen_module()

    stamped = module.render_citation_cff("3.10.0", _CITATION_SAMPLE, today="2099-01-01")

    assert stamped == _CITATION_SAMPLE, "a matching version must render byte-identically"


def test_citation_cff_stamp_rejects_a_file_it_cannot_stamp() -> None:
    module = _gen_module()

    with pytest.raises(module.ManifestValidationError, match="date-released"):
        module.render_citation_cff("3.14.159", 'cff-version: 1.2.0\nversion: "3.10.0"\n', today="2026-08-10")


def test_citation_cff_stamp_rejects_a_document_it_cannot_fully_own() -> None:
    """A duplicate top-level key would leave a stale value the stamp never touched.

    ``re.sub(..., count=1)`` stamps the first match. With two ``version:`` keys
    the second keeps the old value, the projection then agrees with itself, and
    ``--check`` reports in sync while the artifact is wrong.
    """
    module = _gen_module()
    doubled = _CITATION_SAMPLE + 'version: "3.10.0"\n'

    with pytest.raises(module.ManifestValidationError, match="exactly one"):
        module.render_citation_cff("3.14.159", doubled, today="2026-08-10")


def test_citation_cff_stamp_rejects_a_non_scalar_version() -> None:
    """``version:`` opening a block leaves nothing for the stamp to replace."""
    module = _gen_module()
    block = 'cff-version: 1.2.0\nversion:\n  - "3.10.0"\ndate-released: "2026-07-26"\n'

    with pytest.raises(module.ManifestValidationError, match="not a scalar"):
        module.render_citation_cff("3.14.159", block, today="2026-08-10")


def test_citation_cff_stamp_rejects_a_date_that_only_looks_like_one() -> None:
    """A preserved ``date-released`` is still validated, not trusted."""
    module = _gen_module()
    bad = 'cff-version: 1.2.0\nversion: "3.14.159"\ndate-released: "last Tuesday"\n'

    with pytest.raises(module.ManifestValidationError, match="ISO 8601"):
        module.render_citation_cff("3.14.159", bad, today="2026-08-10")


def test_failed_provenance_puts_back_every_file_the_run_replaced(tmp_path: Path) -> None:
    """A failed release gate must not leave the tree half-rewritten.

    Provenance is verified against the regenerated ``server.json``, so the write
    happens first. If the check then fails and the new bytes stay, the manifests
    disagree about which version is being released -- and the next run finds no
    drift and reports itself in sync.
    """
    module = _gen_module()

    existing = tmp_path / "server.json"
    existing.write_text('{"version": "3.10.0"}\n', encoding="utf-8")
    created = tmp_path / "mcp.json"
    created.write_text("new content\n", encoding="utf-8")

    module._restore_replaced({existing: '{"version": "3.10.0"}\n', created: None})

    assert existing.read_text(encoding="utf-8") == '{"version": "3.10.0"}\n'
    assert not created.exists(), "a file this run created must be removed, not left empty"


def test_provenance_failure_restores_before_it_returns() -> None:
    """Pins the ordering the previous test cannot observe from outside."""
    source = (_REPO / "scripts" / "gen_distribution_manifests.py").read_text(encoding="utf-8")

    branch = source.partition("if not provenance.ok:")[2].partition("return 1")[0]
    assert branch, "expected a provenance failure branch in main()"
    assert "_restore_replaced(replaced)" in branch, (
        "the provenance failure path must put back what the write phase replaced"
    )


def test_repository_citation_cff_matches_the_package_version() -> None:
    """The checked-in file must already be stamped, or ``--check`` fails the release."""
    module = _gen_module()

    current = (_REPO / "CITATION.cff").read_text(encoding="utf-8")
    assert f'version: "{module.pyproject_version()}"' in current


def test_gen_script_check_mode_passes_and_is_idempotent(tmp_path: Path) -> None:
    check = subprocess.run(
        [sys.executable, str(_REPO / "scripts" / "gen_distribution_manifests.py"), "--check"],
        cwd=_REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert check.returncode == 0, check.stdout + check.stderr

    before = {
        "server.json": (_REPO / "server.json").read_bytes(),
        ".plugin/plugin.json": (_REPO / ".plugin" / "plugin.json").read_bytes(),
        "plugin.json": (_REPO / "plugin.json").read_bytes(),
        "mcp.json": (_REPO / "mcp.json").read_bytes(),
    }
    regen = subprocess.run(
        [sys.executable, str(_REPO / "scripts" / "gen_distribution_manifests.py")],
        cwd=_REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert regen.returncode == 0, regen.stdout + regen.stderr
    for rel, payload in before.items():
        assert (_REPO / rel).read_bytes() == payload, f"regeneration changed {rel}"


# --- Agent Plugins v1.0.0 root manifests (#3540) ------------------------

_AGENT_PLUGINS_SCHEMA_DIR = _REPO / "schemas" / "agent-plugins" / "1.0.0"
_PLUGIN_SCHEMA_ID = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
_MCP_SCHEMA_ID = "https://agent-plugins.org/schemas/1.0.0/mcp.schema.json"


def _load_gen_module():
    spec = importlib.util.spec_from_file_location(
        "gen_distribution_manifests_ap",
        _REPO / "scripts" / "gen_distribution_manifests.py",
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _vendored_validator(schema_file: str):
    import jsonschema

    schema = json.loads((_AGENT_PLUGINS_SCHEMA_DIR / schema_file).read_text(encoding="utf-8"))
    jsonschema.Draft202012Validator.check_schema(schema)
    return jsonschema.Draft202012Validator(schema)


def test_vendored_schemas_carry_the_pinned_ids() -> None:
    """The vendored schema files must be the 1.0.0 documents they claim to be.

    Validation is strictly offline: manifests are checked against these
    committed bytes, never against anything fetched from agent-plugins.org.
    """
    plugin_schema = json.loads((_AGENT_PLUGINS_SCHEMA_DIR / "plugin.schema.json").read_text(encoding="utf-8"))
    mcp_schema = json.loads((_AGENT_PLUGINS_SCHEMA_DIR / "mcp.schema.json").read_text(encoding="utf-8"))
    assert plugin_schema["$id"] == _PLUGIN_SCHEMA_ID
    assert mcp_schema["$id"] == _MCP_SCHEMA_ID


def test_root_plugin_json_validates_against_vendored_schema() -> None:
    data = json.loads((_REPO / "plugin.json").read_text(encoding="utf-8"))
    errors = sorted(
        _vendored_validator("plugin.schema.json").iter_errors(data),
        key=lambda e: e.json_path,
    )
    assert not errors, "\n".join(f"{e.json_path}: {e.message}" for e in errors)
    assert data["$schema"] == _PLUGIN_SCHEMA_ID
    assert data["name"] == "bernstein"
    assert data["version"] == _pyproject_version()


def test_root_mcp_json_validates_against_vendored_schema() -> None:
    data = json.loads((_REPO / "mcp.json").read_text(encoding="utf-8"))
    errors = sorted(
        _vendored_validator("mcp.schema.json").iter_errors(data),
        key=lambda e: e.json_path,
    )
    assert not errors, "\n".join(f"{e.json_path}: {e.message}" for e in errors)
    assert data["$schema"] == _MCP_SCHEMA_ID
    # The spec requires an explicit transport type on every server entry.
    for name, server in data["mcpServers"].items():
        assert server.get("type") in {"stdio", "streamable-http", "sse"}, name
    assert data["mcpServers"]["bernstein"]["type"] == "stdio"


def test_root_manifests_are_deterministic_projections() -> None:
    """Committed root manifests must equal their regenerated form byte-for-byte."""
    module = _load_gen_module()
    version = _pyproject_version()
    assert (_REPO / "plugin.json").read_text(encoding="utf-8") == (module.render_root_plugin_json(version))
    assert (_REPO / "mcp.json").read_text(encoding="utf-8") == (module.render_root_mcp_json())


def test_skill_discovery_matches_the_fixed_spec_location() -> None:
    """Every immediate child of ``skills/`` must be a discoverable skill.

    The spec's fixed discovery location is ``skills/``: each immediate child
    directory holding a regular ``SKILL.md`` is one skill, no deeper search.
    A child directory without a ``SKILL.md`` would ship dead weight that
    conformant hosts silently ignore, so it fails here instead.
    """
    module = _load_gen_module()
    discovered = module.discover_skills()
    children = sorted(p.name for p in (_REPO / "skills").iterdir() if p.is_dir())
    assert discovered == children
    assert "bernstein-run" in discovered
    for name in discovered:
        assert (_REPO / "skills" / name / "SKILL.md").is_file()


def test_dockerfile_has_mcp_registry_server_name_label() -> None:
    """The published image must carry the MCP registry server-name annotation.

    The MCP registry rejects a server.json whose OCI package image lacks the
    ``io.modelcontextprotocol.server.name`` label, so the Dockerfile must set it
    to the same identity the manifest declares.
    """
    import json as _json

    dockerfile = (_REPO / "Dockerfile").read_text(encoding="utf-8")
    server_name = _json.loads((_REPO / "server.json").read_text(encoding="utf-8"))["name"]
    assert "io.modelcontextprotocol.server.name" in dockerfile
    assert server_name in dockerfile


def test_docker_mcp_catalog_source_commit_and_project_are_valid() -> None:
    """The Docker MCP catalog entry must pin a real commit and the right repo.

    ``packaging/docker-mcp/server.yaml`` is hand-maintained: the commit hash
    cannot be known before the release commit exists, so nothing regenerates
    it. This pins the two fields the catalog validator enforces - a 40-char
    lowercase hex SHA and a ``source.project`` that agrees with the
    ``server.json`` repository URL - so a stale or mis-targeted entry fails at
    commit time instead of at catalog review.
    """
    import yaml

    catalog = yaml.safe_load(
        (_REPO / "packaging" / "docker-mcp" / "server.yaml").read_text(encoding="utf-8")
    )
    commit = catalog["source"]["commit"]
    assert re.fullmatch(r"[0-9a-f]{40}", commit), (
        f"server.yaml source.commit {commit!r} is not a 40-char lowercase hex SHA"
    )

    project = catalog["source"]["project"]
    server = json.loads((_REPO / "server.json").read_text(encoding="utf-8"))
    assert project == server["repository"]["url"], (
        f"server.yaml source.project {project!r} does not match "
        f"server.json repository.url {server['repository']['url']!r}"
    )


def test_publish_workflow_mcp_registry_is_idempotent() -> None:
    """The registry publish step must treat an already-published version as success.

    The MCP registry rejects re-submitting a live version with an HTTP 400
    ``cannot publish duplicate version``. This happens on any re-run or when the
    tag-push and workflow_dispatch triggers race to publish the same server.json.
    The listing is already correct in that case, so the step must swallow the
    duplicate rather than fail the release with a red check.
    """
    workflow = (_REPO / ".github" / "workflows" / "publish.yml").read_text(encoding="utf-8")
    # The publish step guards on the duplicate-version marker and exits 0 for it.
    assert "duplicate version" in workflow
    assert "idempotent" in workflow.lower()


# --- Generator-side schema validation of rendered root manifests ---------


def _write_json(path: Path, data: object) -> Path:
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return path


def _plugin_source_fixture(**overrides: object) -> dict[str, object]:
    source: dict[str, object] = {
        "name": "bernstein",
        "description": "orchestrator",
        "license": "Apache-2.0",
        "keywords": ["agents"],
    }
    source.update(overrides)
    return source


def test_render_root_plugin_json_rejects_malformed_source(tmp_path: Path) -> None:
    """A schema-invalid .plugin/plugin.json must fail generation, not ship."""
    module = _load_gen_module()
    module.PLUGIN_JSON = _write_json(tmp_path / "plugin.json", _plugin_source_fixture(name=42))
    try:
        module.render_root_plugin_json("9.9.9")
    except module.ManifestValidationError as exc:
        assert "$.name" in str(exc)
        assert "string" in str(exc)
    else:
        raise AssertionError("numeric name must raise ManifestValidationError")


def test_render_root_plugin_json_rejects_string_keywords(tmp_path: Path) -> None:
    module = _load_gen_module()
    module.PLUGIN_JSON = _write_json(tmp_path / "plugin.json", _plugin_source_fixture(keywords="agents"))
    try:
        module.render_root_plugin_json("9.9.9")
    except module.ManifestValidationError as exc:
        assert "$.keywords" in str(exc)
        assert "array" in str(exc)
    else:
        raise AssertionError("string keywords must raise ManifestValidationError")


def test_render_root_plugin_json_rejects_bad_name_pattern(tmp_path: Path) -> None:
    module = _load_gen_module()
    module.PLUGIN_JSON = _write_json(tmp_path / "plugin.json", _plugin_source_fixture(name="Bad..Name"))
    try:
        module.render_root_plugin_json("9.9.9")
    except module.ManifestValidationError as exc:
        assert "$.name" in str(exc)
        assert "pattern" in str(exc)
    else:
        raise AssertionError("pattern-violating name must raise ManifestValidationError")


def test_render_root_mcp_json_rejects_stdio_without_command(tmp_path: Path) -> None:
    """A stdio server entry without a command must fail generation."""
    module = _load_gen_module()
    module.MCP_JSON = _write_json(tmp_path / "mcp.json", {"mcpServers": {"broken": {"args": ["serve"]}}})
    try:
        module.render_root_mcp_json()
    except module.ManifestValidationError as exc:
        assert "$.mcpServers.broken" in str(exc)
        assert "command" in str(exc)
    else:
        raise AssertionError("stdio entry without command must raise ManifestValidationError")


def test_render_root_mcp_json_rejects_unknown_transport(tmp_path: Path) -> None:
    module = _load_gen_module()
    module.MCP_JSON = _write_json(
        tmp_path / "mcp.json",
        {"mcpServers": {"ws": {"type": "websocket", "url": "wss://example.invalid"}}},
    )
    try:
        module.render_root_mcp_json()
    except module.ManifestValidationError as exc:
        assert "$.mcpServers.ws" in str(exc)
    else:
        raise AssertionError("unknown transport type must raise ManifestValidationError")


def test_render_root_mcp_json_rejects_stray_server_keys(tmp_path: Path) -> None:
    module = _load_gen_module()
    module.MCP_JSON = _write_json(
        tmp_path / "mcp.json",
        {"mcpServers": {"bernstein": {"command": "bernstein", "restart": True}}},
    )
    try:
        module.render_root_mcp_json()
    except module.ManifestValidationError as exc:
        assert "$.mcpServers.bernstein" in str(exc)
    else:
        raise AssertionError("stray server keys must raise ManifestValidationError")


def test_render_root_mcp_json_rejects_reserved_env_names(tmp_path: Path) -> None:
    """The spec reserves PLUGIN_ROOT / PLUGIN_DATA env names for the host."""
    module = _load_gen_module()
    module.MCP_JSON = _write_json(
        tmp_path / "mcp.json",
        {"mcpServers": {"bernstein": {"command": "bernstein", "env": {"PLUGIN_ROOT": "/x"}}}},
    )
    try:
        module.render_root_mcp_json()
    except module.ManifestValidationError as exc:
        assert "PLUGIN_ROOT" in str(exc)
    else:
        raise AssertionError("reserved env name must raise ManifestValidationError")


def test_stdlib_schema_evaluator_agrees_with_jsonschema() -> None:
    """The script's stdlib evaluator and the real jsonschema must agree.

    The generator cannot import jsonschema (the publish job runs it with a
    bare python3), so its evaluator is hand-rolled; this cross-checks the
    verdict (valid / invalid) of both implementations over representative
    documents so the two cannot silently diverge.
    """
    import jsonschema

    module = _load_gen_module()
    cases: list[tuple[str, object]] = [
        ("plugin.schema.json", json.loads((_REPO / "plugin.json").read_text(encoding="utf-8"))),
        ("mcp.schema.json", json.loads((_REPO / "mcp.json").read_text(encoding="utf-8"))),
        ("plugin.schema.json", {"$schema": _PLUGIN_SCHEMA_ID, "name": 42}),
        ("plugin.schema.json", {"$schema": _PLUGIN_SCHEMA_ID, "name": "ok", "keywords": "x"}),
        ("plugin.schema.json", {"$schema": _PLUGIN_SCHEMA_ID, "name": "ok", "surprise": 1}),
        ("mcp.schema.json", {"$schema": _MCP_SCHEMA_ID, "mcpServers": {"a": {"type": "stdio"}}}),
        ("mcp.schema.json", {"$schema": _MCP_SCHEMA_ID, "mcpServers": {"a": {"type": "sse", "url": "https://x"}}}),
        ("mcp.schema.json", {"$schema": _MCP_SCHEMA_ID, "mcpServers": {"a": {"type": "nope"}}}),
        ("mcp.schema.json", {"$schema": "https://wrong", "mcpServers": {}}),
    ]
    for schema_file, document in cases:
        schema = json.loads((_AGENT_PLUGINS_SCHEMA_DIR / schema_file).read_text(encoding="utf-8"))
        reference_valid = jsonschema.Draft202012Validator(schema).is_valid(document)
        stdlib_errors = module._schema_errors(document, schema, schema)
        assert (not stdlib_errors) == reference_valid, (
            f"evaluator disagreement on {schema_file} for {document!r}: "
            f"jsonschema valid={reference_valid}, stdlib errors={stdlib_errors}"
        )
