"""Distribution-manifest contracts for the agent skill / plugin surface (#2369).

The MCP registry manifest (``server.json``), the plugin manifest
(``.plugin/plugin.json``), and the bundled ``bernstein-run`` skill are
release artifacts generated by ``scripts/gen_distribution_manifests.py``.
These tests pin:

1. Version sync - every manifest carries the ``pyproject.toml`` version,
   so a release cannot ship a stale registry listing.
2. Shape - the manifests reference assets that actually exist in the
   tree (skills dir, commands, agents, rules, ``.mcp.json``).
3. Determinism - regenerating the manifests is byte-stable, so the
   release-workflow check step can diff instead of trusting hand edits.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tomllib
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]


def _pyproject_version() -> str:
    with (_REPO / "pyproject.toml").open("rb") as fh:
        return tomllib.load(fh)["project"]["version"]


def test_server_json_version_matches_pyproject() -> None:
    data = json.loads((_REPO / "server.json").read_text(encoding="utf-8"))
    version = _pyproject_version()
    assert data["version"] == version
    packages = {p["registryType"]: p for p in data["packages"]}
    assert packages["pypi"]["identifier"] == "bernstein"
    assert packages["pypi"]["version"] == version
    # The registry schema forbids a top-level version on OCI packages;
    # the version rides in the identifier tag instead.
    assert "version" not in packages["oci"]
    assert packages["oci"]["identifier"] == f"ghcr.io/sipyourdrink-ltd/bernstein:{version}"


def test_plugin_manifest_version_and_paths() -> None:
    manifest = json.loads((_REPO / ".plugin" / "plugin.json").read_text(encoding="utf-8"))
    assert manifest["version"] == _pyproject_version()
    assert manifest["skills"] == "./skills/"
    for key in ("commands", "agents", "rules", "skills"):
        rel = manifest[key]
        assert (_REPO / rel).is_dir(), f"plugin.json {key} path {rel} missing"
    mcp_rel = manifest["mcpServers"]
    mcp = json.loads((_REPO / mcp_rel).read_text(encoding="utf-8"))
    assert "bernstein" in mcp["mcpServers"]


def test_bundled_skill_has_frontmatter_and_stays_ascii() -> None:
    skill_md = _REPO / "skills" / "bernstein-run" / "SKILL.md"
    body = skill_md.read_text(encoding="utf-8")
    assert body.startswith("---")
    assert "name: bernstein-run" in body
    assert "description:" in body
    assert "—" not in body, "em-dash characters are not allowed in shipped skill text"
    assert body.isascii(), "shipped skill text must stay ASCII"


def test_render_server_json_retags_oci_identifier_on_version_bump() -> None:
    spec = importlib.util.spec_from_file_location(
        "gen_distribution_manifests",
        _REPO / "scripts" / "gen_distribution_manifests.py",
    )
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    rendered = json.loads(module.render_server_json("9.9.9"))
    packages = {p["registryType"]: p for p in rendered["packages"]}
    assert packages["oci"]["identifier"] == "ghcr.io/sipyourdrink-ltd/bernstein:9.9.9"
    assert "version" not in packages["oci"]
    assert packages["pypi"]["version"] == "9.9.9"


def test_gen_script_check_mode_passes_and_is_idempotent(tmp_path: Path) -> None:
    check = subprocess.run(
        [sys.executable, str(_REPO / "scripts" / "gen_distribution_manifests.py"), "--check"],
        cwd=_REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert check.returncode == 0, check.stdout + check.stderr

    before = {
        "server.json": (_REPO / "server.json").read_bytes(),
        "plugin.json": (_REPO / ".plugin" / "plugin.json").read_bytes(),
    }
    regen = subprocess.run(
        [sys.executable, str(_REPO / "scripts" / "gen_distribution_manifests.py")],
        cwd=_REPO,
        capture_output=True,
        text=True,
        check=False,
    )
    assert regen.returncode == 0, regen.stdout + regen.stderr
    assert (_REPO / "server.json").read_bytes() == before["server.json"]
    assert (_REPO / ".plugin" / "plugin.json").read_bytes() == before["plugin.json"]


def test_dockerfile_has_mcp_registry_server_name_label() -> None:
    """The published image must carry the MCP registry server-name annotation.

    The MCP registry rejects a server.json whose OCI package image lacks the
    ``io.modelcontextprotocol.server.name`` label, so the Dockerfile must set it
    to the same identity the manifest declares.
    """
    import json as _json

    dockerfile = (_REPO / "Dockerfile").read_text(encoding="utf-8")
    server_name = _json.loads((_REPO / "server.json").read_text(encoding="utf-8"))["name"]
    assert "io.modelcontextprotocol.server.name" in dockerfile
    assert server_name in dockerfile
